import type { WorkflowGuide } from "./guided-help";

// Each entry describes the current staff interface, including its unfinished controls.
// Selectors are editorial constants scoped to main.content; no form actions run here.
type Lesson = [title: string, body: string, selector: string, missing?: string, caution?: string];
function guide(id: string, title: string, category: string, route: string, screen: string, description: string, lessons: Lesson[]): WorkflowGuide {
  return { id, title, category, description, duration: `${Math.max(2, Math.ceil(lessons.length * .7))} min`, steps: lessons.map(([heading, body, selector, missing, caution], index) => ({
    id: `${id}-${index + 1}`, title: heading, body, route, screen, selector, target: id,
    missing: missing ?? `Open ${screen} and wait for it to load. Check your permission and store scope if the area is unavailable. You can keep reading without changing a record.`, caution,
  })) };
}

export const extendedGuides: WorkflowGuide[] = [
  guide("monthly-billing", "Review and post monthly billing", "Money and accounts", "/billing/monthly", "Monthly billing", "Approve account terms, preview charges and create the monthly invoice.", [
    ["Choose the account and month", "Choose the intended customer account and billing month. The list is restricted to your permitted stores. Future months are blocked; select the correct current or historical unbilled period before proceeding.", ".monthly-billing"],
    ["Save approved account terms", "Set the first unbilled month, agreed calendar-day or full-month proration, tax treatment, recurring charges and discount dates. Insurance uses the recorded enrollment premium. Enter the actual approval reference; saving records a real billing policy.", ".monthly-plan", undefined, "Do not approve invented fees or tax treatment. These terms can affect real customer balances."],
    ["Review the invoice preview", "Preview monthly invoice calculates each charge, credit and included tax. Review existing-charge, transfer and historical test-payment warnings. A blocked account requires investigation; changing the month to evade a blocker can create an incorrect bill.", ".monthly-billing"],
    ["Post once and retain the invoice", "After checking the period and amounts, confirm the review and post. Charges, balance, invoice and audit are saved together. Changed records require a new preview. Open the saved invoice to review or print it; no email or collection is triggered.", ".monthly-preview", undefined, "Posting changes the account ledger. Tutorial reading never posts a bill."],
  ]),
  guide("tenants", "Customer records and consent", "Customer journey", "/tenants", "Tenants", "Create or find a customer, maintain contacts and locate signed documents.", [
    ["Find the existing customer first", "Search name, contact or ID in the left list. Select the matching person or business and confirm contact details. A customer record can exist before any tenancy; avoid creating a second record for the same customer.", ".accounts-list"],
    ["Add or edit the right details", "Add customer opens the customer form; Edit details updates the selected record. Choose Individual or Business, then enter names, company where relevant, phone, email and the required identity details. Complete the primary address, alternate contact, emergency and work sections before saving.", ".page-header"],
    ["Record the customer's actual consent", "In Consent and notes, select Email, SMS, WhatsApp and Phone only for channels the customer approved. Include useful operational notes. A contact number or an existing tenancy does not itself mean WhatsApp consent.", ".customer-detail", undefined, "Saving changes a real customer record. Do not enter invented identities or consent during training."],
    ["Read tenancy and booking records separately", "Tenancies and units shows the facility, occupancy, account and balance. Signed booking agreements lists the original booking PDF. Debit-order mandates have a separate reference, status and PDF; a signed mandate is not a successful collection.", ".customer-detail"],
    ["Continue into the correct workflow", "Use Reservations for a hold, Move in for the selected booking and Operations → Payments for the account ledger. A signed PDF can precede an active tenancy. Check payment, date and physical handover before telling the customer they can move in.", ".customer-detail"],
  ]),
  guide("leads", "Capture an enquiry and reserve a unit", "Customer journey", "/leads", "Lead to lease", "Record source and timing, then reserve real available inventory.", [
    ["Prepare the customer record", "Create or confirm the customer in Tenants first. In Add lead, select the correct facility and existing customer, enter the enquiry source and expected move-in date. Add lead saves a real sales enquiry.", ".leasing-form"],
    ["Check the pipeline", "Review Prospect, Facility, Source, Requirement and Stage in the table. This screen lists recorded leads; it does not provide a drag-and-drop stage editor. Use an operational task to track follow-up work when needed.", ".data-table"],
    ["Reserve the agreed space", "Reserve available unit requires a matching facility, customer and available unit, quoted rate and intended move-in date. Confirm the customer's choice before Reserve. Availability can change while you are looking; read any rejection before trying again.", ".leasing-form:nth-of-type(2)", undefined, "Reserve creates a live hold. It does not confirm payment, signature or handover."],
    ["Check the hold and follow up", "Open Reservations and find the customer to check the saved unit, expiry and rate. Continue with Manage a reservation, then Prepare a move-in. Use Calendar and Operations tasks for agreed follow-ups rather than relying on a tutorial tick.", ".data-table"],
  ]),
  guide("unsigned-move-in", "Prepare an unsigned rental agreement", "Customer journey", "/operations/move-in", "Move in", "Select the unit and account details before an agreement is sent.", [
    ["Choose the booking or unit", "Prefer Move in on the existing reservation. On Select unit, use the store and unit filters and check the selected unit's rate and availability. A signed reservation follows the separate Move-in checks path described in Prepare a move-in.", '[data-guide="move-in-workspace"]'],
    ["Confirm the account details", "Continue to Account details. Select the existing customer or use Add a new customer if there is no record. Check Start date, Monthly rent, Initial charge and Payment method. Initial charge is provisional until finance rules are confirmed. Do not create a duplicate customer or lease to bypass a blocker.", '[data-guide="move-in-workspace"]'],
    ["Review the lease before dispatch", "Read Lease agreement and the displayed summary. The chosen payment arrangement determines the appropriate agreement path. Review customer contact details before using the agreement submission button; this can create records and dispatch a real signing invitation.", '[data-guide="move-in-workspace"]', undefined, "Sending a lease is a real action. For training, read the fields and leave without submitting."],
    ["Follow signature and handover separately", "Check the result after submission. Use Integrations → BlendSign lease reconciliation for dispatch failures or reminders, and the account for completed documents. Signature, cleared funds, agreed date and physical key handover are distinct steps; continue with Prepare a move-in after signing.", '[data-guide="move-in-workspace"]'],
  ]),
  guide("accounts", "Read a customer account", "Money and accounts", "/operations/accounts", "Accounts", "Find balances, ledger entries, lease documents and account actions.", [
    ["Open the correct account", "Search account, tenant or unit in the account list. Select a result, then verify account number, customer, facility and unit above the balance. On a small screen, Back to accounts returns to the list.", ".accounts-list"],
    ["Understand the displayed balance", "Review Security status, Monthly rent, Unit type and Tenancy status together with the ledger. An amount due is an account total, not proof that a particular invoice is overdue. If Reconciliation required or Historical test entries is shown, finance must resolve the underlying records before the balance or statement is relied on.", ".account-detail"],
    ["Trace transactions and signed documents", "Read the dates, descriptions, types and amounts in the ledger. Completed lease opens the signed document; a completion certificate is offered for the supported signing provider. A missing document link is not evidence that a lease was signed.", ".account-detail .table-wrap"],
    ["Choose a specific account workflow", "Take payment posts a receipt, Transfer changes the occupied unit, Move out closes the occupancy and Account statement opens statement controls. Each has its own guide. Disabled actions can reflect the tenancy status; inspect the record instead of changing its status just to enable a button.", ".account-actions"],
  ]),
  guide("payments", "Record a received payment", "Money and accounts", "/operations/accounts", "Accounts", "Post confirmed funds and check the resulting ledger entry.", [
    ["Identify the account and receipt", "Search and select the customer account. Check the actual bank, till or terminal evidence, amount, date and reference against payments already recorded. Booking receipts before a tenancy use Move-in checks instead of this account form.", ".accounts-list"],
    ["Open Take payment", "Take payment opens Amount, Payment method, Reference and Date received. Choose EFT, Card, Cash or Bank debit to match the actual receipt. The default amount is the account balance; replace it with the amount really received.", ".account-actions"],
    ["Use a traceable reference", "Replace the generated reference with the customer's bank or receipt reference where available. Confirm the received date and amount to cents before Post payment. Posting a bank-debit receipt does not initiate a debit-order collection.", ".account-actions", undefined, "Post payment changes the ledger. A screenshot, pending callback, sandbox result or mandate alone is not proof of cleared funds."],
    ["Verify once, then reconcile", "After a successful post, inspect the new PAYMENT row and updated balance. If the response is unclear, refresh and inspect the ledger before repeating. Reconcile against the real bank or till evidence; use Netcash operations for provider exceptions and System audit for the operator trail.", ".account-detail .table-wrap"],
  ]),
  guide("transfer", "Transfer an active tenant", "Customer journey", "/operations/accounts", "Accounts", "Move an active tenancy to another available unit with the agreed rate and date.", [
    ["Confirm the existing tenancy", "Select the account and verify customer, facility, current unit and ACTIVE tenancy status. Transfer is disabled for other states. Confirm availability and the physical move with the customer before editing the account.", ".account-detail"],
    ["Choose the destination and date", "Open Transfer. New unit lists available units for this facility; choose the agreed destination. Set Effective date and use Monthly rent override only when the agreed rent differs. This form is not an inter-store transfer workflow.", ".account-actions"],
    ["Review before completing", "Confirm source and destination, rate and date. Use the Prorate calculator only as an indicative 31-day preview and get the actual billing treatment agreed before Complete transfer. Save only when the real transfer should be recorded.", ".account-actions", undefined, "Complete transfer changes occupancy. Do not submit a practice transfer on a live tenant."],
    ["Check records and access after the move", "Verify the account now shows the correct occupied unit, rate and ledger changes. Check Units & rates and the physical units. Review access separately if doors or permissions differ; a recorded transfer alone does not prove the customer's door access works.", ".account-info-grid"],
  ]),
  guide("move-out", "Complete a move-out", "Customer journey", "/operations/accounts", "Accounts", "Check final charges, deposit handling, unit condition and access follow-up.", [
    ["Review the account before departure", "Select the correct account, check the balance and tenancy, confirm notice and inspect the unit. Move out is available for ACTIVE or NOTICE GIVEN tenancies. Agree final charges and deposit handling through your approved process first.", ".account-detail"],
    ["Enter the actual departure details", "Open Move out and enter Move-out date and Final charge. Add the required move-out reason and condition notes, including outstanding physical actions. The default zero charge should only remain if it is correct.", ".account-actions"],
    ["Choose the deposit treatment deliberately", "Choose No deposit action, Refund requires processing or Apply deposit to balance, and enter the relevant deposit amount. Refund requires processing records follow-up; it does not send money to the customer.", ".account-actions", undefined, "Confirm deposit evidence and approval. Never create a refund or charge to satisfy a guide step."],
    ["Complete and check the outcome", "Complete move-out records the real departure. Verify tenancy and occupancy status, final ledger and the unit's availability. Resolve outstanding balances through finance and retain the original transaction history.", ".account-detail"],
    ["Close the physical and access work", "Record outstanding cleaning or damage in Operations maintenance before offering the unit again. Check Facial access revocation and physical access separately. Arrange the approved refund process where needed, then produce a checked statement from the account.", ".account-info-grid"],
  ]),
  guide("statements", "Statements and customer portal invitations", "Money and accounts", "/operations/accounts", "Accounts", "View, download or deliberately email the correct account statement.", [
    ["Start from the account", "Select the account, verify customer and facility, then choose Account statement. Use this account link so the correct account ID is carried forward; there is no generic statement for all customers.", ".account-actions"],
    ["Set the statement period", "On the statement screen, choose From and To and select View statement. Changing either date clears the old preview. Historical test contamination can block generation; escalate the reconciliation rather than bypassing it.", ".statement-filters", "Choose Account statement from the selected account to see the date filters."],
    ["Check the result before downloading", "Verify customer, account, facility, period, opening balance, each debit and credit and closing balance. Download PDF or Print uses the displayed statement. These controls do not create new charges.", ".statement-paper", "Choose View statement and resolve any reported error before a statement preview is available."],
    ["Send only after checking the recipient", "Email secure link requires a separate confirmation and uses the customer's verified email. Send / resend My STOR24 welcome is a different action for portal access instructions. Check the returned message and avoid repeated sends if delivery is uncertain.", ".statement-controls", "Open the selected account's statement screen first.", "Both email controls can send real messages. A welcome email does not confirm payment or grant physical access."],
  ]),
  guide("billing", "Billing, reconciliation and daily close", "Money and accounts", "/billing", "Billing & payments", "Use the finance shortcuts and understand what totals do and do not prove.", [
    ["Review the financial overview", "Collected this month, Outstanding balance and Active tenancies billed link to underlying account, collections and tenant screens. Treat summary figures as a starting point and reconcile exceptions before reporting them as final figures.", ".summary-strip"],
    ["Choose the right finance task", "Take payment opens customer accounts. Netcash operations checks payment outcomes against internal records. Invoices & statements and Daily close open Reports; Receipt audit opens System audit. Use the dedicated guides for those destinations.", ".module-grid"],
    ["Understand the current billing limits", "Autopay runs links to Collections; it does not launch an unattended debit run. Refund approvals links to the current adjustments information hub. A tile or saved billing default does not prove an invoicing, refund or recurring-payment worker is available.", ".module-grid"],
    ["Reconcile and close through the approved process", "Compare account receipts and report totals with bank, till and provider settlement evidence. Review End-of-day control in Operations for recorded closes and variances. This hub has no button to post a daily close; resolve discrepancies and retain finance approval separately.", ".module-grid"],
  ]),
  guide("collections", "Review arrears and plan follow-up", "Money and accounts", "/collections", "Collections", "Use the balance queue without confusing it with an automated collections run.", [
    ["Read the queue's scope", "The table shows up to 100 positive-balance accounts ordered by balance. Its Outstanding and Overdue accounts figures describe that displayed queue. Positive balance alone does not establish invoice age, a broken promise or an approved restriction.", ".summary-strip"],
    ["Check each account before contacting", "Note account number, tenant, facility and balance, then find the same account in Operations → Payments. Review recent receipts, credits and disputed or test entries before discussing an amount with the customer.", ".data-table"],
    ["Use the current follow-up process", "Start call queue and Export are currently unconnected controls on this screen. Use Phone for its current provider status, Operations tasks for follow-up and Reports for supported exports. Do not assume clicking these placeholders started calls or downloaded data.", ".toolbar"],
    ["Track promises and escalation", "Record the agreed contact outcome and next date through your approved customer notes/task process. Review consent before messaging. Notices, fees, refunds and access restrictions need their own authorised process; this queue does not execute them automatically.", ".data-table"],
  ]),
  guide("adjustments", "Handle corrections, reversals and refunds", "Money and accounts", "/adjustments", "Adjustments", "Understand the adjustment hub and route real corrections correctly.", [
    ["Recognise the information hub", "Account corrections describes Ledger adjustments, NSF payment reversal, Moved-out accounts and Refunds. The cards and New adjustment button currently do not open transaction forms, even where a card says Ready. Do not treat a click as a completed correction.", ".hub-stack"],
    ["Gather the original evidence", "Find the original account entry, payment reference, reason and required finance approval. Review account statements and the audit trail. Keep the original financial history; do not offset an error with an invented customer payment.", ".hub-stack"],
    ["Route stock corrections to Merchandise", "Inventory corrections describes stock adjustments and returns. Actual receipts, damage, adjustments and stock returns are in Merchandise → Record stock movement. A stock return alone does not create a customer financial refund; linked financial returns remain unfinished.", ".hub-stack"],
    ["Finish through the authorised process", "Escalate ledger credits, NSF reversals, write-offs and refunds to finance using the available approved process. Verify the financial posting and actual money movement separately. This tutorial explains the boundary; it does not enable missing transaction controls.", ".hub-stack"],
  ]),
  guide("netcash-operations", "Review Netcash payment outcomes", "Money and accounts", "/billing/netcash", "Netcash operations", "Trace provider attempts, ledger mismatches and settlement exceptions.", [
    ["Read the reconciliation boundary", "These controls compare STOR24 Payment and LedgerEntry records. The settlement warning means bank settlement is not yet reconciled through a verified imported Netcash statement. A matched internal payment is not proof of bank settlement.", ".netcash-ops-note"],
    ["Find the payment attempt", "Recent Netcash payments lists the latest 250 attempts, newest first. Match customer/account, amount and reference to the original transaction. Inspect the provider and internal statuses rather than relying on the browser return page.", ".netcash-payments-panel"],
    ["Investigate exceptions without reposting", "Separate pending, failed, test and review outcomes from eligible real receipts. Use the account ledger and System audit to investigate mismatches. Do not post another receipt just because a callback or browser result was delayed.", ".netcash-payments-panel"],
    ["Keep configuration and collection separate", "The Netcash test connection screen validates dedicated test credentials and controls sandbox tests. It does not prove live payment settlement, debit orders or eMandates. Escalate provider and finance discrepancies with the transaction reference.", ".netcash-ops-summary"],
  ]),
  guide("operations", "Tasks, maintenance and daily operations", "Facility operations", "/operations", "Operations", "Assign follow-up work, manage service requests and review close records.", [
    ["Choose the workflow", "Customer account workflows links to Move in, Payments, Transfer, Move out and Merchandise. Check the task and customer before entering the destination. Dedicated account tutorials explain the transaction fields.", ".operations-account-grid"],
    ["Create and follow an operational task", "New task asks for facility, title, description, priority and optional due date. Add enough detail for another member of staff to act. Assigned operational tasks shows the facility, assignee and due time; View request details can include a customer link.", ".work-list"],
    ["Complete only finished work", "Complete changes a real task's status. First carry out the work, check the outcome and retain any required evidence in the relevant record. An empty queue may simply mean there are no open tasks in scope.", ".work-list"],
    ["Create a maintenance request", "Use New request in Maintenance queue. Choose facility, optional unit, title, description, priority and due date. Selecting a unit removes it from bookable availability while linked maintenance remains open.", ".dashboard-grid", "Find Maintenance queue on Operations; its New request opens the form.", "A maintenance request can affect live availability immediately."],
    ["Resolve service status and inspect close records", "Use Start, Complete or Cancel for the real maintenance outcome, then verify the unit state. End-of-day control lists recorded business dates, status and cash variance; it is a review table, not a daily-close submission form.", ".dashboard-grid"],
  ]),
  guide("units", "Units, rates and inventory", "Facility operations", "/units", "Units & rates", "Filter physical inventory, maintain unit details and handle renumbering safely.", [
    ["Filter the inventory", "Choose store, type and status, then search for the physical unit. Display controls change the view. Check AVAILABLE, RESERVED, OCCUPIED and SERVICE against the actual workflow; a tutorial cannot make an occupied unit available.", ".inventory-toolbar"],
    ["Add or edit a unit", "Use Add unit or the row's edit control to review unit number, store, dimensions, type, floor, zone, monthly rate and tax before saving. Verify the physical unit and facility first. Changing a standard rate is not evidence that every existing tenant's contracted rent changed.", ".page-header"],
    ["Review types and dimensions", "Use the unit-type controls for the correct size and category. Check calculated area, labels and the related units. Do not remove or repurpose a type used by live stock simply to tidy the list.", ".page-stack"],
    ["Renumber deliberately", "Renumber units is a batch workflow. Review every old-to-new number, resolve duplicates and confirm the intended store before applying. Check the result against signage, reservations and maps afterwards.", ".page-header", undefined, "Renumbering affects operational references. UAT reset is a destructive test-data tool, not part of routine unit setup or training."],
    ["Use the responsible workflow for availability", "Use Reservations for holds, Move in/Transfer/Move out for occupancy and Operations maintenance for service restrictions. Recheck Units & rates and Facility map after the real action. Avoid forcing statuses to work around a booking blocker.", ".page-stack"],
    ["Review batch rate and hold tools", "Apply Midrand rates is a facility-specific rate action; confirm applicability and approved prices before running it. Release cancelled holds requires Confirm safe release and checks for active records. Read which units were released or protected rather than assuming all RESERVED units are now available.", ".page-header", undefined, "These tools change rates or availability. Do not use them to demonstrate guide progress."],
    ["Keep UAT reset out of routine work", "Reset UAT customers first requests a preview of affected records and then requires a separate confirmation. It removes test-customer data and can release units. Only an authorised test-cleanup process should use it after reviewing the exact scope; Cancel leaves the reset unconfirmed.", ".page-header", undefined, "A reset can delete records. The tutorial never opens its preview or submits its confirmation."],
  ]),
  guide("map", "View and maintain the facility map", "Facility operations", "/map", "Facility map", "Choose a floor, inspect units and edit a saved layout with permission.", [
    ["Choose the store and floor", "Select Facility and Floor / layout before inspecting the map. Check the legend against unit status. A map position describes the layout; availability still comes from the underlying inventory.", ".page-stack"],
    ["Inspect units and navigate", "Use the zoom controls and select a unit to inspect Unit details. Confirm number, type and status before directing a customer. Read-only staff can inspect the layout without editing it.", ".page-stack"],
    ["Use the toolbox in editing mode", "With editing permission, use Toolbox to place units, walls, doors, labels and other objects. Select an object to adjust its Properties, dimensions, rotation and label. Place a unit links to real inventory; check the correct unit instead of drawing a duplicate reference.", ".page-stack"],
    ["Review changes before saving", "Save layout persists the current floor. Resolve any duplicate-unit or changed-layout errors instead of overwriting another editor's work. Reopen the correct store and floor to confirm the saved arrangement.", ".page-header"],
    ["Handle floor duplication carefully", "Add floor creates a separate layout. Save the source before Duplicate floor, then inspect the destination and any replacement warning. Duplicating a drawing must not be mistaken for creating available physical inventory.", ".page-stack", undefined, "Layout and inventory edits affect staff and potentially public booking maps. Use approved physical plans."],
  ]),
  guide("merchandise", "Products, stock and returns", "Facility operations", "/operations/merchandise", "Merchandise", "Maintain products and record physical stock movements.", [
    ["Find a product and read available stock", "Search products or SKU and filter by category. Products and stock shows selling price, facility, status and reserved quantity. Available stock is on hand less reserved; do not promise reserved stock to another customer.", ".merchandise-catalogue-panel"],
    ["Add or edit the catalogue", "Add product requires facility, SKU, name, category, cost, selling price, opening stock and reorder point; barcode is optional. Open an existing row to manage its image, price and stock controls. Save only checked commercial values and actual opening stock.", ".merchandise-catalogue-panel"],
    ["Record the physical movement", "Record stock movement asks for product, RECEIPT, ADJUSTMENT, DAMAGE or RETURN, quantity, optional unit cost, reference and reason. Choose the movement that actually occurred and check the signed quantity expected by the form before recording it.", ".page-header"],
    ["Verify stock and keep refunds separate", "Check the updated available and reserved quantities after saving. Retain supplier or count evidence and investigate discrepancies. A RETURN stock movement does not issue a customer refund or complete the planned linked financial-returns workflow.", ".merchandise-catalogue-panel"],
  ]),
  guide("packages", "Build and maintain storage packages", "Facility operations", "/operations/merchandise", "Merchandise", "Choose component products, package pricing and customer-facing presentation.", [
    ["Start with facility stock", "In Customer-ready packages, choose New package and the facility. The studio uses that facility's products, prices and available stock. Configure missing products before constructing a package.", ".panel-spacious"],
    ["Build the package contents", "Choose component products and quantities, then review the package code, name, contents and selling price in the studio. Check the displayed availability against all required components; a package needs every component to be supplied.", ".panel-spacious"],
    ["Review the customer presentation", "Check image, badge and description alongside the commercial details. Save and reopen the package to verify the result. Active or Available to channels concerns catalogue visibility; it does not prove tenant checkout is enabled or ready for launch.", ".panel-spacious"],
    ["Maintain existing packages", "Open a package row to edit it. Recheck component quantities and price before saving and consider existing reserved orders. Follow the Paid packing supplies guide for actual collection or delivery.", ".panel-spacious"],
  ]),
  guide("fulfilment", "Supply paid packing materials", "Facility operations", "/operations/merchandise", "Merchandise", "Check paid orders and record physical collection or delivery.", [
    ["Open the paid-order queue", "Expand Customer purchases · collection and delivery to see Paid packing supplies. Match customer, account, order total and listed items. An empty queue is not permission to create a test purchase in production.", "details.panel"],
    ["Confirm the order is eligible", "Paid · awaiting supply is distinct from Supplied or Payment review — do not supply. Investigate payment review with finance before releasing stock. The existence of this staff queue does not mean customer checkout has been enabled.", "details.panel"],
    ["Hand over the listed items", "Check each product and quantity against the actual order. Record collection / delivery opens a confirmation. Use Not yet if the items have not all been handed over; Confirm supplied deducts stock and records the real supply.", "details.panel", undefined, "Do not confirm supply as a practice exercise. This changes real order and stock records."],
    ["Check the outcome", "Verify Supplied and the updated stock after the actual handover. If an error occurs, refresh and inspect the order before repeating. Handle missing items, returns and refunds through the approved exception process.", "details.panel"],
  ]),
  guide("insurance", "Insurance plans, enrolment and waivers", "Facility operations", "/insurance", "Insurance", "Record an approved cover decision without implying premium collection.", [
    ["Check the register", "Tenant insurance register lists active customer tenancies, facility/unit, account, decision, cover and premium. Locate the correct tenancy and review any existing ACTIVE, WAIVED or outstanding decision.", ".data-table"],
    ["Configure approved plans", "New plan records provider-approved plan code, name, scope, cover, premium, excess and policy details. Organisation-wide plans apply everywhere; facility plans only apply at that store. Confirm commercial approval before creating a plan.", ".page-header"],
    ["Record the customer's decision", "Choose an eligible plan and Enrol only after the customer agrees. Waive requires the real reason. End cover stops an active cover record. Read the confirmation and resulting status for the correct tenancy.", ".data-table", undefined, "Enrol, Waive and End cover change real cover records. Do not demonstrate them on a live customer."],
    ["Check the financial and provider follow-up", "Cover values are captured at enrolment so later plan changes do not rewrite the recorded decision. This is an operational register: premium posting and provider acceptance remain separate checks. Confirm those through the approved process.", ".summary-strip"],
  ]),
  guide("access", "Facial enrolment and revocation", "Facility operations", "/access", "Facial access", "Check consent, active tenancy, provider readiness and physical access.", [
    ["Check the prerequisites", "Confirm the correct active tenancy, completed handover and approved access process. Review Hikvision configuration and provider readiness with the administrator. A saved connection or payment does not prove enrolment and door access work.", ".customer-form"],
    ["Prepare consent and photograph", "Select Active tenancy by customer, facility and unit. Use a clear JPEG or PNG within the displayed 5 MB limit. Explain the alternative access method and record explicit biometric consent before selecting its confirmation.", ".customer-form", undefined, "Only use the customer's authorised photograph. Do not upload test faces or assert consent to try the tutorial."],
    ["Read the provider result", "Enrol facial access sends a real enrolment request. Read the response and inspect Biometric access register for status, consent and provisioned time. Escalate failures; an accepted request alone does not prove access at the physical door.", ".data-table"],
    ["Revoke and verify separately", "Revoke is available on active enrolments and changes real access. Use it for an authorised departure or consent withdrawal, inspect the result and complete controlled provider and door verification. Retention, alternative access and physical-door acceptance remain operational responsibilities.", ".data-table"],
  ]),
  guide("calendar", "Plan work with the calendar", "Facility operations", "/calendar", "Calendar", "Read scheduled tasks, follow-ups, viewings and move-outs in SAST.", [
    ["Read the scheduled work", "Calendar groups facility-scoped tasks, lead follow-ups, viewings and scheduled move-outs by day. Times use South African time. No scheduled work means nothing is returned for that day, not that every operational task is finished.", ".calendar-grid"],
    ["Open the source record", "Choose an item to open its linked workflow. Check customer, facility and due time before acting. This calendar is a linked view; it does not offer drag-and-drop rescheduling or a general appointment creation form.", ".calendar-grid"],
    ["Create or resolve work at its source", "Use Operations → New task to create a dated operational follow-up. Complete the actual task or update its source record through the appropriate workflow, then revisit Calendar to check the result. Reading this guide does not clear calendar entries.", ".calendar-grid"],
  ]),
  guide("prorate", "Use the proration preview", "Money and accounts", "/prorate", "Prorate calculator", "Understand the calculator's 31-day assumption before using its result.", [
    ["Enter the monthly rate", "Monthly rate (ZAR) changes the local preview only. Use the agreed rent and confirm whether the intended calculation is for move-in, transfer or move-out.", ".calculator-card"],
    ["Check the effective day and assumption", "This calculator uses a fixed 31-day month and includes the effective day: rate ÷ 31 × (31 − day + 1). Use a day from 1 to 31. It is not a date-aware calculator for February or a 30-day month.", ".calculator-card", undefined, "Do not use this preview as the final charge without checking the actual contract, calendar period and approved finance rules."],
    ["Apply only through the actual workflow", "Review the displayed number of days and daily rate. Nothing is posted by this page. Enter an approved amount through the relevant move-in, transfer or move-out workflow and verify the resulting ledger there.", ".calculation-result"],
  ]),
  guide("reports", "Choose and export a report", "Reports and oversight", "/reports", "Reports", "Choose report, period and facility, then validate the exported figures.", [
    ["Browse the available reports", "Use the category tabs and report cards to read purpose, format and permission. Category tabs filter the catalogue; select the actual report in Report parameters before exporting.", ".report-card-grid"],
    ["Set the exact parameters", "Choose Report, From, To and Facility. All permitted facilities uses your allowed scope. Verify the date range and report type before Export CSV; the server validates each run and your export permission.", ".report-parameters"],
    ["Check the export", "Open the downloaded CSV and confirm headings, facility, period, row counts and totals against source records. A downloaded file can still contain incomplete or unreconciled operational data; investigate unexpected zeros or differences before sharing it.", ".report-actions"],
    ["Handle restrictions and statements correctly", "If your role can view but not export, request the appropriate permission from your administrator. Customer account statements and their PDFs are available from the selected account's Account statement link, not every report card.", ".report-actions"],
  ]),
  guide("graphs", "Interpret portfolio graphs", "Reports and oversight", "/graphs", "Graphs", "Read occupancy, pipeline and revenue alongside their underlying records.", [
    ["Read scope and measures", "Portfolio KPIs show leads, conversion, physical occupancy, active tenancies, billed month to date and collections rate. Check the measure and time period rather than treating all figures as today's activity.", ".metric-grid"],
    ["Compare occupancy and sales", "Occupancy trend is reconstructed from occupancy records over 12 months. Lead pipeline groups leads created in the last 90 days; New leads covers seven days. These different windows explain why the charts need not match one another.", ".dashboard-grid"],
    ["Separate charged from collected", "Revenue index compares charges and collections over 12 months. Collected is not the same as a bank settlement reconciliation. Investigate differences in accounts, Netcash operations and finance reports before drawing conclusions.", ".revenue-dual-chart"],
    ["Check individual facilities", "Unit status by facility separates available, reserved/held, occupied and service/unavailable units. Investigate the underlying unit or occupancy record when a count looks wrong; this page displays data and does not edit it.", ".unit-status-table"],
  ]),
  guide("audit", "Trace activity in System audit", "Reports and oversight", "/audit", "System audit", "Read who did what, when, to which record and with which request reference.", [
    ["Understand the audit view", "System audit shows the latest 200 organisation events, newest first. Time is displayed in South African time. An older event may fall outside this limited view; its absence is not proof the action never happened.", ".data-table"],
    ["Correlate the evidence", "Match Time, Action, Actor, Target and Request reference to the issue. System indicates an automated or unavailable actor. Details can show Netcash validation statuses without displaying keys.", ".data-table"],
    ["Follow supported targets", "Document targets link to the related account; the NETCASH integration target opens its settings. Other targets may have no link. Keep the event and transaction references when escalating; do not copy credentials or customer identity documents into general notes.", ".data-table"],
    ["Verify the business outcome separately", "An attempted action or saved configuration is not proof of delivered email, bank settlement or a working door. Check the relevant account, provider status and physical workflow. This view is read-only and does not undo events.", ".data-table"],
  ]),
  guide("company", "Store setup and public visibility", "Administration", "/company", "Company & setup", "Configure the selected store, its hours and website exposure.", [
    ["Select the store before editing", "Use Store at the top to choose the facility. Add store creates a real separate store with a name and unique code. Confirm the intended portfolio structure before using it; setup is scoped to the selected store.", ".facility-actions"],
    ["Maintain contact and location details", "Store information includes legal and trading details, contacts, address, location, access hours and office hours. Set closed days and check each start/end time, including public holidays, before saving.", ".company-setup-panel"],
    ["Check public booking visibility", "Website booking includes Public store address and Show this store and its available units on the public website. Confirm the public slug, inventory, map, pricing and launch approval before enabling it. Online payments supported alone is not payment-provider readiness.", ".company-setup-panel", undefined, "These settings can expose the facility on the public website. Do not enable a store as a tutorial exercise."],
    ["Choose which attributes are published", "Open Attributes on website. Review unit and store attribute names, descriptions and Used. Only attributes marked Used are offered to website consumers. Save and inspect the actual public result after an approved change.", ".setup-nav"],
    ["Finish the other setup sections", "Tenant defaults controls required/default customer fields; Program defaults holds grouped operational settings. Use their separate guides. A Saved badge confirms stored configuration, not that every downstream workflow has implemented and tested that setting.", ".setup-nav"],
  ]),
  guide("tenant-defaults", "Configure tenant field defaults", "Administration", "/company", "Company & setup", "Review required fields across primary, alternate and work details.", [
    ["Open the correct store and section", "Select Store, then Tenant defaults in Site setup. Check that you are changing the intended facility's policy, not a customer's current record.", ".setup-nav"],
    ["Review all three field groups", "Primary address, Alternate contact and Work details each have Required and Default value controls. Check each tab, especially contact and address fields. Avoid applying a person's private details as defaults for other customers.", ".tenant-defaults", "Select Tenant defaults in Site setup to see these fields."],
    ["Keep consent and sensitive details individual", "Sensitive identity fields cannot be pre-filled. Do not use a default as evidence of an individual customer's permission to receive messages. Review the actual customer consent separately in Tenants.", ".tenant-defaults", "Select Tenant defaults first."],
    ["Save and check downstream behaviour", "Save tenant defaults, confirm success and reopen the section to verify the stored values. Confirm the actual customer-entry workflow enforces the intended fields before relying on the policy; a stored setting alone does not prove enforcement everywhere.", ".tenant-defaults", "Select Tenant defaults first."],
  ]),
  guide("program-defaults", "Program defaults: every settings group", "Administration", "/company", "Company & setup", "Walk through all 18 groups, from proration and payments to reservations.", [
    ["Select the facility and Program defaults", "Open Program defaults in Site setup. Review each tab against your approved operating policy. Save program defaults stores the groups together; changing tabs does not save. Saved configuration must still be checked in the actual consuming workflow.", ".setup-nav"],
    ...([
      ["General", "Review the general operating choices and customer/account behaviour for this store. Keep policy changes traceable and verify their effect in the actual workflow."],
      ["Proration", "Check the proration method and charge treatment against agreed contract rules. The separate Prorate calculator remains a fixed 31-day preview and does not prove these settings are applied."],
      ["Move In", "Review move-in defaults before staff prepare agreements and charges. These defaults do not replace signed agreement, verified payment, date or physical handover checks."],
      ["Move Out", "Review departure and charge rules alongside deposit treatment. A stored refund preference is not money returned to the customer or proof access was revoked."],
      ["Invoice", "Check invoice choices and periods with finance. Unattended invoicing workers are not enabled merely by storing these choices."],
      ["Payment Types", "Review payment names, descriptions, Allowed, Online and Reversals. Marking Online does not configure a merchant or validate a real payment channel."],
      ["Payments", "Review receipt and past-due treatment. Confirm actual receipt allocation behaviour with finance; never treat a pending provider attempt as cleared funds."],
      ["Credits", "Review global and per-ledger limits, required security levels, reset period and maximum merchandise discount. Stored thresholds do not create a credit or prove enforcement by every transaction route."],
      ["Refunds", "Review purchase-age limits, minimum and maximum refunds and required security level. Use the approved refund process; the adjustments hub does not currently provide a refund transaction form."],
      ["Daily Close", "Review automatic-close options and lead requirements. Operations currently displays recorded closes; saving an automatic option does not establish a running close worker."],
      ["Late Fees", "Review schedule, threshold and unit-specific setting with finance. Do not adopt a labelled foreign fee schedule without approved local policy or assume fees were posted."],
      ["Printing & Reports", "Check reporting period, fiscal start, store columns, start-of-day printing, font, collation and paper size. Confirm actual exports or printing support separately."],
      ["SMS", "Maintain predefined message text for the approved workflow. Saving text does not approve a provider template, obtain consent or send a message."],
      ["South Africa", "Review country, ZAR, metric units, decimal precision and finance-approved VAT treatment. Confirm current tax treatment with finance rather than treating a displayed default as authoritative."],
      ["Inter-store transfers", "Review enablement, approval, receipt confirmation and destination stores. These are inventory-transfer settings; the tenant Transfer form in Accounts lists units in the current facility."],
      ["Response lists", "Maintain credit reasons, call-note phrases, complimentary-unit reasons and unit notes so staff can record the actual reason. Do not replace individual evidence with a stock phrase."],
      ["Activity reasons", "Review which activities require explanations, including rate/status edits, credits, refunds and tenant changes. Verify enforcement in the applicable workflow after changing policy."],
      ["Reservations", "Review expiry days, first/subsequent follow-up intervals and reservation-fee treatment. Confirm actual hold dates and task behaviour after saving; the settings alone do not prove a worker ran."],
    ] as const).map(([tab, body]): Lesson => [tab, `Select the ${tab} tab. ${body}`, ".program-defaults-workspace", "Select Program defaults in Site setup, then the named tab. The guide does not switch tabs or alter settings for you."]),
    ["Save and verify the approved settings", "Choose Save program defaults after reviewing every intended change. Check the success message, reopen the section and verify values. Keep downstream worker, finance and staff acceptance checks separate from configuration storage.", ".program-defaults-workspace", "Select Program defaults first.", "Saving affects the store's real configuration. Do not experiment with policy values in production."],
  ]),
  guide("users", "Employees, invitations and permissions", "Administration", "/users", "Users & permissions", "Invite the right person, set store scope and maintain access.", [
    ["Review existing access first", "Search employees and inspect security level, store access, Active/Inactive and MFA. Review Security roles before granting privileges. Check the person already has no active or pending account.", ".data-table"],
    ["Invite an employee deliberately", "Add an employee collects their name, email, role and store scope. Confirm the address and intended role before issuing the invitation. Review Pending invitations and the displayed invitation result; do not assume the person has accepted or received email.", ".page-header", undefined, "An invitation can grant real access. Do not invite a practice address or grant owner privileges for training."],
    ["Adjust roles and custom permissions", "Changing the role dropdown saves a real role change immediately. Edit permissions opens the individual permission groups; review only the access required and save deliberately. Report export and integration management may require separate permissions from viewing a page.", ".data-table"],
    ["Deactivate departing staff", "Deactivate changes access immediately; Reactivate restores it for the selected employee. Confirm identity and authorised employment/access status first. Review the result and System audit; never deactivate your own access as an exercise.", ".data-table"],
    ["Check security setup", "MFA status shows whether two-step verification is enabled, not the employee's recovery codes. Each staff member configures their own authenticator in Settings. Keep onboarding acceptance and role/store verification separate from an invitation being created.", ".role-grid"],
  ]),
  guide("settings", "Settings, sign-in and account security", "Administration", "/settings", "Settings", "Find configuration and manage passwords, MFA and recovery codes.", [
    ["Find the appropriate settings screen", "Settings links to organisation/facilities, users, rates, documents and integrations. Several tiles lead to Company setup; follow the actual options there rather than assuming a dedicated editor exists for each tile.", ".module-grid"],
    ["Set up two-step verification", "In Two-step verification, Set up authenticator displays a QR code and manual setup option. Add the account to your authenticator, enter the six-digit code and choose Verify and enable. Do not share the QR code, setup key or one-time codes.", ".mfa-settings"],
    ["Keep recovery codes securely", "Recovery codes are shown once. Store them securely. Create new recovery codes invalidates the old set. Turning off two-step verification requires password and a valid code and returns you to sign-in; use it only for an authorised security change.", ".mfa-settings"],
    ["Change password and recover access", "Account password invalidates existing sessions when updated. If you cannot sign in, use the normal Forgot password flow; invitation and reset links are individual and time-limited. Ask an administrator for account-status issues instead of borrowing another person's sign-in.", ".page-stack"],
    ["Understand tutorial preferences", "Guide me is available after staff sign-in. Guide mode can be switched off at any time; Pause closes the panel and retains progress. Reading progress is private to your sign-in on this browser, not cross-device training certification.", ".module-grid"],
  ]),
  guide("communications", "Messaging consent, tests and delivery", "Administration", "/communications", "Communications", "Review provider readiness, templates, delivery statuses and retries.", [
    ["Review channels and templates", "Read the provider configuration and template table before sending. Draft/unapproved templates are not ready simply because their text is listed. Verify customer details and channel-specific consent in Tenants.", ".page-stack"],
    ["Understand the connection-test forms", "Twilio SMS and WhatsApp connection tests are owner-only and require configuration. A controlled test sends a real message; it does not create a customer or enable automatic messaging. Use only an approved recipient and test when authorised.", ".page-stack", undefined, "Do not send messages while practising a tutorial. Opening or reading this guide sends nothing."],
    ["Read the delivery log", "WhatsApp delivery log separates queued, sent, delivered, read and failed outcomes, showing direction, updated time and failure code. Sent is not delivered. No attempts means no matching log, not proof the provider is unavailable.", ".page-stack"],
    ["Retry only after investigating", "Retry appears for failed outbound messages and can send again. Check the failure, recipient consent, provider readiness and duplication risk first. Review the updated delivery result after an authorised retry.", ".page-stack"],
    ["Review automation separately", "Integrations contains the WhatsApp automation control and readiness information. Enabling automation can affect future customer messaging. A successful owner connection test does not approve templates, consent rules or launch of an automated programme.", ".page-stack"],
  ]),
  guide("integrations", "Provider health and lease reconciliation", "Administration", "/integrations", "Integrations", "Inspect connection health, signing failures, webhooks and outbound work.", [
    ["Check status and readiness", "Read Connection health and the summary. Distinguish configured credentials, a successful health check and a fully accepted business workflow. Payments, messaging, signing and physical access each have separate readiness requirements.", ".integration-table"],
    ["Review BlendSign lease reconciliation", "Find the lease's customer and facility, local status, provider envelope and latest error. Follow its account/document link where available. A local document record without a completed envelope is not a signed lease.", ".integration-table"],
    ["Use recovery actions carefully", "Retry dispatch can create or retry the provider dispatch; Send reminder sends a real invitation reminder. Check whether an envelope or invitation already exists and read the failure before acting. These buttons do not require you to complete the tutorial first.", ".reconciliation-action", "Recovery actions appear only on eligible lease rows. An empty or healthy list may have none.", "Retry dispatch and Send reminder can contact a real customer. Do not click them as a demonstration."],
    ["Review incoming and outgoing queues", "Webhook inbox shows incoming provider events. Transactional outbox shows queued outbound work and errors. A queued event is not completed delivery or settlement. Keep event, document and request references for support when work remains stuck.", ".dashboard-grid"],
    ["Change provider settings through the dedicated screen", "Use the separate Hikvision access control and Netcash test connection guides for those settings. Review WhatsApp automation readiness before an approved switch change. Do not alter server credentials or automation to clear a tutorial warning.", ".page-stack"],
  ]),
  guide("hikvision", "HikCentral connection and door mapping", "Administration", "/settings/integrations/hikvision", "Hikvision access control", "Store connection details and map only the intended facility doors.", [
    ["Review the company connection", "Check endpoint and credential-configured status. Only authorised integration managers should change the HikCentral server address, App Key, App Secret, optional TLS certificate pin or region index code.", ".page-stack"],
    ["Save credentials securely", "Use the dedicated credential form. Saved secrets are not returned to the screen; blank secret fields can preserve existing values as described by the placeholders. Confirm endpoint and provider details before saving or testing.", ".page-stack", undefined, "Credentials and connection checks affect the real provider. Never paste secrets into tutorial notes, screenshots or customer records."],
    ["Map each facility separately", "In Organisation and doors, choose Facility, enter the intended organisation index and one door index code per line. Only listed doors should be granted for that facility. Verify provider codes rather than substituting display names.", ".hikvision-facility-picker"],
    ["Complete controlled access verification", "Check saved configuration and health results, then follow the approved consent-led enrol/revoke test and physical-door verification. Configuration success alone is not launch approval. Use Facial access for the actual customer's enrolment or revocation.", ".page-stack"],
  ]),
  guide("netcash-settings", "Netcash test credentials and test gate", "Administration", "/settings/integrations/netcash", "Netcash test connection", "Validate the dedicated sandbox account without implying live payment readiness.", [
    ["Read the test-only scope", "This screen validates and stores a dedicated Netcash test account. It cannot itself submit payments or debit orders. Review current configuration and permission before entering account or service keys.", ".page-stack"],
    ["Validate the correct key set", "Enter the 11-digit test account number beginning with 5 and its Account Services, Debit Orders and Pay Now keys. Netcash validates the pairing before storage. Keys are encrypted and not shown again; do not put them into operational notes.", ".page-stack"],
    ["Inspect every validation result", "Latest provider check reports how many of the three services validated and their response statuses. Review failed services and account messages; a partial pass is not a fully working payment setup.", ".page-stack"],
    ["Keep test processing within its stated gate", "Test transaction processing has an explicit typed enablement confirmation. The screen limits current authority to controlled R10 Pay Now tests; debit orders, DebiCheck, eMandate and AVS remain unverified. Never enable or initiate them to try the guide.", ".page-stack", undefined, "A test-enable switch is a real configuration change. Sandbox success is not collected rent, settlement or move-in clearance."],
  ]),
  guide("phone", "Phone integration and caller handling", "Administration", "/phone", "Phone integration", "Understand the current telephony shell and handle enquiries through existing records.", [
    ["Read the current connection state", "Incoming caller and Caller ID log are configuration-shell views. The screen explicitly says caller events remain empty until a provider adapter is implemented and health-verified. Waiting for a call is not proof live telephony is connected.", ".dashboard-grid"],
    ["Find the customer through the working tools", "For a real call, use Tenants search and verify identity before discussing account information. Use Lead to lease for an enquiry, Reservations for a hold and Accounts for verified balance/payment questions.", ".dashboard-grid"],
    ["Record the follow-up", "Capture the actual outcome in the approved customer notes or an Operations task with a due date. Check communication consent. This page does not place calls, record call outcomes or automatically start the collections call queue.", ".dashboard-grid"],
  ]),
  guide("offline-readiness", "Check device readiness before an outage", "Offline work", "/offline-readiness", "Offline readiness", "Review tracked encrypted snapshots and practise unlocking the prepared device.", [
    ["Read the device register", "The latest recorded snapshot preparation for each facility/device shows device name, facility, preparer, refresh time and expiry. This view does not contain passphrases or the offline customer data itself.", ".data-table"],
    ["Resolve expiry and missing devices", "Ready, Expiring soon, Expired or Unknown describe the tracked expiry. An empty register means no tracked snapshot was prepared. Use Offline workspace on the actual device while online to download or refresh its encrypted copy.", ".data-table"],
    ["Verify on the device", "A readiness row is a server download record, not proof the local copy still exists or can be unlocked. Check the actual browser/device, unlock with the retained passphrase and read the snapshot's facility and age before relying on it.", ".data-table"],
    ["Plan for reconnecting", "Staff must understand that offline leads and unit requests wait in an encrypted outbox. A requested unit is not held until the server accepts it and returns a reservation reference. Use the full Offline workspace guide for capture, sync, conflicts and erasure.", ".data-table"],
  ]),
  guide("offline", "Offline preparation, capture and recovery", "Offline work", "/offline-workspace.html", "Offline workspace", "Prepare an encrypted copy, queue enquiries and reconcile them after reconnection.", [
    ["Prepare this device while online", "Sign in online first. Choose Facility, a recognisable Device name and an offline unlock passphrase of at least eight characters. Download and encrypt snapshot saves a device-local copy. Keep the passphrase securely; the readiness register does not know it.", "#setup-panel"],
    ["Unlock and inspect the snapshot", "Open saved offline information uses the passphrase to Unlock workspace. Check facility, snapshot time, expiry and any age warning. Units, Leads, Reservations and Tasks are read-only snapshot views and can become stale while other staff work online.", "#unlock-panel"],
    ["Capture an enquiry once", "Capture a new lead records name, mobile, optional email, unit type, expected move-in and notes. Record permission to contact and the actual Email, SMS and WhatsApp consent. Encrypt and queue lead secures the request on this device; it does not yet create a server-confirmed booking.", "#lead-form", "Unlock the snapshot before the lead form becomes available."],
    ["Request a unit without promising a hold", "Request a specific unit reveals the unit, quoted rate and intended payment method. Choose the customer's actual requirements. Tell them the unit remains unconfirmed until reconnection and successful sync return a reservation reference. No payment is taken offline.", "#request-reservation", "Unlock the workspace and review Specific unit request in the lead form."],
    ["Reconnect and check sync results", "When online and signed in, use Sync now and inspect both lead and reservation queues plus Recent sync receipts. Confirm server references rather than assuming a reduced queue count proves every stage succeeded. Do not recapture the same enquiry after an unclear response.", "#sync-now", "Unlock the saved workspace to see Sync now and the outbox."],
    ["Resolve conflicts and incomplete handoffs", "If another device reserved the unit first, use Choose another available unit to update the queued request. Review price/date and sync again. Lead creation, reservation confirmation and lease dispatch are separate results; follow remaining errors into the live portal.", "#reservation-outbox-list", "Unlock the workspace; reservation requests and any conflict actions appear in the outbox."],
    ["Refresh or erase with care", "Refresh offline copy updates the snapshot while online. Before Erase offline copy, ensure every unsynced enquiry and request has been recovered through the approved process. Erasing browser data can destroy the only local copy of queued work.", "#unlock-panel", undefined, "Do not erase or change passphrases during training with unsynced work present."],
    ["Use help during an outage", "Guide me on the offline page works from cached tutorial assets once this version has been loaded online. Its switch and reading position are device-specific and separate from the signed-in staff library. Tutorial reading never unlocks, syncs or edits the encrypted business data.", "#offline-guide-toggle"],
  ]),
];

// Statement steps must remain on the selected account's real URL, never a made-up ID.
for (const step of extendedGuides.find(item => item.id === "statements")!.steps.slice(1)) {
  step.routePattern = "^/operations/accounts/[^/]+/statement$";
}

export const extendedPageHelp = extendedGuides.filter(item => !["unsigned-move-in", "payments", "transfer", "move-out", "packages", "fulfilment", "tenant-defaults", "program-defaults"].includes(item.id))
  .map(item => ({ route: item.id === "statements" ? "/operations/accounts/[id]/statement" : item.steps[0].route,
    title: item.id === "merchandise" ? "Merchandise" : item.steps[0].screen, body: item.description, guideId: item.id }));
