import {db} from '@/lib/db';
import {Prisma} from '@/generated/prisma/client';
import {businessDeadline,defaultLeadSla,leadSlaSchema,slaFromStoreHours} from './lead-sla-policy';
import {emailProvider,escapeEmailHtml,type EmailMessage} from './email';
const DOMAIN='LEAD_SLA',STATE='LEAD_SLA_ESCALATION';
export async function leadSlaView(org:string,facilityId:string,now=new Date()){
  const facility=await db.facility.findFirst({where:{id:facilityId,organisationId:org},select:{id:true,name:true}});if(!facility)throw Error('FORBIDDEN');
  const profile=await db.configurationProfile.findFirst({where:{organisationId:org,facilityId,domain:DOMAIN,name:'policy'}});const store=await db.configurationProfile.findFirst({where:{organisationId:org,facilityId,domain:'STORE_INFORMATION',name:'Default',status:'READY'},select:{config:true,updatedAt:true}});const imported=slaFromStoreHours(store?.config);const policy=profile?leadSlaSchema.parse(profile.config):imported??defaultLeadSla;const calendarSource=profile?'Saved SLA policy':imported?'Saved store office hours':'Unconfirmed example hours';
  const leads=await db.lead.findMany({where:{facilityId,facility:{organisationId:org},stage:{notIn:['WON','LOST']}},select:{id:true,stage:true,createdAt:true,assignedTo:{select:{name:true}}},orderBy:{createdAt:'desc'},take:2001});if(leads.length>2000)throw Error('SLA_LEAD_LIMIT');
  const events=await db.auditEvent.findMany({where:{organisationId:org,entityType:'Lead',entityId:{in:leads.map(l=>l.id)},action:'lead.updated'},select:{entityId:true,occurredAt:true,after:true},orderBy:{occurredAt:'asc'}});
  const states=await db.configurationProfile.findMany({where:{organisationId:org,facilityId,domain:STATE,name:{in:leads.map(l=>l.id)}}});
  return {facility,policy,calendarSource,revision:profile?.updatedAt.toISOString()??null,rows:leads.map(l=>{const first=events.find(e=>e.entityId===l.id&&(e.after as {stage?:string}|null)?.stage&& (e.after as {stage:string}).stage!=='NEW');const due=businessDeadline(l.createdAt,policy);const state=states.find(p=>p.name===l.id);return {id:l.id,stage:l.stage,createdAt:l.createdAt.toISOString(),assignedTo:l.assignedTo?.name??null,dueAt:due.toISOString(),firstResponseAt:first?.occurredAt.toISOString()??null,overdue:!first&&l.stage==='NEW'&&due<now,lateResponse:!!first&&first.occurredAt>due,escalation:state?.status??'NOT_SENT'};})};
}
export async function saveLeadSla(org:string,actorId:string,facilityId:string,input:unknown,revision:string|null){const policy=leadSlaSchema.parse(input);await db.$transaction(async tx=>{const facility=await tx.facility.findFirst({where:{id:facilityId,organisationId:org}});if(!facility)throw Error('FORBIDDEN');await tx.$queryRaw`SELECT "id" FROM "Facility" WHERE "id"=${facilityId} FOR UPDATE`;const old=await tx.configurationProfile.findFirst({where:{organisationId:org,facilityId,domain:DOMAIN,name:'policy'}});if((old?.updatedAt.toISOString()??null)!==revision)throw Error('SLA_CONFIG_CONFLICT');const result=await tx.configurationProfile.upsert({where:{organisationId_facilityId_domain_name:{organisationId:org,facilityId,domain:DOMAIN,name:'policy'}},create:{organisationId:org,facilityId,domain:DOMAIN,name:'policy',status:'READY',config:policy},update:{config:policy,status:'READY'}});await tx.auditEvent.create({data:{organisationId:org,facilityId,actorId,action:'lead.sla.policy.updated',entityType:'ConfigurationProfile',entityId:result.id,after:{enabled:policy.enabled,hours:policy.hours,recipientCount:policy.recipients.length,windowCount:policy.windows.length}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return leadSlaView(org,facilityId);}
export async function processLeadSla(org:string,send=(message:EmailMessage)=>emailProvider().send(message)){const configs=await db.configurationProfile.findMany({where:{organisationId:org,domain:DOMAIN,status:'READY'}});let sent=0,review=0,claimed=0;for(const config of configs){if(!config.facilityId)continue;const view=await leadSlaView(org,config.facilityId);if(!view.policy.enabled)continue;for(const lead of view.rows.filter(r=>r.overdue&&r.escalation==='NOT_SENT').slice(0,1)){const claim=await db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "Lead" WHERE "id"=${lead.id} FOR UPDATE`;const current=await tx.configurationProfile.findUnique({where:{id:config.id}});if(!current||current.updatedAt.toISOString()!==view.revision||!leadSlaSchema.parse(current.config).enabled)return null;const live=await tx.lead.findFirst({where:{id:lead.id,facilityId:config.facilityId!,stage:'NEW'}});if(!live)return null;const exists=await tx.configurationProfile.findFirst({where:{organisationId:org,facilityId:config.facilityId!,domain:STATE,name:lead.id}});if(exists)return null;return tx.configurationProfile.create({data:{organisationId:org,facilityId:config.facilityId!,domain:STATE,name:lead.id,status:'CLAIMED',config:{dueAt:lead.dueAt,claimedAt:new Date().toISOString(),accepted:0,recipientCount:view.policy.recipients.length}}});});if(!claim)continue;claimed++;let accepted=0;try{for(const recipient of view.policy.recipients){const link=`https://portal.stor24.co.za/leads?lead=${encodeURIComponent(lead.id)}`;await send({to:recipient.email,subject:'STOR24 enquiry SLA — follow-up needed',text:`An enquiry at ${view.facility.name} has passed its ${view.policy.hours}-business-hour first-response deadline. Review it in the staff portal: ${link}`,html:`<p>An enquiry at ${escapeEmailHtml(view.facility.name)} has passed its ${view.policy.hours}-business-hour first-response deadline.</p><p><a href="${escapeEmailHtml(link)}">Review the enquiry</a></p>`,dlp:{organisationId:org,facilityId:config.facilityId!,resourceId:lead.id,approvedRecipient:recipient.email}});accepted++;}await db.configurationProfile.update({where:{id:claim.id},data:{status:'SENT',config:{dueAt:lead.dueAt,accepted,recipientCount:view.policy.recipients.length,completedAt:new Date().toISOString()}}});sent++;}catch{await db.configurationProfile.update({where:{id:claim.id},data:{status:'REVIEW_REQUIRED',config:{dueAt:lead.dueAt,accepted,recipientCount:view.policy.recipients.length,reviewAt:new Date().toISOString()}}});review++;}await db.auditEvent.create({data:{organisationId:org,facilityId:config.facilityId!,action:'lead.sla.escalated',entityType:'Lead',entityId:lead.id,after:{accepted,recipientCount:view.policy.recipients.length,reviewRequired:accepted!==view.policy.recipients.length}}});}}
  return {checkedAt:new Date().toISOString(),claimed,sent,review};
}
