export const privacyNoticeVersion = "stor24-privacy-2026-09-24-v1";
export const privacySections = [
  { title: "Who is responsible", body: "STOR24 is a trading name of Blend Property 20 (Pty) Ltd, registration 2016/031577/07. Our business and Midpoint facility address is Store 1 – Midpoint, 162 Tonetti Street, Halfway House, Midrand, 1685. Contact bookings@stor24.co.za or +27 11 380 9400 and ask for the person handling privacy requests." },
  { title: "Booking and account information", body: "We collect your name, email, mobile number, chosen unit, dates and selected extras to respond to your request, reserve space and administer your storage agreement. Required fields are marked in the form; without them we cannot complete an online booking. Optional enquiry details help us recommend storage. Please do not include identity documents, banking credentials or sensitive personal details in free-text enquiries. We also keep agreement, payment-status and account records needed to deliver the service, reconcile balances and handle disputes." },
  { title: "Contact choices", body: "Choose the optional booking-update channels you want to use. Leaving them unticked does not subscribe you to marketing. Verification codes and communications needed to secure or fulfil your transaction are separate from optional updates. You can ask us to change your contact preferences using the contact details above. We verify requests before changing account information. A booking is not consent to unrelated marketing." },
  { title: "Identity and precinct access", body: "Identity documents are used for the identity review explained at the upload step. Where facial-photo collection is enabled, its separate notice explains the access purpose, review and retention settings before upload. Uploading a photo does not itself activate precinct access. Facial access arrangements and the final policy are under review. Contact us before submitting if you cannot use facial recognition or need to discuss another means of entry. We do not promise an alternative that has not been agreed with the precinct operator." },
  { title: "How information is used and shared", body: "Authorised STOR24 staff use relevant information to manage your enquiry, agreement, account and access. Service providers may process the information needed for hosting, communications, electronic signatures, payments and precinct access. Relevant services include Google reCAPTCHA for abuse prevention and, where used for your transaction, Twilio, Netcash, BlendSign and Hikvision. Enquiry automation may pass details to our CRM. Service providers may process information outside South Africa; contact us for information about the providers and safeguards applicable to your request. We may also disclose information where legally required or needed to establish or defend a lawful claim." },
  { title: "Storage and retention", body: "We retain information for its stated service purpose and applicable legal, accounting or dispute requirements. Identity and facial-image collection have specific notices and retention settings. Portal photo deletion does not itself confirm deletion of a provider or device copy; those copies require separate handling. Backup and audit records may have different retention requirements. Ask us for the retention arrangements applicable to your records. We assess deletion requests against those requirements rather than promising that every record can be erased immediately." },
  { title: "Cookies and browser storage", body: "Our sites use session and browser storage to support sign-in, verification and booking continuity. Google reCAPTCHA helps prevent automated abuse and may process device and interaction information. Clearing browser storage may interrupt an unfinished booking or sign you out. Optional marketing choices are separate from these service and security functions." },
  { title: "Your rights and requests", body: "You can ask what personal information we hold, request access or correction, raise an objection or request deletion where applicable. Contact bookings@stor24.co.za with the subject Privacy request and a brief description. Include your booking reference if available, but do not email a full ID copy, password, PIN or verification code. We may need proportionate identity verification before releasing or changing records. If we must retain information or cannot fulfil a request, we will explain the relevant reason. You can also complain to South Africa’s Information Regulator." },
  { title: "About this notice", body: "This notice describes the current service. It does not replace the separate information presented for identity or facial-photo collection, or your signed agreement. The formal PAIA manual and final biometric-policy review remain in progress. Changes to this notice will carry a new edition date; they do not retrospectively change your signed agreement." },
] as const;

