/** Small, standards-compliant uncompressed ZIP. Filenames are generated by the server. */
export function reportBundle(files:{name:string;bytes:Uint8Array}[]) {
  const chunks:Buffer[]=[],directory:Buffer[]=[];let offset=0;
  const crc=(bytes:Uint8Array)=>{let value=0xffffffff;for(const byte of bytes){value^=byte;for(let bit=0;bit<8;bit++)value=(value>>>1)^(value&1?0xedb88320:0);}return (value^0xffffffff)>>>0;};
  for(const file of files) {
    if(!/^[a-zA-Z0-9._-]{1,100}$/.test(file.name))throw new Error("INVALID_BUNDLE_NAME");
    const name=Buffer.from(file.name),bytes=Buffer.from(file.bytes),checksum=crc(bytes);
    const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x800,6);local.writeUInt32LE(checksum,14);local.writeUInt32LE(bytes.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(name.length,26);
    const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0x800,8);central.writeUInt32LE(checksum,16);central.writeUInt32LE(bytes.length,20);central.writeUInt32LE(bytes.length,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE(offset,42);
    chunks.push(local,name,bytes);directory.push(central,name);offset+=local.length+name.length+bytes.length;
  }
  const centralBytes=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralBytes.length,12);end.writeUInt32LE(offset,16);
  return Buffer.concat([...chunks,centralBytes,end]);
}
