import { buildLeaseClauses, renderLeaseDocument, type LeaseClauseContext } from "./lease-agreement-content";

// Immutable review edition. Publish a NEW version after legal changes; never rewrite
// this edition or historical reservation content/PDFs. No pricing policy is activated here.
export const STORAGE_TERMS_VERSION = "storage-terms-review-2026-09-10";
export const STORAGE_TERMS_STATUS = "Working draft for legal review - not legal-approved";
export const STORAGE_TERMS = [
  { title: "1. Our agreement and your booking schedule", body: "These storage terms accompany your personalised booking schedule and the eight summary acknowledgements. STOR24 means the facility operator identified in your final booking schedule; you means the named customer or its authorised representative. The schedule must identify the operator's legal name, registration and VAT details where applicable, contact and service address, customer, facility, unit, commencement date, agreed charges and payment method. Missing operator or pricing information must be resolved before production use. Mandatory South African law prevails, followed by expressly agreed schedule particulars and these terms. A website update does not retrospectively replace your accepted edition." },
  { title: "2. Storage service and commencement", body: "The unit is for self-storage of lawful goods only, not accommodation, manufacturing, retail trading or occupation as business premises. No postal or registered-business address is provided unless separately agreed in writing. The licence runs month to month from the schedule date. Unit sizes are approximate; inspect suitability before moving in. If we cannot make the agreed unit available, we will offer an agreed alternative or refund prepaid charges for the unavailable service. Signing or reserving does not itself issue keys or activate access: required identity checks, cleared agreed payment and operational confirmation must first be completed." },
  { title: "3. Prices, VAT and amounts due", body: "The booking schedule must separately show monthly rent, its VAT treatment, any deposit, initial rent period, optional goods and the total due before you commit. These terms do not create an undisclosed fee or authorise a higher checkout amount. Where VAT applies, the tax and VAT-inclusive total must be disclosed; an unclear quote must be corrected before production payment. Monthly rent is payable in advance on the agreed due date. Mid-month prorating and payment for a following month apply only if the period, calculation and amount are expressly shown in the agreed schedule. A controlled test payment is not settlement of the actual move-in balance." },
  { title: "4. Deposits, increases and refunds", body: "A deposit is payable only when its amount is expressly included in the schedule; this review edition does not automatically impose a one-month deposit. A deposit is not a substitute for rent or cancellation notice. At move-out we will provide an itemised account of lawful deductions for unpaid agreed charges and damage beyond fair wear, and refund the undisputed balance within 14 business days after handover and reconciliation, subject to any shorter statutory period. Deposit interest will be handled as required by applicable law and the agreed schedule. Proposed rent or deposit increases require at least one calendar month's written notice, no retrospective application, and preservation of your cancellation rights." },
  { title: "5. Payment methods and debit-order mandates", body: "Use only verified STOR24 payment instructions and the supplied reference. Verify any purported bank-account change with us through an independently established contact. Card payment and EFT are processed through the designated payment channel; proof of EFT alone is not cleared payment. Choosing debit order or signing this storage agreement is not a completed bank mandate. A separate secure mandate must specify the account holder, amount or calculation, collection date, frequency and cancellation process and be accepted through the approved provider. Cancelling a mandate does not by itself cancel storage or extinguish amounts lawfully owed. Do not send bank credentials, PINs or OTPs to STOR24. Disputed or failed payments must be reconciled before any repeat collection." },
  { title: "6. Move-out and cancellation", body: "For this draft month-to-month arrangement, give at least 14 calendar days' written notice before your intended month-end termination date. We will acknowledge the effective date and final account in writing. Any statutory cooling-off, fixed-term cancellation or other mandatory right remains available and overrides a more restrictive condition. No automatic full following-month penalty is imposed by this draft. Remove all goods and personal locks, return issued keys or credentials and leave the unit clean and undamaged, fair wear excepted, by the agreed handover time. Charges for continued occupation must reflect actual lawful occupation and disclosed rates; they do not waive either party's rights." },
  { title: "7. Lawful goods and prohibited items", body: "You confirm that you own the goods or have authority to store them and that storage does not infringe anyone else's rights. Do not store stolen or unlawful goods, explosives, fuels, flammable or hazardous substances, weapons or ammunition without lawful written approval, live animals or plants, perishables, waste, infectious material, goods attracting pests or creating odours, or anything posing a safety or environmental risk. Do not charge batteries or operate equipment in a unit without written permission. Tell us immediately about a suspected prohibited item, leak, infestation or danger. Emergency protective action must be proportionate and lawful; reasonable attributable clean-up costs may be charged with an explanation and evidence." },
  { title: "8. Packing, condition and care", body: "You choose how to pack and arrange your goods and must keep exits, ventilation and fire equipment clear, respect load limits and avoid overstacking. Check and report unit defects before moving in and promptly report later damage or damp. Do not drill, nail, paint, wire, alter or attach fixtures without written consent. You are responsible for damage caused by you or people you authorise, excluding fair wear and damage for which we are responsible. Do not leave waste in shared areas. Facilities and packing advice do not guarantee that every item is suitable for storage." },
  { title: "9. Access, keys and facility rules", body: "Access is during the facility's notified hours, subject to reasonable safety and identity controls. Keep credentials secure and report lost keys or compromised access immediately. Visitors, movers and drivers you admit must follow reasonable notified rules, speed limits, parking directions and equipment instructions. Use a suitable lock and check that your unit is secured. Where keys are collected at the guard house, the person collecting must be authorised and handover recorded. Leaving a key with staff does not create an unlimited custody obligation. Reasonable changes to access hours will be communicated in advance where practicable; urgent safety restrictions will be explained." },
  { title: "10. Our access to a unit", body: "For routine inspection, repairs or maintenance we will normally give at least seven days' notice and arrange reasonable access. We may enter without prior notice where reasonably necessary to respond to an emergency, prevent imminent harm or comply with lawful authority. Any lock removal must be necessary and proportionate, recorded and communicated as soon as practicable. We will take reasonable care and secure the unit afterwards. This is not a general permission to search or dispose of your property." },
  { title: "11. Important risk and insurance notice", body: "IMPORTANT: Stored goods can be damaged or lost through fire, water, theft, pests or other events. Facility security does not guarantee prevention of all loss, and rental does not include insurance unless your schedule expressly says so. Arrange suitable cover for the nature and value of your goods and check exclusions and claim requirements with your insurer. Tell us promptly about any incident and preserve relevant evidence. Nothing here excludes liability that cannot lawfully be excluded, including liability for gross negligence, fraud or wilful misconduct, or removes statutory consumer remedies." },
  { title: "12. Responsibility and third-party claims", body: "Each party remains responsible to the extent required by law for loss caused by its breach or negligent or wrongful conduct. You are responsible for reasonable substantiated third-party claims caused by your unlawful storage or wrongful acts, only to the extent attributable to you or people you authorise. You do not indemnify us for our own wrongful conduct or liability that law does not allow us to transfer. Use trolleys, lifts, gates and shared areas with reasonable care and follow displayed safety instructions. Notify us of unsafe equipment; a risk warning does not excuse failure to maintain equipment reasonably." },
  { title: "13. Arrears, breach and lawful remedies", body: "We will notify you of a material breach, the remedy required and the applicable time to remedy before cancellation or enforcement, except where law permits urgent protective action. Any mandatory notice or remedy period prevails. Interest, collection or administrative charges apply only if specifically disclosed, agreed and lawful; this draft does not automatically impose 24 percent interest, attorney-and-client costs or a re-entry fee. We will consider a genuine dispute and provide an account. Access restrictions, any claimed lien and recovery proceedings must follow applicable law. There is no waiver of protection against unlawful dispossession or permission for unlawful self-help." },
  { title: "14. Uncollected goods", body: "Non-payment or failure to collect does not automatically transfer ownership of your goods to us. We will make reasonable attempts to contact you using recorded contact details and give notices required by law before seeking any lawful remedy. Sale or disposal requires a lawful basis and applicable notice or court process; this draft does not authorise automatic disposal after 60 days. Where a lawful sale takes place, we will account for proceeds, lawful costs and the balance, and explain any claimed shortfall. Urgent handling of dangerous goods remains subject to the proportionate safety provisions above." },
  { title: "15. Packages, custom selections and merchandise", body: "Packages are optional. Your accepted schedule records the selected products, quantities and once-off price; browsing a recommendation does not add a charge. Custom selections are costed from the confirmed product prices and quantities before acceptance. We will not substitute materially different products or increase the agreed price without consent. For a unit-ready order we will confirm preparation and arrange placement in the unit before the agreed handover; notify us promptly of missing or damaged items. If goods are unavailable, we will offer an agreed replacement or refund the unavailable portion. Statutory quality, return and refund rights remain unaffected. Cancelling storage does not automatically resolve a goods order: we will separately reconcile supplied and unsupplied goods and any lawful refund." },
  { title: "16. Interruption and events beyond reasonable control", body: "Tell us promptly if the unit becomes unusable. We will communicate material interruptions, take reasonable steps to mitigate them and agree an alternative where possible. If the contracted storage cannot be provided, charges for the unavailable period will be adjusted or refunded as legally required. Either party may seek termination where continued performance is not reasonably possible, with reconciliation of prepaid amounts. An event beyond reasonable control does not remove duties already owed, statutory remedies or responsibility for failure to take reasonable precautions." },
  { title: "17. Personal information and verification", body: "We use relevant customer, contact, booking and payment-status information to administer storage, communicate service matters, verify authority, protect safety and meet legal obligations. Identity documents or biometric data should be requested only where justified, with the purpose and safeguards explained. We use appropriate service providers under confidentiality and security arrangements and retain information only for legitimate operational or legal periods. You may request access or correction and raise a privacy concern through our contact page; you may also complain to the Information Regulator. Marketing consent is separate and optional. This agreement does not give blanket irrevocable consent for credit-bureau reporting, unrelated marketing or unrestricted sharing. Any lawful credit reporting requires its own applicable notices and process." },
  { title: "18. Notices, complaints and disputes", body: "Keep your recorded email, telephone and service address current. Send notices or complaints through the facility contact details or the website contact page, quoting your booking reference; keep a copy. We will acknowledge them and seek a fair resolution. Electronic notices must be capable of being retained and should not be treated as received where delivery is known to have failed. Nothing prevents you approaching a competent court, the National Consumer Commission, an applicable ombud or other competent authority. South African law applies without excluding mandatory consumer protections or lawful jurisdiction." },
  { title: "19. Changes, transfers and severability", body: "Agreed changes must be recorded in a durable form identifying what changed and when; electronic agreement may be used where lawful. We will not rewrite your previously accepted document when website wording changes. You may not transfer the unit or agreement without consent, which will not be unreasonably withheld where appropriate. Any operator transfer must be lawful, communicated and preserve your accrued rights. Failure to enforce a right immediately is not a permanent waiver. If a provision is unenforceable, the remaining lawful provisions continue so far as they can operate fairly." },
  { title: "20. Electronic acceptance and retained copy", body: "Before signing, read the personalised schedule, summary acknowledgements, important risk notices and this exact terms edition. You may ask questions and correct details before accepting. Acceptance requires your positive action; checkboxes are not preselected. The system retains the accepted text, its version and fingerprint, clause acknowledgements, signer name and signing time with the signed PDF. Download and retain your copy. A storage signature is separate from a bank mandate and is not proof of payment, insurance, stock fulfilment or access activation. This edition is a working draft supplied for legal review and controlled testing; legal and commercial approval remains required before production reliance." },
] as const;

export function storageTermsText() {
  return [`FULL STORAGE TERMS AND CONDITIONS`, `Terms version: ${STORAGE_TERMS_VERSION}`, STORAGE_TERMS_STATUS, "", ...STORAGE_TERMS.flatMap(s => [s.title, s.body, ""])].join("\n");
}

export function buildReviewLeaseClauses(ctx: LeaseClauseContext) {
  return buildLeaseClauses(ctx).map(clause => ({ ...clause, body: ({
    term_and_rent: `Storage starts on ${ctx.startDate.toISOString().slice(0, 10)} and runs month to month. The recorded monthly rate is R ${ctx.monthlyRate.toFixed(2)}. VAT treatment, any deposit and first-period calculation must be disclosed in the final schedule before production payment; these draft terms add no undisclosed charge. See full terms 3-6.`,
    access_and_security: "Access and keys require the agreed payment and operational checks. Follow the facility hours and safety rules, keep credentials secure and report lost keys. Security is not insurance. See full terms 9-10.",
    insurance_and_liability: "IMPORTANT RISK NOTICE: Goods may be lost or damaged. Rental does not include insurance unless expressly agreed. Arrange appropriate cover. Responsibility for damage and third-party claims is limited to what is lawful and attributable to each party; statutory rights and liability that cannot be excluded remain intact. Read full terms 11-12 before initialling.",
    default_and_termination: "For this draft month-to-month arrangement, give at least 14 calendar days' written notice before the intended month-end termination. Statutory rights take precedence. Breach remedies require lawful notice and procedure; there is no automatic disposal of goods or waiver of protection against unlawful dispossession. See full terms 6 and 13-14.",
    data_and_privacy: "Relevant information is processed to administer storage, verify authority and meet legal obligations, with appropriate safeguards. Marketing is separate and optional. No blanket credit-reporting or biometric consent is created. See full terms 17-18.",
  } as Partial<Record<string, string>>)[clause.key] || clause.body }));
}

export function renderReviewLeaseDocument(ctx: LeaseClauseContext) {
  const legacy = renderLeaseDocument(ctx);
  const schedule = legacy.split("\n\n")[1].replace(" (excl. applicable tax)", " (VAT treatment to be confirmed before production payment)");
  return ["STOR24 STORAGE AGREEMENT", `Version: ${STORAGE_TERMS_VERSION}`, STORAGE_TERMS_STATUS, "", "YOUR BOOKING SCHEDULE", schedule,
    "Deposit / first-period calculation: no additional charge authorised by this draft; final itemised schedule required before production payment.", "", "YOUR SUMMARY ACKNOWLEDGEMENTS",
    ...buildReviewLeaseClauses(ctx).flatMap(c => [c.title, c.body, ""]), storageTermsText()].join("\n");
}
