import { db } from "@/lib/db";
import { requireFacility, facilityWhere, type RequestScope } from "@/lib/scope";
import { unitIsOperational } from "@/lib/floor-availability";
import { effectiveUseTypes } from "@/lib/product-line";
import { isTestPayment } from "@/lib/payments/payment-evidence";
import { REPORT_SOURCE_LIMIT, ReportError } from "@/lib/visual-report-engine";
import { visualReportDatasets, type VisualReportQuery, type VisualReportRow } from "@/lib/visual-report-contract";
import { decryptReportArtifact } from "@/lib/visual-report-security";
import { z } from "zod";

const iso=(date:Date|null|undefined)=>date?.toISOString()??null;
const name=(c:{companyName:string|null;firstName:string|null;lastName:string|null}|null)=>c?(c.companyName||[c.firstName,c.lastName].filter(Boolean).join(" ")):null;
const customerSelect={companyName:true,firstName:true,lastName:true} as const;
const facilitySelect={name:true} as const;
const tenancySelect={facility:{select:facilitySelect},customer:{select:customerSelect},account:{select:{accountNumber:true}}} as const;
async function rawVisualReportSource(scope:RequestScope, query:VisualReportQuery):Promise<VisualReportRow[]> {
  if(query.facilityId) await requireFacility(scope,query.facilityId);
  const facility={...facilityWhere(scope),...(query.facilityId?{id:query.facilityId}:{})};
  const facilityId=query.facilityId?query.facilityId:scope.unrestrictedFacilities?undefined:{in:scope.facilityIds};
  const direct={organisationId:scope.organisationId,...(facilityId?{facilityId}:{})};
  const take=REPORT_SOURCE_LIMIT+1;
  const period={gte:new Date(`${query.from}T00:00:00+02:00`),lt:new Date(new Date(`${query.to}T00:00:00+02:00`).getTime()+86400000)};
  const range=(field:string,key:string)=>query.dateField===key?{[field]:period}:{};
  const interval=query.intervalMode?{startDate:query.intervalMode==="whole-period"?{lte:period.gte}:{lt:period.lt},OR:[{endDate:null},{endDate:query.intervalMode==="whole-period"?{gte:period.lt}:{gt:period.gte}}]}:{};
  const bounded=<T>(rows:T[])=>{if(rows.length>REPORT_SOURCE_LIMIT)throw new ReportError("REPORT_LIMIT");return rows;};
  switch(query.dataset) {
    case "tenants": return bounded(await db.tenancy.findMany({where:{facility,...range("startDate","start"),...range("endDate","end"),...range("noticeDate","notice")},take,orderBy:{id:"asc"},select:{...tenancySelect,status:true,productLine:true,paymentMethod:true,startDate:true,endDate:true,noticeDate:true,customer:{select:{...customerSelect,email:true,phone:true}},account:{select:{accountNumber:true,balance:true,currency:true}},occupancies:{where:{status:{in:["ACTIVE","NOTICE_GIVEN"]}},select:{monthlyRate:true,unit:{select:{number:true}}},take:101}}})).map(t=> {
      if(t.occupancies.length>100)throw new ReportError("REPORT_LIMIT");
      // Sum Decimal values through Prisma Decimal, preserving exact cents.
      const rate=t.occupancies.reduce((sum,o)=>sum.add(o.monthlyRate),t.account.balance.mul(0));
      return {facility:t.facility.name,account:t.account.accountNumber,customer:name(t.customer),email:t.customer.email,phone:t.customer.phone,status:t.status,units:t.occupancies.map(o=>o.unit.number).join(", "),product:t.productLine,paymentMethod:t.paymentMethod,monthlyRate:rate.toFixed(2),balance:t.account.balance.toFixed(2),currency:t.account.currency,start:iso(t.startDate),end:iso(t.endDate),notice:iso(t.noticeDate),unitCount:t.occupancies.length};
    });
    case "units": return bounded(await db.unit.findMany({where:{facility,combinedIntoUnitId:null},take,orderBy:{id:"asc"},include:{facility:{select:{name:true,closedFloors:true}},unitType:true}})).map(u=>({facility:u.facility.name,unit:u.number,floor:u.floor,type:u.unitType.name,status:u.status,effectiveStatus:unitIsOperational(u,u.facility.closedFloors)?u.status:"CLOSED_FLOOR",products:effectiveUseTypes(u).join(" | "),monthlyRate:u.monthlyRate.toFixed(2),area:u.unitType.areaSqMetres===null?null:Number(u.unitType.areaSqMetres),operational:unitIsOperational(u,u.facility.closedFloors)}));
    case "occupancies": return bounded(await db.occupancy.findMany({where:{tenancy:{facility,...range("noticeDate","notice")},...range("startDate","start"),...range("endDate","end"),...interval},take,orderBy:{id:"asc"},select:{status:true,startDate:true,endDate:true,monthlyRate:true,accessState:true,unit:{select:{number:true}},tenancy:{select:{...tenancySelect,noticeDate:true}}}})).map(o=>({facility:o.tenancy.facility.name,account:o.tenancy.account.accountNumber,customer:name(o.tenancy.customer),unit:o.unit.number,status:o.status,start:iso(o.startDate),end:iso(o.endDate),notice:iso(o.tenancy.noticeDate),monthlyRate:o.monthlyRate.toFixed(2),accessState:o.accessState}));
    case "ledger": return bounded(await db.ledgerEntry.findMany({where:{account:{customer:{organisationId:scope.organisationId},tenancy:{facility}},...range("effectiveAt","date")},take,orderBy:{id:"asc"},select:{id:true,type:true,effectiveAt:true,amount:true,taxAmount:true,description:true,reversalOfId:true,account:{select:{accountNumber:true,currency:true,customer:{select:customerSelect},tenancy:{select:{facility:{select:facilitySelect}}}}}}})).map(e=>({facility:e.account.tenancy!.facility.name,account:e.account.accountNumber,customer:name(e.account.customer),entry:e.id,type:e.type,date:iso(e.effectiveAt),amount:e.amount.toFixed(2),tax:e.taxAmount.toFixed(2),currency:e.account.currency,description:e.description,reversalOf:e.reversalOfId}));
    case "payments": return bounded(await db.payment.findMany({where:{account:{customer:{organisationId:scope.organisationId},tenancy:{facility}},NOT:[{status:{in:["TEST_PENDING","TEST_SUCCEEDED"]}},{environment:"sandbox"}],...range("createdAt","date"),...range("processedAt","processed")},take,orderBy:{id:"asc"},select:{id:true,status:true,amount:true,currency:true,method:true,provider:true,environment:true,idempotencyKey:true,createdAt:true,processedAt:true,failureCode:true,account:{select:{accountNumber:true,customer:{select:customerSelect},tenancy:{select:{facility:{select:facilitySelect}}}}}}})).filter(p=>!isTestPayment(p)).map(p=>({facility:p.account.tenancy!.facility.name,account:p.account.accountNumber,customer:name(p.account.customer),payment:p.id,status:p.status,method:p.method,provider:p.provider,amount:p.amount.toFixed(2),currency:p.currency,date:iso(p.createdAt),processed:iso(p.processedAt),failure:p.failureCode}));
    case "leads": return bounded(await db.lead.findMany({where:{facility,...range("createdAt","date"),...range("expectedMoveIn","expectedMoveIn"),...range("nextActionAt","nextAction")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},customer:{select:customerSelect},source:true,stage:true,productLine:true,assignedTo:{select:{name:true}},createdAt:true,expectedMoveIn:true,nextActionAt:true}})).map(l=>({facility:l.facility.name,customer:name(l.customer),source:l.source,stage:l.stage,product:l.productLine,assignedTo:l.assignedTo?.name??null,date:iso(l.createdAt),expectedMoveIn:iso(l.expectedMoveIn),nextAction:iso(l.nextActionAt)}));
    case "insurance": return bounded(await db.insuranceEnrollment.findMany({where:{...direct,...range("acknowledgedAt","date"),...range("effectiveFrom","start"),...range("endedAt","end")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},tenancy:{select:tenancySelect},plan:{select:{name:true}},status:true,providerName:true,coverageAmount:true,monthlyPremium:true,excessAmount:true,acknowledgedAt:true,effectiveFrom:true,endedAt:true,waiverReason:true}})).map(e=>({facility:e.facility.name,account:e.tenancy.account.accountNumber,customer:name(e.tenancy.customer),status:e.status,plan:e.plan?.name??null,provider:e.providerName,coverage:e.coverageAmount?.toFixed(2)??null,premium:e.monthlyPremium?.toFixed(2)??null,excess:e.excessAmount?.toFixed(2)??null,date:iso(e.acknowledgedAt),start:iso(e.effectiveFrom),end:iso(e.endedAt),waiver:e.waiverReason}));
    case "products": return bounded(await db.product.findMany({where:direct,take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},sku:true,name:true,category:true,quantityOnHand:true,quantityReserved:true,reorderPoint:true,sellingPrice:true,active:true}})).map(p=>({facility:p.facility.name,sku:p.sku,product:p.name,category:p.category,onHand:p.quantityOnHand,reserved:p.quantityReserved,available:p.quantityOnHand-p.quantityReserved,reorderPoint:p.reorderPoint,sellingPrice:p.sellingPrice.toFixed(2),active:p.active}));
    case "stock": return bounded(await db.stockMovement.findMany({where:{product:direct,...range("createdAt","date")},take,orderBy:{id:"asc"},select:{product:{select:{facility:{select:facilitySelect},sku:true,name:true}},type:true,quantity:true,unitCost:true,reason:true,createdAt:true}})).map(m=>({facility:m.product.facility.name,sku:m.product.sku,product:m.product.name,type:m.type,quantity:m.quantity,unitCost:m.unitCost?.toFixed(2)??null,reason:m.reason,date:iso(m.createdAt)}));
    case "sales": {
      const orders=bounded(await db.merchandiseOrder.findMany({where:{...direct,isTest:false,...range("createdAt","date"),...range("fulfilledAt","fulfilled")},take,orderBy:{id:"asc"},select:{id:true,facilityId:true,status:true,total:true,currency:true,createdAt:true,fulfilledAt:true,payment:{select:{status:true,idempotencyKey:true,environment:true}},account:{select:{accountNumber:true,customer:{select:customerSelect}}},items:{select:{name:true,quantity:true},take:101}}}));
      const facilities=await db.facility.findMany({where:facility,select:{id:true,name:true}}); const labels=new Map(facilities.map(f=>[f.id,f.name]));
      return orders.filter(o=>!o.payment||!isTestPayment(o.payment)).map(o=>{if(o.items.length>100)throw new ReportError("REPORT_LIMIT");return {facility:labels.get(o.facilityId)??"Unknown",account:o.account.accountNumber,customer:name(o.account.customer),order:o.id,status:o.status,paymentStatus:o.payment?.status??null,total:o.total.toFixed(2),currency:o.currency,items:o.items.map(i=>`${i.quantity} × ${i.name}`).join(" | "),quantity:o.items.reduce((n,i)=>n+i.quantity,0),date:iso(o.createdAt),fulfilled:iso(o.fulfilledAt)};});
    }
    case "closes": {
      // PostgreSQL DATE is stored at UTC midnight, independent of SAST timestamps.
      const dateWhere=query.dateField==="date"?{businessDate:{gte:new Date(query.from),lte:new Date(query.to)}}:range("closedAt","closed");
      return bounded(await db.dailyClose.findMany({where:{...direct,...dateWhere},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},businessDate:true,status:true,expectedCash:true,countedCash:true,variance:true,closedAt:true}})).map(c=>({facility:c.facility.name,date:c.businessDate.toISOString().slice(0,10),status:c.status,expected:c.expectedCash.toFixed(2),counted:c.countedCash?.toFixed(2)??null,variance:c.variance?.toFixed(2)??null,closed:iso(c.closedAt)}));
    }
    case "notes": return bounded(await db.unitNote.findMany({where:{...direct,...range("createdAt","date")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},unit:{select:{number:true}},author:{select:{name:true}},note:true,pinned:true,createdAt:true}})).map(n=>({facility:n.facility.name,unit:n.unit.number,author:n.author.name,note:n.note,pinned:n.pinned,date:iso(n.createdAt)}));
    case "maintenance": return bounded(await db.maintenanceRequest.findMany({where:{...direct,...range("createdAt","date"),...range("dueAt","due"),...range("completedAt","completed")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},unit:{select:{number:true}},title:true,status:true,priority:true,assignedTo:{select:{name:true}},createdAt:true,dueAt:true,completedAt:true}})).map(m=>({facility:m.facility.name,unit:m.unit?.number??null,title:m.title,status:m.status,priority:m.priority,assignedTo:m.assignedTo?.name??null,date:iso(m.createdAt),due:iso(m.dueAt),completed:iso(m.completedAt)}));
    case "communications": return bounded(await db.communicationLog.findMany({where:{...direct,...range("queuedAt","date"),...range("sentAt","sent"),...range("deliveredAt","delivered")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},customer:{select:customerSelect},channel:true,direction:true,messageType:true,status:true,queuedAt:true,sentAt:true,deliveredAt:true,failureCode:true}})).map(c=>({facility:c.facility?.name??"Organisation",customer:name(c.customer),channel:c.channel,direction:c.direction,type:c.messageType,status:c.status,date:iso(c.queuedAt),sent:iso(c.sentAt),delivered:iso(c.deliveredAt),failure:c.failureCode}));
    case "access": return bounded(await db.accessDecision.findMany({where:{...direct,...range("createdAt","date"),...range("confirmedAt","confirmed")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},occupancy:{select:{unit:{select:{number:true}}}},action:true,source:true,state:true,reason:true,createdAt:true,confirmedAt:true,attempts:true,failureCode:true}})).map(a=>({facility:a.facility.name,unit:a.occupancy.unit.number,action:a.action,source:a.source,state:a.state,reason:a.reason,date:iso(a.createdAt),confirmed:iso(a.confirmedAt),attempts:a.attempts,failure:a.failureCode}));
    case "audit": return bounded(await db.auditEvent.findMany({where:{...direct,...range("occurredAt","date")},take,orderBy:{id:"asc"},select:{facility:{select:facilitySelect},actor:{select:{name:true}},action:true,entityType:true,occurredAt:true}})).map(a=>({facility:a.facility?.name??"Organisation",actor:a.actor?.name??null,action:a.action,entityType:a.entityType,date:iso(a.occurredAt)}));
    case "adjustments": {
      const facilities=await db.facility.findMany({where:facility,select:{id:true,name:true}});const labels=new Map(facilities.map(f=>[f.id,f.name]));
      return bounded(await db.financialAdjustment.findMany({where:{...direct,...range("createdAt","date"),...range("postedAt","posted")},take,orderBy:{id:"asc"},select:{facilityId:true,kind:true,status:true,amount:true,taxAmount:true,reason:true,createdAt:true,postedAt:true,payoutDate:true,account:{select:{accountNumber:true,currency:true,customer:{select:customerSelect}}}}})).map(a=>({facility:labels.get(a.facilityId)??"Unknown",account:a.account.accountNumber,customer:name(a.account.customer),kind:a.kind,status:a.status,amount:a.amount.toFixed(2),tax:a.taxAmount.toFixed(2),currency:a.account.currency,reason:a.reason,date:iso(a.createdAt),posted:iso(a.postedAt),payout:a.payoutDate}));
    }
    case "marketing": return bounded(await db.marketingActivity.findMany({where:{campaign:direct,...range("occurredAt","date")},take,orderBy:{id:"asc"},select:{campaign:{select:{facility:{select:facilitySelect},name:true,source:true,medium:true}},kind:true,title:true,occurredAt:true,spend:true,clicks:true,impressions:true}})).map(a=>({facility:a.campaign.facility.name,campaign:a.campaign.name,source:a.campaign.source,medium:a.campaign.medium,kind:a.kind,title:a.title,date:iso(a.occurredAt),spend:a.spend.toFixed(2),clicks:a.clicks,impressions:a.impressions}));
    default: throw new ReportError("REPORT_DATASET_UNAVAILABLE");
  }
}

export async function visualReportSource(scope:RequestScope, query:VisualReportQuery):Promise<VisualReportRow[]> {
  if(query.historyImportId) {
    const imported=await db.reportHistoryImport.findFirst({where:{id:query.historyImportId,organisationId:scope.organisationId,dataset:query.dataset,...(query.facilityId?{facilityId:query.facilityId}:scope.unrestrictedFacilities?{}:{facilityId:{in:scope.facilityIds}})}});
    if(!imported)throw new ReportError("REPORT_NOT_FOUND");
    await requireFacility(scope,imported.facilityId);
    return z.array(z.record(z.string(),z.union([z.string(),z.number().finite(),z.boolean(),z.null()]))).max(REPORT_SOURCE_LIMIT).parse(JSON.parse(decryptReportArtifact(imported.encryptedRows,`${scope.organisationId}:history:${imported.id}`)));
  }
  if(visualReportDatasets.find(d=>d.key===query.dataset)?.importOnly)throw new ReportError("REPORT_HISTORY_REQUIRED");
  const rows=await rawVisualReportSource(scope,query);
  const org=await db.organisation.findUniqueOrThrow({where:{id:scope.organisationId},select:{currency:true}});
  return rows.map(row=>({...row,currency:row.currency??org.currency}));
}
