import { defaultVisualQuery } from "./visual-report-engine";
import { visualReportSchema, type VisualReportQuery, visualReportDatasets } from "./visual-report-contract";

export type VisualReportTemplate = { key: string; name: string; group: string; dataset?: string; dateField?: string; intervalMode?:VisualReportQuery["intervalMode"]; columns?: string[]; filters?: VisualReportQuery["filters"]; groupBy?: string[]; metrics?: VisualReportQuery["metrics"]; reason?: string; nativeGap?: string; legacyKey?: string };
const equal=(field:string,value:string):VisualReportQuery["filters"][number]=>({field,operator:"eq",value});
const template=(key:string,name:string,group:string,dataset:string,options:Partial<VisualReportTemplate>={}):VisualReportTemplate=>({key,name,group,dataset,...options});
const ledger=(key:string,name:string,type?:string)=>template(key,name,"Finance","ledger",{dateField:"date",...(type?{filters:[equal("type",type)]}:{})});
export const visualReportTemplates:VisualReportTemplate[]=[
  template("directory","Tenant directory","Tenants","tenants",{columns:["facility","account","customer","email","phone","units","status"]}),
  template("lease-roll","Detailed rent roll","Tenants","tenants"),
  template("vacated","Vacated leases","Tenants","tenants",{dateField:"end"}),
  template("walk-through","Walk-through unit list","Tenants","units"),
  template("card-roll","Card payment-method roll","Tenants","tenants",{filters:[equal("paymentMethod","CARD")]}),
  template("debit-roll","Debit-order payment-method roll","Tenants","tenants",{filters:[equal("paymentMethod","DEBIT_ORDER")]}),
  template("eft-roll","EFT payment-method roll","Tenants","tenants",{filters:[equal("paymentMethod","EFT")]}),
  {key:"past-due",name:"Past due balances",group:"Tenants",legacyKey:"receivables-ageing"},
  template("balances","Balances due (all recorded leases)","Tenants","tenants",{filters:[{field:"balance",operator:"gt",value:0}]}),
  template("contact-activity","Communication history","Tenants","communications",{dateField:"date"}),
  template("payment-history","Payment history","Tenants","payments",{dateField:"date"}),
  template("ledger-history","Detailed ledger history","Tenants","ledger",{dateField:"date"}),
  template("rental-history","Recorded rental intervals","Units","occupancies"),
  template("occupied-whole-period","Occupied for entire reporting period","Units","occupancies",{intervalMode:"whole-period"}),
  template("occupied-overlap","Occupied during any part of period","Units","occupancies",{intervalMode:"overlap"}),
  template("price-list","Price list","Units","units",{columns:["facility","unit","floor","type","area","monthlyRate","effectiveStatus"]}),
  template("move-ins","Move-ins","Units","occupancies",{dateField:"start"}),
  template("move-outs","Recorded move-outs","Units","occupancies",{dateField:"end",filters:[equal("status","MOVED_OUT")]}),
  template("scheduled-moves","Scheduled move-outs","Units","occupancies",{dateField:"end",filters:[equal("status","NOTICE_GIVEN")]}),
  template("vacant","Vacant operational units","Units","units",{filters:[equal("effectiveStatus","AVAILABLE")]}),
  template("occupied","Occupied units","Units","units",{filters:[equal("status","OCCUPIED")]}),
  template("unit-status","Unit status","Units","units"),
  template("unit-notes","Unit notes","Units","notes",{dateField:"date"}),
  template("custom-units","Custom units report","Units","units"),
  {key:"duration",name:"Tenant duration & recorded rent changes",group:"Tenants",legacyKey:"tenant-duration"},
  {key:"receivable-ageing",name:"Aged receivables",group:"Finance",legacyKey:"receivables-ageing"},
  template("receivables","Accounts receivable (current balances)","Finance","tenants",{filters:[{field:"balance",operator:"gt",value:0}]}),
  template("receipts","Succeeded payment receipts","Finance","payments",{dateField:"processed",filters:[equal("status","SUCCEEDED")]}),
  template("receipt-details","Receipt details","Finance","payments",{dateField:"processed",filters:[equal("status","SUCCEEDED")]}),
  template("daily-payments","Daily payments","Finance","payments",{dateField:"date"}),
  template("card-payments","Card payments","Finance","payments",{dateField:"date",filters:[equal("method","CARD")]}),
  template("payment-activity","Payment activity","Finance","payments",{dateField:"date"}),
  ledger("credits","Credits issued","CREDIT"),
  ledger("refund-entries","Recorded refund ledger entries","REFUND"),
  ledger("write-offs","Bad debt written off (ledger)","WRITE_OFF"),
  template("refund-requests","Refund requests and reviews","Finance","adjustments",{dateField:"date",filters:[equal("kind","REFUND")]}),
  template("recorded-payouts","Refunds with recorded payout dates","Finance","adjustments",{dateField:"payout",filters:[equal("kind","REFUND"),{field:"payout",operator:"isNotEmpty"}]}),
  template("refund-summary","Refund request summary","Finance","adjustments",{dateField:"date",filters:[equal("kind","REFUND")],groupBy:["status","currency"],metrics:[{field:"*",operation:"count"},{field:"amount",operation:"sum"}]}),
  template("ledger-summary","Ledger totals by type","Finance","ledger",{dateField:"date",groupBy:["type","currency"],metrics:[{field:"*",operation:"count"},{field:"amount",operation:"sum"},{field:"tax",operation:"sum"}]}),
  template("returned-payments","Failed / returned payment records","Finance","payments",{dateField:"date",filters:[equal("status","FAILED")]}),
  template("marketing-summary","Recorded marketing summary","Marketing","marketing",{dateField:"date",groupBy:["source","currency"],metrics:[{field:"spend",operation:"sum"},{field:"clicks",operation:"sum"},{field:"impressions",operation:"sum"}]}),
  template("marketing-history","Marketing activity history","Marketing","marketing",{dateField:"date"}),
  template("advertisement","Advertisement activity tracking","Marketing","marketing",{dateField:"date"}),
  template("lead-funnel","Current lead funnel","Management","leads",{dateField:"date",groupBy:["stage"],metrics:[{field:"*",operation:"count"}]}),
  template("lead-sources","Enquiries by source","Marketing","leads",{dateField:"date",groupBy:["source"],metrics:[{field:"*",operation:"count"}]}),
  template("insurance-roll","Insurance and waiver roll","Insurance","insurance"),
  template("insurance-activity","Recorded insurance decisions","Insurance","insurance",{dateField:"date"}),
  template("merchandise-summary","Merchandise stock summary","Merchandise","products"),
  template("merchandise-activity","Merchandise stock activity","Merchandise","stock",{dateField:"date"}),
  template("merchandise-sales","Merchandise orders and sales status","Merchandise","sales",{dateField:"date"}),
  template("merchandise-total","Merchandise order totals by status","Merchandise","sales",{dateField:"date",groupBy:["status","currency"],metrics:[{field:"*",operation:"count"},{field:"total",operation:"sum"}]}),
  template("daily-cash","Daily cash close controls","Deposits","closes",{dateField:"date"}),
  template("cash-variance","Cash variance by store","Deposits","closes",{dateField:"date",groupBy:["facility","currency"],metrics:[{field:"expected",operation:"sum"},{field:"counted",operation:"sum"},{field:"variance",operation:"sum"}]}),
  {key:"management-current",name:"Current occupancy & contracted rent",group:"Management",legacyKey:"occupancy-revenue"},
  template("inspection-records","Site maintenance records","Management","maintenance",{dateField:"date"}),
  template("manager-activity","Manager activity","Management","audit",{dateField:"date"}),
  template("hourly-records","Staff activity detail","Management","audit",{dateField:"date"}),
  template("exceptions","Unconfirmed access decisions","Management","access",{dateField:"date",filters:[{field:"state",operator:"ne",value:"CONFIRMED"}]}),
  template("gate-decisions","Access-control decision history","Management","access",{dateField:"date"}),
  ...[
    ["internet-access","Internet access roll","Tenants","No tenant internet-access entitlement source is recorded."],
    ["unpaid-charges","Unpaid charges / all unpaid charges","Finance","Requires approved charge-level payment/credit allocations; a current account balance does not identify unpaid charges."],
    ["transfer-pairs","Move-outs & transfers","Units","Requires an explicit transfer event/link and agreed effective-date definition; matching dates alone cannot establish a transfer."],
    ["complimentary","Complimentary units","Units","Requires an approved complimentary/discount classification; zero rent alone is insufficient."],
    ["general-journal","General journal entries","Finance","MRI journal contract, chart-of-accounts mappings and reconciliation are not approved. Ledger transaction detail is available separately."],
    ["income-analysis","Financial summary / income analysis","Finance","Requires approved revenue recognition, allocations, reversals and financial statement definitions."],
    ["prepaid-rent","Prepaid rent / prepaid rent liabilities","Finance","Requires effective-period allocation and approved liability classification. Credit balances are not automatically prepaid rent."],
    ["prepaid-insurance","Prepaid insurance","Finance","Requires insurance period allocation and provider reconciliation."],
    ["security-deposits","Security deposit liabilities","Finance","Requires classified deposit transactions, release/refund allocation and liability reconciliation."],
    ["recurring-charges","Recurring charges","Finance","Requires an agreed recurring charge schedule and its linkage to leases and posted billing."],
    ["bad-debt","Bad debt provision","Finance","Requires an approved finance provision policy; posted write-offs are available separately."],
    ["postal","Postal code statistics","Marketing","Customer addresses are unstructured; verified postcode normalization and permitted geographic aggregation are required."],
    ["map-tenants","MapPoint / geographic tenant map","Marketing","Requires verified address/geocoding data and approved geographic privacy rules."],
    ["marketing-roll","Tenant marketing roll","Marketing","Requires validated purpose/channel-specific communication consent; directory data cannot imply consent."],
    ["competitors","Competitor comparison","Marketing","No maintained competitor dataset is recorded."],
    ["teletracker","TeleTracker activity","Marketing","Requires an integrated call-event and campaign-attribution source."],
    ["insurance-statement","Insurance statement","Insurance","Requires provider premium collections/remittance and reconciliation; enrollment premiums are not settlement."],
    ["bank-deposits","Daily deposit / cash basis deposit details & summary","Deposits","Requires bank/merchant matching and agreed deposit allocation. Daily cash controls are available separately."],
    ["accrual-deposits","Accrual basis deposit details","Deposits","Requires approved accrual allocation and bank settlement reconciliation."],
    ["management-history","Management / occupied history","Management","Historical daily snapshots must be captured and retained; present-day records cannot reconstruct unrecorded past states."],
    ["rate-history","Complete rate management history","Management","Requires a complete rate-change event source, including migration history. Recorded current rent-review information is available separately."],
    ["discount-history","Discounts / discount summary","Management","Requires applied-discount linkage and historical finance amounts; configured plans alone are not applied discounts."],
    ["logons","Log on history","Management","Requires defined successful/failed session events and approved retention; generic audit events are insufficient."],
    ["security-settings","Security settings report","Management","Requires a separately authorized permission-review report with agreed employee scope."],
    ["pc-maintenance","PC maintenance","Management","Desktop-specific SiteLink function; requires a managed endpoint inventory/health source."],
    ["gate-passages","Gate passage history","Management","Provider-confirmed gate passage events are required; access decisions are available separately."],
    ["tenant-notes-history","Complete tenant notes history","Tenants","Requires immutable note revisions; current customer note text is not historical evidence."],
    ["batch-letters","Start-of-day letters","Management","Requires approved letter templates, recipient/consent rules and a reviewed communications workflow."],
  ].map(([key,name,group,reason])=>{const imported=visualReportDatasets.find(d=>d.key===`history-${key}`);return imported?{key,name,group,dataset:imported.key,dateField:"date",...(key==="marketing-roll"?{filters:[{field:"consent",operator:"eq" as const,value:true}]}:{}),nativeGap:reason}:{key,name,group,reason};}),
];
export function queryFromTemplate(template:VisualReportTemplate,from:string,to:string):VisualReportQuery {
  if(!template.dataset)throw new Error("REPORT_TEMPLATE_UNAVAILABLE");
  const base=defaultVisualQuery(template.dataset,from,to);
  return visualReportSchema.parse({...base,name:template.name,columns:template.columns??base.columns,filters:template.filters??[],groupBy:template.groupBy??[],metrics:template.metrics??[],...(template.dateField?{dateField:template.dateField}:{}),...(template.intervalMode?{intervalMode:template.intervalMode,dateField:undefined}:{})});
}
