/**
 * Renders a customer-facing account statement as branded, self-contained
 * HTML — same rendering approach and same rationale as invoice-renderer.ts
 * (no new PDF dependency; see that file's header comment).
 *
 * A statement is a plain historical view of the ledger: every LedgerEntry
 * in the range, in order, with a running balance. Unlike an invoice it is
 * not limited to CHARGE rows — CREDIT, REVERSAL and WRITE_OFF entries
 * (manual adjustments a staff member makes directly in the CRM) render
 * here too, which is exactly why a statement can never be generated by
 * Netcash: those rows never touch a payment rail at all (see
 * claude/invoicing-statements-scope.md §0/§2 in the Stor24 project).
 */
import { BRAND, documentShellHtml, escapeHtml, formatZar } from "@/lib/finance/billing-document-brand";
import type { BillingDocumentCompanyDetails } from "@/lib/finance/billing-document-config";

export type StatementLedgerLine = {
  id: string;
  type: "CHARGE" | "PAYMENT" | "CREDIT" | "REFUND" | "REVERSAL" | "WRITE_OFF";
  description: string;
  effectiveAt: Date;
  amount: number | string;
};

export type StatementRenderInput = {
  statementNumber: string;
  issueDate: Date;
  periodFrom: Date;
  periodTo: Date;
  facilityName: string;
  company: BillingDocumentCompanyDetails;
  customerName: string;
  billingAddressLines?: string[];
  accountNumber: string;
  openingBalance: number | string;
  lines: StatementLedgerLine[];
  closingBalance: number | string;
  payNowUrl?: string;
};

const DEBIT_TYPES = new Set(["CHARGE", "REVERSAL"]);

function formatDate(date: Date) {
  return date.toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" });
}

export function renderStatementHtml(input: StatementRenderInput): string {
  let running = Number(input.openingBalance);
  const rows = input.lines.map((line) => {
    const signedAmount = DEBIT_TYPES.has(line.type) ? Number(line.amount) : -Number(line.amount);
    running += signedAmount;
    return `
      <tr>
        <td style="padding:9px 0;border-bottom:1px solid ${BRAND.line};font-size:13px;color:${BRAND.mutedSoft};white-space:nowrap;">${escapeHtml(formatDate(line.effectiveAt))}</td>
        <td style="padding:9px 0;border-bottom:1px solid ${BRAND.line};font-size:14px;color:${BRAND.ink};">${escapeHtml(line.description)}</td>
        <td style="padding:9px 0;border-bottom:1px solid ${BRAND.line};font-size:14px;color:${BRAND.ink};text-align:right;white-space:nowrap;">${signedAmount >= 0 ? formatZar(signedAmount) : `(${formatZar(Math.abs(signedAmount))})`}</td>
        <td style="padding:9px 0;border-bottom:1px solid ${BRAND.line};font-size:13px;color:${BRAND.muted};text-align:right;white-space:nowrap;">${formatZar(running)}</td>
      </tr>`;
  }).join("");

  const payNowBlock = input.payNowUrl && Number(input.closingBalance) > 0
    ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:22px 0 4px;"><tr><td align="center">
        <a href="${escapeHtml(input.payNowUrl)}" target="_top" style="display:inline-block;background:${BRAND.accent};color:#ffffff;font-weight:800;font-size:15px;padding:14px 28px;border-radius:12px;text-decoration:none;">Pay now</a>
      </td></tr></table>`
    : "";

  const bodyHtml = `
    <div style="margin-bottom:12px;color:${BRAND.accent};font-size:11px;line-height:1.4;font-weight:800;letter-spacing:2px;text-transform:uppercase;">Account statement</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin-bottom:18px;">
      <tr>
        <td style="font-size:13px;color:${BRAND.muted};line-height:1.6;vertical-align:top;">
          ${escapeHtml(input.customerName)}<br>
          ${(input.billingAddressLines ?? []).map((line) => escapeHtml(line)).join("<br>")}
        </td>
        <td style="font-size:13px;color:${BRAND.muted};line-height:1.6;text-align:right;vertical-align:top;">
          Statement #: <strong style="color:${BRAND.ink};">${escapeHtml(input.statementNumber)}</strong><br>
          Period: ${escapeHtml(formatDate(input.periodFrom))} &ndash; ${escapeHtml(formatDate(input.periodTo))}<br>
          Facility: ${escapeHtml(input.facilityName)}<br>
          Account: ${escapeHtml(input.accountNumber)}
        </td>
      </tr>
    </table>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;">
      <thead><tr>
        <td style="font-size:11px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:${BRAND.mutedSoft};padding-bottom:6px;border-bottom:2px solid ${BRAND.ink};">Date</td>
        <td style="font-size:11px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:${BRAND.mutedSoft};padding-bottom:6px;border-bottom:2px solid ${BRAND.ink};">Description</td>
        <td style="font-size:11px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:${BRAND.mutedSoft};padding-bottom:6px;border-bottom:2px solid ${BRAND.ink};text-align:right;">Amount</td>
        <td style="font-size:11px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:${BRAND.mutedSoft};padding-bottom:6px;border-bottom:2px solid ${BRAND.ink};text-align:right;">Balance</td>
      </tr></thead>
      <tbody>
        <tr><td colspan="3" style="padding:8px 0;font-size:13px;color:${BRAND.muted};">Opening balance</td><td style="padding:8px 0;font-size:13px;color:${BRAND.ink};text-align:right;">${formatZar(input.openingBalance)}</td></tr>
        ${rows}
      </tbody>
    </table>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin-top:10px;">
      <tr><td style="text-align:right;padding:8px 0 0;font-size:16px;font-weight:900;color:${BRAND.ink};border-top:1px solid ${BRAND.line};">Closing balance</td><td style="text-align:right;padding:8px 0 0;font-size:16px;font-weight:900;color:${BRAND.ink};border-top:1px solid ${BRAND.line};width:140px;">${formatZar(input.closingBalance)}</td></tr>
    </table>
    ${payNowBlock}
    ${input.company.registrationNumber || input.company.vatNumber ? `<p style="margin:16px 0 0;font-size:11px;color:${BRAND.mutedSoft};">${input.company.companyName ? escapeHtml(input.company.companyName) + " " : ""}${input.company.registrationNumber ? `Reg no: ${escapeHtml(input.company.registrationNumber)} ` : ""}${input.company.vatNumber ? `VAT no: ${escapeHtml(input.company.vatNumber)}` : ""}</p>` : ""}
  `;

  return documentShellHtml({
    title: `Statement ${input.statementNumber}`,
    preheader: `Your Stor24 statement for ${formatDate(input.periodFrom)} to ${formatDate(input.periodTo)} — closing balance ${formatZar(input.closingBalance)}.`,
    bodyHtml,
  });
}
