import test from 'node:test';import assert from 'node:assert/strict';
import {businessDeadline,defaultLeadSla,leadSlaSchema,slaFromStoreHours} from '../src/lib/lead-sla-policy';
import {initialRentPreview} from '../src/lib/proration-preview';
import {marketProfileSchema} from '../src/lib/lead-market-profile';
import {leadReport} from '../src/lib/lead-reporting';
test('eight business hours pause overnight, weekends and configured holidays',()=>{assert.equal(businessDeadline(new Date('2026-10-02T14:30:00Z'),defaultLeadSla).toISOString(),'2026-10-05T13:30:00.000Z');assert.equal(businessDeadline(new Date('2026-10-02T14:30:00Z'),{...defaultLeadSla,holidays:['2026-10-05']}).toISOString(),'2026-10-06T13:30:00.000Z');assert.equal(businessDeadline(new Date('2026-10-05T04:00:00Z'),defaultLeadSla).toISOString(),'2026-10-05T14:00:00.000Z');assert.ok(!leadSlaSchema.safeParse({...defaultLeadSla,enabled:true}).success);assert.ok(!leadSlaSchema.safeParse({...defaultLeadSla,windows:[{day:1,start:100,end:90}]}).success);});
test('after cutoff includes exact remaining days plus following month, with December rollover and leap months',()=>{const p={mode:'AFTER_CUTOFF_NEXT_MONTH' as const,cutoffDay:15};assert.equal(initialRentPreview(2800,'2026-02-15',p)?.total,1400);assert.equal(initialRentPreview(2800,'2026-02-16',p)?.total,4100);assert.equal(initialRentPreview(2900,'2024-02-29',p)?.total,3000);assert.equal(initialRentPreview(3100,'2026-12-31',p)?.nextMonth,'2027-01');assert.equal(initialRentPreview(2800,'2026-02-16',{mode:'FULL_MONTH',cutoffDay:15})?.total,2800);assert.equal(initialRentPreview(2800,'2026-02-30',p),null);});
test('market profile is voluntary, bounded and does not fabricate missing demographics',()=>{assert.equal(marketProfileSchema.parse({}).gender,'UNKNOWN');assert.ok(!marketProfileSchema.safeParse({gender:'GUESS_FROM_NAME'}).success);const base={stage:'NEW',source:'Walk-in',createdAt:'2026-10-05T09:00:00Z',nextActionAt:null,attribution:null,reservations:[]};const result=leadReport([base,{...base,marketProfile:{gender:'PREFER_NOT_TO_SAY',storageUse:'BUSINESS',discoverySource:'Google ad'}}]);assert.equal(result.genders.find(r=>r.label==='Unknown')?.count,1);assert.equal(result.storageUses.find(r=>r.label==='BUSINESS')?.count,1);});

test('SLA imports saved office hours without substituting access hours or guessing missing stores',()=>{const policy=slaFromStoreHours({officeWeekdayClosed:false,officeWeekdayStart:'07:00',officeWeekdayEnd:'19:00',officeSaturdayClosed:false,officeSaturdayStart:'07:00',officeSaturdayEnd:'19:00',officeSundayClosed:true,officePublicHolidayClosed:true});assert.ok(policy);assert.equal(policy.enabled,false);assert.equal(policy.windows.find(w=>w.day===6)?.end,1140);assert.ok(!policy.windows.some(w=>w.day===0));assert.ok(policy.holidays.includes('2026-11-04'));assert.equal(slaFromStoreHours({accessWeekdayStart:'07:00',accessWeekdayEnd:'19:00'}),null);assert.ok(!leadSlaSchema.safeParse({...defaultLeadSla,holidays:['2026-02-30']}).success);});
