import {protectDlpResponse} from "@/lib/dlp-transfer-service";
import { requireOwner, authErrorResponse } from '@/lib/auth-guards';
import { sameOrigin } from '@/lib/request-security';
import { approveRentReview, previewRentReview, rentReviewReport } from '@/lib/rent-review-service';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'no-store, max-age=0, private'};
function failure(e:unknown){const code=e instanceof Error?e.message:'';if(code.startsWith('RENT_'))return Response.json({error:{code,message:code.replaceAll('_',' ').toLowerCase()}},{status:409,headers});return authErrorResponse(e);}
export async function GET(request:Request){try{const auth=await requireOwner();const facilityId=new URL(request.url).searchParams.get('facilityId');if(!facilityId)return Response.json({error:{message:'Choose a facility.'}},{status:422,headers});return protectDlpResponse(Response.json({data:await rentReviewReport(auth.user.organisationId,facilityId)},{headers}),{organisationId:auth.user.organisationId,actorId:auth.userId,facilityId,resourceId:"rent-review"},"confidential");}catch(e){return failure(e);}}
export async function POST(request:Request){try{if(!sameOrigin(request))return Response.json({error:{message:'Request rejected.'}},{status:403,headers});const auth=await requireOwner();const body=await request.json();if(body.action==='preview'){const preview=await previewRentReview(auth.user.organisationId,body.input);return protectDlpResponse(Response.json({data:preview},{headers}),{organisationId:auth.user.organisationId,actorId:auth.userId,facilityId:preview.facility.id,resourceId:'rent-review-preview'},'confidential');}if(body.action==='approve'&&body.noticeConfirmed===true&&typeof body.fingerprint==='string'&&typeof body.approvalReference==='string')return Response.json({data:await approveRentReview(auth.user.organisationId,auth.userId,body.input,body.fingerprint,body.approvalReference)},{headers});return Response.json({error:{message:'Choose a supported action and confirm the notice approval.'}},{status:422,headers});}catch(e){return failure(e);}}
