ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'TEST_PENDING';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'TEST_SUCCEEDED';
ALTER TABLE "MerchandiseOrder" ADD COLUMN "isTest" BOOLEAN NOT NULL DEFAULT false;
