import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db} from '../../src/lib/db';
import {moveIn,PENDING_MOVE_IN_CHARGE_DESCRIPTION} from '../../src/lib/leasing-service';
import {runLegacyMonthlyBilling} from '../../src/lib/legacy-monthly-billing';
import {previewMonthlyBilling,saveMonthlyBillingPlan} from '../../src/lib/monthly-billing-service';
test('isolated first rent records prepaid periods and prevents following month rebilling without sending messages',async()=>{
assert.equal(process.env.MERCHANDISE_DB_TEST,'isolated-ci');assert.equal(new URL(process.env.DATABASE_URL!).hostname,'localhost');const key=randomUUID();const org=await db.organisation.create({data:{name:'Initial rent CI',slug:key}});
try{const f=await db.facility.create({data:{organisationId:org.id,code:key,name:'CI facility'}});const user=await db.user.create({data:{organisationId:org.id,name:'CI owner',email:key+'@example.invalid'}});const customer=await db.customer.create({data:{organisationId:org.id,firstName:'CI'}});const type=await db.unitType.create({data:{facilityId:f.id,name:'CI',features:[]}});const unit=await db.unit.create({data:{facilityId:f.id,unitTypeId:type.id,number:key,monthlyRate:2800,status:'AVAILABLE'}});const scope={userId:user.id,organisationId:org.id,facilityIds:[f.id],unrestrictedFacilities:false};
const result=await moveIn(scope,{facilityId:f.id,customerId:customer.id,unitId:unit.id,startDate:new Date('2026-02-16T00:00:00+02:00'),initialCharge:0,paymentMethod:'EFT',accessState:'PENDING',simulation:true,initialRentPolicy:{mode:'AFTER_CUTOFF_NEXT_MONTH',cutoffDay:15,approvalReference:'CI pricing approval'}});
assert.equal(result.tenancy.status,'DRAFT');const rows=await db.ledgerEntry.findMany({where:{accountId:result.tenancy.accountId},orderBy:{externalRef:'asc'}});assert.deepEqual(rows.map(r=>[r.externalRef,Number(r.amount)]),[['RENT-2026-02',1300],['RENT-2026-03',2800]]);assert.ok(rows.every(r=>r.description===PENDING_MOVE_IN_CHARGE_DESCRIPTION&&r.effectiveAt.getTime()===new Date('2026-02-16T00:00:00+02:00').getTime()));assert.equal(Number((await db.account.findUniqueOrThrow({where:{id:result.tenancy.accountId}})).balance),4100);assert.equal(await db.communicationLog.count({where:{organisationId:org.id}}),0);assert.equal(await db.payment.count({where:{accountId:result.tenancy.accountId}}),0);assert.equal(await db.auditEvent.count({where:{organisationId:org.id,action:'tenancy.initial_rent.calculated'}}),1);
await db.tenancy.update({where:{id:result.tenancy.id},data:{status:'ACTIVE'}});await db.occupancy.updateMany({where:{tenancyId:result.tenancy.id},data:{status:'ACTIVE'}});await runLegacyMonthlyBilling('2026-03');assert.equal(await db.ledgerEntry.count({where:{accountId:result.tenancy.accountId}}),2);await saveMonthlyBillingPlan(scope,result.tenancy.accountId,{firstPeriod:'2026-03',proration:'ACTUAL_DAYS',taxPercent:0,rentTaxable:false,insuranceEnabled:false,insuranceTaxable:false,charges:[],discount:null,approvalReference:'CI plan'});await assert.rejects(previewMonthlyBilling(scope,result.tenancy.accountId,'2026-03'),/ALREADY_POSTED/);
}finally{await db.$disconnect();}});
