ALTER TABLE "UnitType" ADD COLUMN "useTypes" TEXT[] NOT NULL DEFAULT ARRAY['STORAGE']::TEXT[];
ALTER TABLE "Unit" ADD COLUMN "useTypesOverride" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Lead" ADD COLUMN "productLine" TEXT NOT NULL DEFAULT 'STORAGE', ADD COLUMN "businessDetails" JSONB;
ALTER TABLE "Reservation" ADD COLUMN "productLine" TEXT NOT NULL DEFAULT 'STORAGE', ADD COLUMN "businessDetails" JSONB;
ALTER TABLE "Tenancy" ADD COLUMN "productLine" TEXT NOT NULL DEFAULT 'STORAGE', ADD COLUMN "businessDetails" JSONB;
