"use client";
import { useCallback, useEffect, useState } from "react";
import { adjustmentKinds, adjustmentLabels, type AdjustmentInput } from "@/lib/adjustment-policy";
type Review = { fingerprint: string; accountNumber: string; facilityName: string; balanceBefore: string; balanceAfter: string; amount: string; taxAmount: string; source: { description: string; amount: string } | null; input: AdjustmentInput };
type Item = { id: string; accountId: string; kind: string; status: string; amount: string; taxAmount: string; reason: string; evidenceReference: string; requestedById: string; reviewedById: string | null; reviewReference: string | null; documentId: string | null; createdAt: string; payoutReference: string | null; payoutDate: string | null; snapshot: Review };
type Workspace = { accounts: { id: string; accountNumber: string; balance: string; tenancy: { facility: { name: string } } }[]; requests: Item[]; userId: string };
type Detail = { balance: string; entries: { id: string; type: string; description: string; amount: string; taxAmount: string; effectiveAt: string }[] };
const money = (v: string) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(Number(v));
const status: Record<string, string> = { PENDING_APPROVAL: "Awaiting independent approval", APPROVED: "Refund approved · payout not recorded", POSTED: "Posted to account", REJECTED: "Rejected", CANCELLED: "Cancelled" };
async function api(body?: unknown, accountId?: string) {
  const response = await fetch(`/api/v1/adjustments${accountId ? `?accountId=${encodeURIComponent(accountId)}` : ""}`, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" });
  const value = await response.json(); if (!response.ok) throw new Error(value.error || "Unable to load adjustments."); return value;
}
const empty: AdjustmentInput = { accountId: "", kind: "CREDIT", amount: "", taxAmount: "0", sourceEntryId: null, reason: "", evidenceReference: "" };
export function AdjustmentsWorkspace() {
  const [data, setData] = useState<Workspace | null>(null), [input, setInput] = useState(empty), [detail, setDetail] = useState<Detail | null>(null);
  const [preview, setPreview] = useState<Review | null>(null), [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [requestKey, setRequestKey] = useState("");
  const load = useCallback(async () => setData(await api()), []);
  useEffect(() => { let active = true; void api().then(v => { if (active) setData(v); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; if (input.accountId) void api(undefined, input.accountId).then(v => { if (active) setDetail(v); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, [input.accountId]);
  function change(patch: Partial<AdjustmentInput>) { setInput(v => ({ ...v, ...patch })); setPreview(null); setConfirm(false); setRequestKey(""); setMessage(""); }
  async function act(body: unknown, success: string) {
    setBusy(true); setMessage("");
    try { const result = await api(body); await load(); if (input.accountId) setDetail(await api(undefined, input.accountId)); setMessage(success); return result; }
    catch (error) { setMessage(error instanceof Error ? error.message : "Unable to complete action."); return null; }
    finally { setBusy(false); }
  }
  const ready = input.accountId && Number(input.amount) > 0 && input.reason.trim().length >= 10 && input.evidenceReference.trim().length >= 5 && (input.kind === "CHARGE" || input.sourceEntryId);
  return <div className="monthly-billing adjustments-workspace">
    <section className="monthly-card adjustment-boundary"><strong>Every correction keeps its original history</strong><p>Request a correction, review its effect, and ask a different authorised colleague to approve it. Approval posts charges, credits, write-offs and receipt reversals. Refund approval reserves the request; record the refund only after an authorised external payout has completed.</p><p>No bank transfer, customer message or accounting export is sent here. Stock returns and deposit balances held outside this account need their own reconciliation.</p></section>
    {message && <p className="monthly-card" role="status">{message}</p>}
    {!data ? <p>Loading permitted accounts and requests…</p> : <>
      <section className="monthly-card adjustment-create"><h2>New adjustment request</h2><div className="monthly-grid">
        <label>Account<select aria-label="Account" value={input.accountId} disabled={busy} onChange={e => { setDetail(null); change({ accountId: e.target.value, sourceEntryId: null }); }}><option value="">Select account</option>{data.accounts.map(a => <option key={a.id} value={a.id}>{a.accountNumber} · {a.tenancy.facility.name}</option>)}</select></label>
        <label>Correction type<select value={input.kind} disabled={busy} onChange={e => change({ kind: e.target.value as AdjustmentInput["kind"], sourceEntryId: null, taxAmount: "0" })}>{adjustmentKinds.map(k => <option key={k} value={k}>{adjustmentLabels[k]}</option>)}</select></label>
        {input.kind !== "CHARGE" && <label>Original entry<select value={input.sourceEntryId ?? ""} disabled={busy || !detail} onChange={e => change({ sourceEntryId: e.target.value || null })}><option value="">Select original {input.kind === "REFUND" || input.kind === "REVERSAL" ? "receipt" : "charge"}</option>{detail?.entries.filter(e => e.type === (input.kind === "REFUND" || input.kind === "REVERSAL" ? "PAYMENT" : "CHARGE")).map(e => <option key={e.id} value={e.id}>{e.description} · {money(e.amount)}</option>)}</select></label>}
        <label>Amount (including tax)<input type="number" min="0.01" step="0.01" value={input.amount} disabled={busy} onChange={e => change({ amount: e.target.value })}/></label>
        {input.kind === "CHARGE" && <label>Included tax amount<input type="number" min="0" step="0.01" value={input.taxAmount} disabled={busy} onChange={e => change({ taxAmount: e.target.value })}/></label>}
        <label>Supporting evidence reference<input value={input.evidenceReference} maxLength={200} disabled={busy} placeholder="Approved instruction or source document" onChange={e => change({ evidenceReference: e.target.value })}/></label>
      </div><label>Reason<textarea value={input.reason} maxLength={500} disabled={busy} placeholder="Explain the correction for the reviewer" onChange={e => change({ reason: e.target.value })}/></label>
      <p>{detail ? `Current balance: ${money(detail.balance)}. ` : ""}Credits inherit proportional tax from the original charge. Write-offs do not claim tax relief. Receipt reversals must be for the full original receipt. Refunds require a cleared overpayment and a verified original receipt.</p>
      <button className="button button-primary" disabled={busy || !ready} onClick={async () => { setPreview(null); setConfirm(false); const value = await act({ action: "preview", input }, "Preview ready. Check the original entry and balance change."); if (value) { setPreview(value); setRequestKey(crypto.randomUUID()); } }}>Preview adjustment</button></section>
      {preview && <section className="monthly-card adjustment-preview"><h2>Review before requesting</h2><p>{preview.accountNumber} · {preview.facilityName}</p><p>{adjustmentLabels[input.kind]}: <strong>{money(preview.amount)}</strong> · Included tax: {money(preview.taxAmount)}</p>{preview.source && <p>Original: {preview.source.description} · {money(preview.source.amount)}</p>}<p>Balance before: <strong>{money(preview.balanceBefore)}</strong> → Balance after posting: <strong>{money(preview.balanceAfter)}</strong></p><label className="monthly-check"><input type="checkbox" checked={confirm} disabled={busy} onChange={e => setConfirm(e.target.checked)}/>I checked the source, reason and balance change.</label><button className="button button-primary" disabled={busy || !confirm} onClick={async () => { const value = await act({ action: "request", input, fingerprint: preview.fingerprint, requestKey, confirm: true }, "Request saved. A different authorised colleague must approve it."); if (value) { setPreview(null); setConfirm(false); } }}>Request independent approval</button></section>}
      <section className="monthly-card adjustment-history"><h2>Requests and permanent records</h2><p>Showing the latest 100 requests across your permitted stores. One open request is allowed per account.</p>{!data.requests.length && <p>No adjustment requests yet.</p>}{data.requests.map(item => <AdjustmentCard key={item.id} item={item} userId={data.userId} busy={busy} act={act}/>)}</section>
      <p><a href="/operations/accounts">View account ledger and statements</a> · <a href="/operations/merchandise">Stock returns and inventory corrections</a></p>
    </>}
  </div>;
}
function AdjustmentCard({ item, userId, busy, act }: { item: Item; userId: string; busy: boolean; act: (body: unknown, success: string) => Promise<unknown> }) {
  const [reference, setReference] = useState(""), [date, setDate] = useState(""), [confirmed, setConfirmed] = useState(false), [unpaid, setUnpaid] = useState(false);
  async function perform(body: unknown, success: string) { const result = await act(body, success); if (result) { setConfirmed(false); setUnpaid(false); setReference(""); setDate(""); } }
  const own = item.requestedById === userId, open = ["PENDING_APPROVAL", "APPROVED"].includes(item.status);
  return <article className="adjustment-record"><h3>{item.snapshot.accountNumber} · {adjustmentLabels[item.kind]} · {money(item.amount)}</h3><strong>{status[item.status] ?? item.status}</strong><p>{item.reason}</p><p>Evidence: {item.evidenceReference}</p><details><summary>Review saved evidence and balance change</summary><p>Request: {item.id}</p><p>{item.snapshot.facilityName} · {item.snapshot.source?.description ?? "Additional charge"}</p><p>{money(item.snapshot.balanceBefore)} → {money(item.snapshot.balanceAfter)} · Included tax {money(item.taxAmount)}</p><p>Approval: {item.reviewReference ?? "Awaiting review"}</p>{item.payoutReference && <p>External payout: {item.payoutReference} · {item.payoutDate}</p>}</details>
    {open && <><label>Review or payout reference<input aria-label={`Reference for ${item.id}`} value={reference} disabled={busy} maxLength={200} onChange={e => setReference(e.target.value)}/></label>{item.status === "APPROVED" && <label>Completed payout date<input type="date" value={date} disabled={busy} onChange={e => setDate(e.target.value)}/></label>}<label className="monthly-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e => { setConfirmed(e.target.checked); setUnpaid(false); }}/>{item.status === "APPROVED" ? "I verified the authorised external payout is complete." : "I reviewed the saved source, reason and balance change."}</label>{item.status === "APPROVED" && <label className="monthly-check"><input type="checkbox" checked={unpaid} disabled={busy} onChange={e => { setUnpaid(e.target.checked); setConfirmed(false); }}/>No external payout has occurred; cancel this unpaid request.</label>}<div className="adjustment-actions">
      {item.status === "PENDING_APPROVAL" && <><button className="button button-primary" disabled={busy || own || !confirmed || reference.trim().length < 5} onClick={() => perform({ action: "approve", id: item.id, reference, confirm: true }, item.kind === "REFUND" ? "Refund approved. No payout has been recorded." : "Approved and posted once to the account.")}>{item.kind === "REFUND" ? "Approve refund request" : "Approve and post correction"}</button><button className="button button-secondary" disabled={busy || own || !confirmed || reference.trim().length < 5} onClick={() => perform({ action: "reject", id: item.id, reference, confirm: true }, "Request rejected. No balance change.")}>Reject request</button></>}
      {item.status === "APPROVED" && <button className="button button-primary" disabled={busy || own || !confirmed || !date || reference.trim().length < 5} onClick={() => perform({ action: "record-payout", id: item.id, reference, date, paidConfirmed: true }, "Externally completed refund recorded on the account.")}>Record completed external refund</button>}
      {(own || item.reviewedById === userId) && <button className="button button-secondary" disabled={busy || !(item.status === "APPROVED" ? unpaid : confirmed) || reference.trim().length < 5} onClick={() => perform({ action: "cancel", id: item.id, reference, confirm: true, unpaidConfirmed: unpaid }, "Unposted request cancelled. No balance change.")}>Cancel unposted request</button>}
    </div>{own && <p>You requested this correction. A different authorised colleague must approve and record it.</p>}</>}
    {item.documentId && <p><a href={`/api/v1/adjustments?document=${encodeURIComponent(item.id)}`} target="_blank" rel="noreferrer">View saved adjustment record</a></p>}
  </article>;
}
