"use client";
import { useEffect, useRef, useState } from "react";
import { buckets, type CollectionAction } from "@/lib/collections-policy";
import { filterCollections, type CollectionFilters } from "@/lib/collections-view";
import type { CollectionsWorkspaceData } from "@/lib/collections-service";
type Row = CollectionsWorkspaceData["rows"][number];
const money = (cents: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(cents / 100);
async function api(asOf: string, body?: unknown): Promise<CollectionsWorkspaceData> {
  const response = await fetch(`/api/v1/collections${asOf ? `?asOf=${encodeURIComponent(asOf)}` : ""}`, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" });
  const value = await response.json(); if (!response.ok) throw new Error(value.error || "Unable to load collections."); return value;
}
export function CollectionsWorkspace() {
  const requestKeys = useRef(new Map<string, string>());
  const [data, setData] = useState<CollectionsWorkspaceData | null>(null), [asOf, setAsOf] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [selected, setSelected] = useState("");
  const [filters, setFilters] = useState<CollectionFilters>({ search: "", facility: "", mode: "all", owner: "" });
  useEffect(() => { let active = true; void api(asOf).then(v => { if (active) setData(v); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, [asOf]);
  const rows = data ? filterCollections(data, filters) : [], current = data?.rows.find(r => r.id === selected);
  const historical = data && data.asOf !== data.today;
  async function act(input: CollectionAction) {
    setBusy(true); setMessage("");
    const signature = JSON.stringify({ ...input, requestKey: "" });
    input.requestKey = requestKeys.current.get(signature) ?? input.requestKey;
    requestKeys.current.set(signature, input.requestKey);
    try { await api("", input); const fresh = await api(asOf); setData(fresh); setMessage("Saved. Account balances and customer communications are unchanged."); return true; }
    catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save."); return false; }
    finally { setBusy(false); }
  }
  const query = new URLSearchParams({ ...filters, asOf: data?.asOf ?? "", export: "csv" });
  return <div className="monthly-billing collections-workspace">
    <section className="monthly-card"><strong>Ageing uses approved due dates</strong><p>Charges are aged in calendar days after their due date. Receipts reduce the oldest due charges after source-linked credits. Missing terms and unreconciled history go to finance review and are excluded from aged totals. No messages, charges, debit runs or access changes are triggered here.</p></section>
    {message && <p role="status" className="monthly-card">{message}</p>}
    <section className="monthly-card collections-filters"><div className="monthly-grid">
      <label>As of (South Africa)<input type="date" value={asOf || data?.asOf || ""} max={data?.today} disabled={busy} onChange={e => { setData(null); setSelected(""); setAsOf(e.target.value); }}/></label>
      <label>Search accounts<input value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })}/></label>
      <label>Store<select value={filters.facility} onChange={e => setFilters({ ...filters, facility: e.target.value })}><option value="">All permitted stores</option>{[...new Map(data?.rows.map(r => [r.facilityId, r.facility])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
      <label>Show<select aria-label="Show" value={filters.mode} onChange={e => setFilters({ ...filters, mode: e.target.value })}><option value="all">All accounts</option><option value="overdue">Overdue balances</option><option value="follow-up">Follow-ups due now</option><option value="review">Finance review</option><option value="disputes">Dispute holds</option><option value="promises">Open promises</option>{buckets.map((b, i) => <option key={b} value={`bucket-${i}`}>{b}</option>)}</select></label>
      <label>Owner<select value={filters.owner} onChange={e => setFilters({ ...filters, owner: e.target.value })}><option value="">All owners</option><option value="unassigned">Unassigned</option>{[...new Map(data?.rows.flatMap(r => r.owners.map(o => [o.id, o.name] as const))).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    </div><div className="adjustment-actions"><button className="button button-primary" disabled={!data || busy || !!historical || !rows.some(r => !r.ageing.issue && !r.hold && r.ageing.overdue > 0 && (!r.nextFollowUp || r.nextFollowUp <= data.today))} onClick={() => { const queue = rows.filter(r => !r.ageing.issue && !r.hold && r.ageing.overdue > 0 && (!r.nextFollowUp || r.nextFollowUp <= data!.today)); const index = queue.findIndex(r => r.id === selected); setSelected(queue[(index + 1) % queue.length].id); }}>Open next follow-up</button>{data && <a className="button button-secondary" href={`/api/v1/collections?${query}`}>Export filtered CSV</a>}<button className="button button-secondary" disabled={busy} onClick={async () => { setBusy(true); try { setData(await api(asOf)); setMessage("Report refreshed."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to refresh."); } finally { setBusy(false); } }}>Refresh</button></div></section>
    {!data ? <p>Loading permitted accounts…</p> : <><section className="summary-strip collections-summary">{buckets.map((b, i) => <div className="summary-cell" key={b}><span>{b}</span><strong>{money(rows.reduce((s, r) => s + (r.ageing.issue ? 0 : r.ageing.buckets[i]), 0))}</strong></div>)}<div className="summary-cell"><span>Finance review</span><strong>{rows.filter(r => r.ageing.issue).length} accounts</strong></div></section>
    <section className="monthly-card collections-queue"><h2>Account review queue</h2><p>{rows.length} of {data.rows.length} permitted tenant accounts · snapshot {data.asOf}. Totals follow the filters. Holds remain in aged totals. Case ownership, holds, promises and follow-up dates show their current state.</p>{historical && <p>Historical ageing uses currently approved terms and currently recorded ledger history. Backdated entries may change a later rerun. Editing is available only on today’s report.</p>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Account / tenant</th><th>Store</th><th>Overdue</th><th>Oldest debt</th><th>Follow-up / hold</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td className="primary-cell"><button className="button button-secondary" aria-label={`Review ${r.accountNumber}`} onClick={() => setSelected(r.id)}>{r.accountNumber}</button><br/>{r.name}</td><td>{r.facility}</td><td>{r.ageing.issue ? "Needs review" : money(r.ageing.overdue)}</td><td>{r.ageing.issue ? "—" : `${r.ageing.oldestDays} days`}</td><td>{r.ageing.issue || r.hold || r.nextFollowUp || "Not scheduled"}<br/>{r.owners.find(o => o.id === r.ownerId)?.name ?? (r.ownerId ? "Owner needs review" : "Unassigned")}</td></tr>)}{!rows.length && <tr><td colSpan={5}>No accounts match these filters.</td></tr>}</tbody></table></div></section>
    {current && <CaseEditor key={`${current.id}:${current.revision}:${data.asOf}`} row={current} today={data.today} disabled={busy || !!historical} act={act}/>}</>}
  </div>;
}
function CaseEditor({ row, today, disabled, act }: { row: Row; today: string; disabled: boolean; act: (v: CollectionAction) => Promise<boolean> }) {
  const [note, setNote] = useState(""), [ownerId, setOwnerId] = useState(row.ownerId ?? ""), [followUp, setFollowUp] = useState(row.nextFollowUp ?? ""), [outcome, setOutcome] = useState<"PLAN" | "REACHED" | "NO_ANSWER">("PLAN");
  const [amount, setAmount] = useState(""), [dueDate, setDueDate] = useState(""), [confirm, setConfirm] = useState(false), [days, setDays] = useState(String(row.terms?.dueDays ?? "")), [reference, setReference] = useState(row.terms?.approvalReference ?? ""), [termConfirm, setTermConfirm] = useState(false);
  const [overrides, setOverrides] = useState(row.terms?.overrides ?? []);
  const ready = !disabled && note.trim().length >= 5;
  const base = () => ({ accountId: row.id, revision: row.revision, requestKey: crypto.randomUUID(), note });
  return <section className="monthly-card collection-case"><h2>{row.accountNumber} · {row.name}</h2><p>{row.facility} · Recorded balance now: {money(Number(row.currentBalance) * 100)} · <a href="/operations/accounts">Account ledger and statements</a></p>
    {(row.ageing.issue || row.hold) && <p className="collection-warning">{row.ageing.issue} {row.hold}{row.disputeReason ? `: ${row.disputeReason}` : ""}</p>}
    <details><summary>Review charge ageing and approved terms</summary><p>Each charge uses its effective date plus the approved calendar days, unless an evidenced invoice date overrides it. These terms support this report; they do not amend an agreement or invoice.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Charge</th><th>Due</th><th>Remaining</th></tr></thead><tbody>{row.ageing.charges.map(c => <tr key={c.id}><td>{c.description}</td><td>{c.dueDate}</td><td>{money(c.remaining)}</td></tr>)}</tbody></table></div>
    <div className="monthly-grid"><label>Approved days after charge<input type="number" min="0" max="120" value={days} disabled={disabled} onChange={e => { setDays(e.target.value); setTermConfirm(false); }}/></label><label>Terms approval reference<input value={reference} maxLength={200} disabled={disabled} onChange={e => { setReference(e.target.value); setTermConfirm(false); }}/></label></div>
    <details><summary>Invoice due-date overrides ({overrides.length})</summary>{row.sources.map(s => <label key={s.id}>{s.description} · {s.date}<input type="date" aria-label={`Due override ${s.id}`} min={s.date} disabled={disabled} value={overrides.find(o => o.entryId === s.id)?.dueDate ?? ""} onChange={e => { setOverrides([...overrides.filter(o => o.entryId !== s.id), ...(e.target.value ? [{ entryId: s.id, dueDate: e.target.value }] : [])]); setTermConfirm(false); }}/></label>)}</details>
    <label className="monthly-check"><input type="checkbox" checked={termConfirm} disabled={disabled} onChange={e => setTermConfirm(e.target.checked)}/>Finance approved these due dates and oldest-due-first allocation for ageing.</label><button className="button button-secondary" disabled={!ready || !termConfirm || days === "" || Number(days) < 0 || Number(days) > 120 || reference.trim().length < 5} onClick={() => act({ ...base(), action: "terms", terms: { dueDays: Number(days), allocation: "OLDEST_DUE_FIRST", approvalReference: reference, overrides }, confirm: true })}>Save approved ageing terms</button></details>
    <label>Case note / evidence reference<textarea value={note} maxLength={1000} disabled={disabled} onChange={e => setNote(e.target.value)} placeholder="Record the actual conversation, instruction or supporting evidence. Do not enter bank details."/></label>
    <div className="monthly-grid"><label>Follow-up owner<select value={ownerId} disabled={disabled} onChange={e => setOwnerId(e.target.value)}><option value="">Unassigned</option>{row.owners.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Next follow-up<input type="date" min={today} value={followUp} disabled={disabled} onChange={e => setFollowUp(e.target.value)}/></label><label>Contact outcome<select value={outcome} disabled={disabled} onChange={e => setOutcome(e.target.value as typeof outcome)}><option value="PLAN">Plan / internal review</option><option value="REACHED">Spoke to customer</option><option value="NO_ANSWER">No answer</option></select></label></div>
    <div className="adjustment-actions"><button className="button button-primary" disabled={!ready} onClick={() => act({ ...base(), action: "follow-up", ownerId: ownerId || null, nextFollowUp: followUp || null, outcome })}>Save follow-up</button><button className="button button-secondary" disabled={!ready} onClick={() => act({ ...base(), action: "dispute", disputed: !row.disputed })}>{row.disputed ? "Resolve dispute hold" : "Place dispute hold"}</button></div><p>Record contact only after it happened. A dispute hold removes this account from the next-follow-up queue; it does not pause an existing debit instruction or change physical access.</p>
    <h3>Promises to pay</h3>{row.promises.map(p => <article key={p.id} className="adjustment-record"><strong>{money(Number(p.amount) * 100)} by {p.dueDate} · {p.status}</strong><p>{p.progress?.label ?? "Receipt history needs review"}{p.progress ? ` · New verified receipts ${money(p.progress.received)}` : ""}</p>{p.status === "OPEN" && <div className="adjustment-actions"><button className="button button-secondary" disabled={!ready || !p.progress?.covered} onClick={() => act({ ...base(), action: "close-promise", promiseId: p.id, status: "KEPT" })}>Confirm promise kept</button><button className="button button-secondary" disabled={!ready} onClick={() => act({ ...base(), action: "close-promise", promiseId: p.id, status: "CANCELLED" })}>Cancel promise with note</button></div>}</article>)}
    {!row.promises.some(p => p.status === "OPEN") && <><div className="monthly-grid"><label>Promised amount<input type="number" min="0.01" step="0.01" value={amount} disabled={disabled} onChange={e => { setAmount(e.target.value); setConfirm(false); }}/></label><label>Promise due date<input type="date" min={today} value={dueDate} disabled={disabled} onChange={e => { setDueDate(e.target.value); setConfirm(false); }}/></label></div><label className="monthly-check"><input type="checkbox" checked={confirm} disabled={disabled} onChange={e => setConfirm(e.target.checked)}/>The customer agreed this amount and date.</label><button className="button button-secondary" disabled={!ready || !confirm || !dueDate || Number(amount) <= 0 || !amount || Number(amount) * 100 > row.ageing.overdue || !!row.ageing.issue || !!row.hold} onClick={() => act({ ...base(), action: "promise", amount, dueDate, confirm: true })}>Record agreed promise</button></>}
    <p>Only new verified receipts recorded after the promise count. Credits and write-offs do not count as payment. An open promise holds follow-up until its due date has passed. Late receipts stay labelled late; resolve that promise with a recorded note. If a previously kept promise loses receipt coverage, review the reversed or refunded receipt before further contact.</p>
    <h3>Recent case history</h3><p>Latest 30 actions and 20 promises shown; all earlier history remains retained.</p>{row.activities.length ? row.activities.map(a => <article key={a.id} className="adjustment-record"><strong>{a.action} · {new Date(a.createdAt).toLocaleString("en-ZA", { timeZone: "Africa/Johannesburg" })}</strong><p>{a.note}</p><small>Recorded by {row.owners.find(o => o.id === a.actorId)?.name ?? a.actorId}</small></article>) : <p>No case activity recorded.</p>}
  </section>;
}
