"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, CalendarClock, ChevronRight, Plus, Search, Users, X } from "lucide-react";
import { LEAD_SOURCES, leadSourceLabel, websiteSourceLabel } from "@/lib/lead-sources";
import { LeadCustomerPicker } from "@/components/lead-customer-picker";
import { ReservationUnitPicker, type ReservationMap } from "@/components/reservation-unit-picker";
import { leadReport, leadStages, stageLabels } from "@/lib/lead-reporting";
import type { LeadAttribution } from "@/lib/lead-attribution";
import { formatSouthAfricaDate, formatSouthAfricaDateTime } from "@/lib/south-africa-time";

type Lead = { id: string; stage: string; source: string; createdAt: string; updatedAt: string; notes: string | null; expectedMoveIn: string | null; nextActionAt: string | null; assignedToId: string | null;
  customer: { id: string; firstName: string; lastName: string; companyName: string | null; email: string | null; phone: string | null } | null;
  facility: { id: string; name: string }; desiredUnitType: { name: string } | null; assignedTo: { id: string; name: string } | null;
  attribution: LeadAttribution | null; reservations: { id: string; status: string; journey: string; quotedRate: number; convertedTenancyId: string | null; unit: { number: string } }[] };
type Workspace = { leads: Lead[]; count: number; facilities: { id: string; name: string; canCreate: boolean; canManage: boolean; canReserve: boolean }[]; staff: { id: string; name: string; facilityIds: (string | null)[] }[] };
const name = (lead: Lead) => lead.customer?.companyName || `${lead.customer?.firstName ?? ""} ${lead.customer?.lastName ?? ""}`.trim() || "Unlinked enquiry";
const money = (n: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR", maximumFractionDigits: 0 }).format(n);
const dateInput = (value: string | null) => value ? new Date(new Date(value).getTime()+2*3600000).toISOString().slice(0,16) : "";
async function request(url: string, body: unknown, method = "POST") { const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Could not save. Refresh and try again."); return result; }

export function LeadsWorkspace({ initialCustomerId = "", initialLeadId = "" }: { initialCustomerId?: string; initialLeadId?: string }) {
  const [submissionId,setSubmissionId]=useState("");
  const [newFacility,setNewFacility]=useState(""); const [newSource,setNewSource]=useState("Walk-in"); const [maps,setMaps]=useState<ReservationMap[]>([]);
  const [now,setNow]=useState<Date | null>(null);
  const [data, setData] = useState<Workspace | null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [query,setQuery]=useState(""); const [facility,setFacility]=useState(""); const [stage,setStage]=useState(""); const [period,setPeriod]=useState(initialCustomerId ? "all" : "90");
  const [selected,setSelected]=useState<Lead | null>(null); const [adding,setAdding]=useState(false); const [reserving,setReserving]=useState(false); const [busy,setBusy]=useState(false);
  const [history,setHistory]=useState<{id:string;at:string;actor:string;action:string;beforeStage:string|null;afterStage:string|null}[]|null>(null);
  const [historyError,setHistoryError]=useState(false);
  useEffect(()=>{let active=true;if(selected)void fetch(`/api/v1/leads/${selected.id}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(result=>{if(active)setHistory(result.data);}).catch(()=>{if(active)setHistoryError(true);});return()=>{active=false;};},[selected]);
  const [units,setUnits]=useState<{id:string;number:string;monthlyRate:string;facilityId:string}[]>([]);
  const load=useCallback(async()=>{const response=await fetch("/api/v1/leads/workspace",{cache:"no-store"});if(!response.ok)throw new Error("Could not load leads. Refresh or check your access.");const result=await response.json();setData(result.data);setNow(new Date());},[]);
  useEffect(()=>{let active=true;void fetch("/api/v1/leads/workspace",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Could not load leads. Refresh or check your access.");return r.json();}).then(result=>{if(active){setData(result.data);setNow(new Date());if(initialLeadId){const lead=result.data.leads.find((l: Lead)=>l.id===initialLeadId);if(lead)setSelected(lead);else setError("This enquiry is unavailable or outside your access.");}}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[initialLeadId]);
  const filtered=useMemo(()=> (data?.leads ?? []).filter(l=>(!initialCustomerId||l.customer?.id===initialCustomerId)&&(!facility||l.facility.id===facility)&&(!stage||l.stage===stage)&&(period==="all"||new Date(l.createdAt).getTime()>=(now?.getTime()??0)-Number(period)*86400000)&&(!query||[name(l),l.customer?.email,l.customer?.phone,l.source,l.attribution?.source,l.attribution?.landingPage,l.attribution?.conversionPage,l.assignedTo?.name].join(" ").toLowerCase().includes(query.toLowerCase()))),[data,facility,stage,period,query,now,initialCustomerId]);
  const report=useMemo(()=>leadReport(filtered,now??new Date(0)),[filtered,now]);
  const maxStage=Math.max(1,...report.stages.map(s=>s.count));const maxWeek=Math.max(1,...report.weeks.map(w=>w.count));
  async function act(operation:()=>Promise<unknown>, message:string) {setBusy(true);setError("");setNotice("");try{await operation();setSelected(null);setAdding(false);setReserving(false);setNotice(message);try{await load();}catch{setError("Saved, but the refreshed worklist could not be loaded. Refresh before making another change.");}}catch(e){setError(e instanceof Error?e.message:"Save failed. Refresh before trying again.");}finally{setBusy(false);}}
  async function openReserve() {if(!selected)return;setBusy(true);setError("");try{const r=await fetch("/api/v1/reservations",{cache:"no-store"});if(!r.ok)throw Error("Could not load available units.");const result=await r.json();setUnits(result.data.facilities.flatMap((f:{id:string;units:{id:string;number:string;monthlyRate:string}[]})=>f.id===selected.facility.id?f.units.map(u=>({...u,facilityId:f.id})):[]));setMaps(result.data.facilities.find((f:{id:string})=>f.id===selected.facility.id)?.maps ?? []);setReserving(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const canManage=selected && data?.facilities.find(f=>f.id===selected.facility.id)?.canManage;
  return <div className="page-stack leads-workspace">
    <header className="leads-heading page-header"><div><p className="eyebrow">SALES INTELLIGENCE</p><h1>Leads &amp; sales performance</h1><p>Know where enquiries come from. Keep the next step moving.</p></div><button className="button button-primary" disabled={!data?.facilities.some(f=>f.canCreate)} onClick={()=>{setAdding(true);setSubmissionId(crypto.randomUUID());setError("");}}><Plus size={17}/> Add enquiry</button></header>
    {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="leads-notice" role="status">{notice}</p>}
    {!data ? <section className="panel"><p>{error?"Leads are unavailable. No figures are shown.":"Loading your sales workspace…"}</p></section> : <>
    {initialCustomerId&&<p className="leads-caption">Showing enquiries linked to this customer. <a href="/leads">Show all customers</a></p>}
    <section className="leads-filters" aria-label="Filter leads"><label className="leads-search"><Search size={16}/><input aria-label="Search leads" placeholder="Search customer, contact or source" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Store<select aria-label="Filter store" value={facility} onChange={e=>setFacility(e.target.value)}><option value="">All accessible stores</option>{data.facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Created<select aria-label="Filter period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option><option value="all">All available history</option></select></label><label>Stage<select aria-label="Filter stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="">All stages</option>{leadStages.map(s=><option key={s} value={s}>{stageLabels[s]}</option>)}</select></label></section>
    {data.count>data.leads.length&&<p className="leads-caption">Showing the latest {data.leads.length} of {data.count} enquiries. Charts cover this loaded cohort.</p>}
    <section className="leads-kpis" aria-label="Sales summary">{[["Enquiries",report.total,"Saved enquiries in the selected cohort",Users],["Open opportunities",report.open,"Awaiting a sales outcome",BarChart3],["Moved in",report.won,`${report.conversionRate}% of selected enquiries`,ArrowUpRight],["Overdue follow-ups",report.overdue,"Open enquiries past their follow-up time",CalendarClock]].map(([label,value,caption,Icon])=>{const Graphic=Icon as typeof Users;return <article key={String(label)}><div><span>{String(label)}</span><Graphic size={18}/></div><strong>{String(value)}</strong><p>{String(caption)}</p></article>;})}</section>
    <div className="leads-charts"><section className="panel leads-chart"><div className="leads-section-title"><div><p className="eyebrow">CURRENT POSITION</p><h2>Sales pipeline</h2></div><span>{money(report.pipelineValue)}<small>monthly rent in active holds</small></span></div><p className="leads-caption">Current stages, not a historical funnel. Select a bar to filter.</p><div className="leads-stage-bars">{report.stages.map(s=><button key={s.stage} onClick={()=>setStage(stage===s.stage?"":s.stage)} aria-pressed={stage===s.stage}><span>{s.label}</span><i><b style={{width:`${s.count/maxStage*100}%`}}/></i><strong>{s.count}</strong></button>)}</div></section>
    <section className="panel leads-chart"><p className="eyebrow">ENQUIRY VOLUME</p><h2>Last eight weeks</h2><p className="leads-caption">Saved enquiries by creation week, within your filters.</p><div className="leads-week-bars" role="img" aria-label={report.weeks.map(w=>`${w.label}: ${w.count}`).join(", ")}>{report.weeks.map(w=><div key={w.label}><strong>{w.count}</strong><i style={{height:`${Math.max(2,w.count/maxWeek*130)}px`}}/><span>{w.label.slice(5)}</span></div>)}</div></section></div>
    <div className="leads-charts"><section className="panel leads-chart"><p className="eyebrow">ACQUISITION</p><h2>Source performance</h2><p className="leads-caption">Website sources need consented attribution; other labels are recorded enquiry sources.</p>{report.sources.length?<div className="leads-source-list">{report.sources.map(s=><div key={s.label}><span>{s.label}</span><strong>{s.total}<small>enquiries</small></strong><strong>{s.won}<small>moved in</small></strong><strong>{Math.round(s.won/s.total*100)}%<small>conversion</small></strong></div>)}</div>:<p className="leads-empty">No enquiries in this selection.</p>}</section>
    <section className="panel leads-chart"><p className="eyebrow">WEBSITE JOURNEYS</p><h2>Landing page → enquiry page</h2><p className="leads-caption">{report.attributed} of {report.total} enquiries have consented journey data. Submission is an enquiry or booking, not a completed lease.</p>{report.paths.length?<div className="leads-paths">{report.paths.slice(0,5).map(p=><div key={p.label}><span>{p.label}</span><strong>{p.count}</strong></div>)}</div>:<p className="leads-empty">No journey data yet. Older enquiries and visitors who decline analytics remain unattributed.</p>}</section></div>
    <section className="panel leads-register"><div className="leads-section-title"><div><p className="eyebrow">YOUR SALES WORKLIST</p><h2>Enquiries <span className="leads-count">{filtered.length}</span></h2></div><button className="text-button" onClick={()=>{setQuery("");setFacility("");setStage("");setPeriod("90");}}>Reset filters</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer &amp; contact</th><th>Requirement</th><th>Source</th><th>Stage</th><th>Owner / next action</th><th>Created</th><th/></tr></thead><tbody>{filtered.slice(0,100).map(l=><tr key={l.id}><td><button className="leads-name" onClick={()=>{setSelected(l);setHistory(null);setHistoryError(false);setReserving(false);setError("");}}>{name(l)}</button><span className="secondary-cell">{l.customer?.email || "No email"}</span><span className="secondary-cell">{l.customer?.phone || "No phone"}</span></td><td>{l.facility.name}<span className="secondary-cell">{l.desiredUnitType?.name || "Requirements in notes"}</span><span className="secondary-cell">{l.expectedMoveIn?`Move-in ${formatSouthAfricaDate(l.expectedMoveIn)}`:"Move-in not set"}</span></td><td>{l.attribution?websiteSourceLabel(l.attribution):leadSourceLabel(l.source)}<span className="secondary-cell">{l.attribution?.landingPage||"Landing page unknown"}</span></td><td><span className={`leads-stage leads-stage-${l.stage.toLowerCase()}`}>{stageLabels[l.stage]}</span></td><td>{l.assignedTo?.name||"Unassigned"}<span className="secondary-cell">{l.nextActionAt?formatSouthAfricaDateTime(l.nextActionAt):"No follow-up scheduled"}</span></td><td>{formatSouthAfricaDate(l.createdAt)}</td><td><button className="leads-open" aria-label={`Open ${name(l)}`} onClick={()=>{setSelected(l);setHistory(null);setHistoryError(false);setReserving(false);setError("");}}><ChevronRight size={18}/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="empty-cell">No enquiries match these filters.</td></tr>}</tbody></table></div>{filtered.length>100&&<p className="leads-caption">First 100 matching enquiries shown. Narrow your filters to find a customer; charts include all {filtered.length} matches.</p>}</section>
    </>}
    {selected&&<div className="modal-backdrop"><section className="modal-card leads-detail" role="dialog" aria-modal="true" aria-labelledby="lead-detail-title"><button className="modal-close" disabled={busy} onClick={()=>setSelected(null)} aria-label="Close enquiry"><X size={18}/></button><p className="eyebrow">ENQUIRY DETAILS</p><h2 id="lead-detail-title">{name(selected)}</h2><p className="modal-copy">{selected.facility.name} · {formatSouthAfricaDate(selected.createdAt)}</p><div className="leads-contact">{selected.customer?.email&&<a href={`mailto:${selected.customer.email}`}>{selected.customer.email}</a>}{selected.customer?.phone&&<a href={`tel:${selected.customer.phone}`}>{selected.customer.phone}</a>}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {selected.attribution?<div className="leads-journey"><strong>{selected.attribution.source} / {selected.attribution.medium}</strong><p>Landing: {selected.attribution.landingPage}</p><p>Submitted on: {selected.attribution.conversionPage}</p><p>{selected.attribution.pages.join(" → ")}</p><small>Consented session; up to 12 public pages. No history before consent.</small></div>:<p className="leads-caption">Website journey unknown for this enquiry.</p>}
    {selected.customer&&<a className="leads-booking" href={`/tenants?customer=${encodeURIComponent(selected.customer.id)}`}>Open customer &amp; tenancy record<ArrowUpRight size={16}/></a>}
    {selected.reservations.map(r=><a className="leads-booking" key={r.id} href={r.status==="CONVERTED"?`/operations/move-in?reservation=${encodeURIComponent(r.id)}`:"/reservations"}>Unit {r.unit.number} · {money(r.quotedRate)} / month · {r.status}<ArrowUpRight size={16}/></a>)}
    {reserving?<form className="leads-edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request("/api/v1/reservations",{facilityId:selected.facility.id,customerId:selected.customer?.id,leadId:selected.id,unitId:f.get("unitId"),quotedRate:Number(f.get("quotedRate")),intendedMoveIn:f.get("intendedMoveIn")||undefined}),"Unit reserved and lead advanced to Reserved.");}}><h3>Reserve a unit for this enquiry</h3><ReservationUnitPicker units={units} maps={maps}/><label>Intended move-in<input name="intendedMoveIn" type="date"/></label>{!units.length&&<p>No available units in this store.</p>}<button className="button button-primary" disabled={busy||!units.length}>Confirm reservation</button><button type="button" className="text-button" onClick={()=>setReserving(false)}>Back to enquiry</button></form>:<form key={selected.id+selected.updatedAt} className="leads-edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request(`/api/v1/leads/${selected.id}`,{updatedAt:selected.updatedAt,stage:f.get("stage"),notes:f.get("notes"),assignedToId:f.get("assignedToId")||null,nextActionAt:f.get("nextActionAt")?new Date(`${f.get("nextActionAt")}:00+02:00`).toISOString():null},"PATCH"),"Enquiry updated. Stage, owner and follow-up saved.");}}><label>Sales stage<select aria-label="Sales stage" name="stage" defaultValue={selected.stage} disabled={!canManage}>{leadStages.map(s=><option key={s} value={s} disabled={["RESERVED","WON"].includes(s)&&s!==selected.stage}>{stageLabels[s]}</option>)}</select></label><p className="leads-caption">Reserved follows a real unit hold. Moved in follows completed handover. Active bookings control their own stage.</p><label>Assigned owner<select aria-label="Assigned owner" name="assignedToId" defaultValue={selected.assignedToId||""} disabled={!canManage}><option value="">Unassigned</option>{data?.staff.filter(s=>s.facilityIds.includes(null)||s.facilityIds.includes(selected.facility.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Next follow-up (South Africa time)<input name="nextActionAt" type="datetime-local" defaultValue={dateInput(selected.nextActionAt)} disabled={!canManage}/></label><label>Requirements &amp; sales notes<textarea name="notes" maxLength={2000} rows={5} defaultValue={selected.notes||""} disabled={!canManage}/></label><div className="leads-detail-actions">{canManage&&<button className="button button-primary" disabled={busy}>{busy?"Saving…":"Save enquiry"}</button>}{selected.customer&&data?.facilities.find(f=>f.id===selected.facility.id)?.canReserve&&!selected.reservations.some(r=>["ACTIVE","CONVERTED"].includes(r.status))&&<button type="button" className="button button-secondary" disabled={busy} onClick={()=>void openReserve()}>Reserve a unit</button>}</div></form>}
    <div className="leads-history"><h3>Activity history</h3><p className="leads-caption">Latest 50 recorded changes. Earlier stages cannot be reconstructed where they were not logged.</p>{historyError?<p role="status">Activity history could not be loaded.</p>:history===null?<p>Loading history…</p>:history.length?history.map(h=><div key={h.id}><strong>{h.afterStage&&h.beforeStage!==h.afterStage?`${h.beforeStage?stageLabels[h.beforeStage]+" → ":""}${stageLabels[h.afterStage]}`:h.action.endsWith("created")?"Enquiry recorded":"Enquiry details updated"}</strong><span>{h.actor} · {formatSouthAfricaDateTime(h.at)}</span></div>):<p className="leads-caption">No recorded changes yet.</p>}</div>
    </section></div>}
    {adding&&data&&<div className="modal-backdrop"><section className="modal-card leads-detail lead-create-dialog" role="dialog" aria-modal="true" aria-labelledby="new-lead-title"><button className="modal-close" disabled={busy} onClick={()=>setAdding(false)} aria-label="Close new enquiry"><X size={18}/></button><p className="eyebrow">NEW OPPORTUNITY</p><h2 id="new-lead-title">Add an enquiry</h2><p className="modal-copy">Choose a customer or create one here, then capture their storage enquiry.</p>{error&&<p className="form-error" role="alert">{error}</p>}<form className="leads-edit-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.has("customerId")&&!f.get("customerId")){setError("Choose an existing customer or select Create new customer.");return;}void act(()=>request("/api/v1/leads",{...Object.fromEntries(f.entries()),submissionId}),"Enquiry saved and linked to the customer.");}}><label>Store<select aria-label="Store" name="facilityId" required value={newFacility} onChange={e=>setNewFacility(e.target.value)}><option value="">Select a store</option>{data.facilities.filter(f=>f.canCreate).map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><LeadCustomerPicker key={newFacility} facilityId={newFacility}/><div className="leads-form-row"><label>Enquiry source<select aria-label="Enquiry source" name="source" required value={newSource} onChange={e=>setNewSource(e.target.value)}>{LEAD_SOURCES.map(source=><option key={source}>{source}</option>)}</select></label><label>Expected move-in<input name="expectedMoveIn" type="date"/></label></div>{newSource==="Other"&&<label>How did the customer find us?<input name="sourceDetail" required maxLength={200} placeholder="Describe the source / reason"/></label>}<p className="leads-caption">Website enquiries identify advertising and digital channels automatically from UTM tags. Choose the enquiry source here for staff-captured enquiries.</p><label>Storage requirements<textarea name="notes" rows={3} maxLength={1800} placeholder="What are they storing, space needed, and next step?"/></label><button className="button button-primary" disabled={busy}>{busy?"Saving…":"Save enquiry"}</button></form></section></div>}

  </div>;
}
