"use client";
import {csvCell} from "@/lib/marketing-contract";
import {useEffect,useState} from 'react';
import type {AdvertisingFeed} from '@/lib/marketing-ads';
export function MarketingAdvertising({from,to}:{from:string;to:string}){
 const [feeds,setFeeds]=useState<AdvertisingFeed[]>([]),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch(`/api/v1/marketing/advertising?from=${from}&to=${to}`,{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error(r.status===403?'Advertising reports require all-store reporting access.':'Advertising could not load. Choose a range of up to 90 days and retry.');setFeeds((await r.json()).data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort();},[from,to]);
 return <section className="marketing-card"><h2>Google and Meta advertising</h2><p><a href="/settings/advertising">Manage reporting connection</a></p><p>Provider campaign delivery is separate from recorded CRM marketing activity. These reports refresh from the providers and do not change advertising budgets.</p>{error?<p role="alert">{error}</p>:!feeds.length?<p role="status">Loading advertising…</p>:feeds.map(feed=><div key={feed.provider}><button className="button button-secondary" disabled={!feed.rows.length} onClick={()=>{const csv=[["Provider","Campaign ID","Campaign","Date","Currency","Spend","Impressions","Clicks","Provider conversions"],...feed.rows.map(r=>[r.provider,r.campaignId,r.name,r.date,r.currency,r.spend,r.impressions,r.clicks,r.conversions??""])].map(row=>row.map(csvCell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`stor24-${feed.provider.toLowerCase().replaceAll(" ","-")}-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url);}}>Export {feed.provider}</button><h3>{feed.provider} · {feed.status==='connected'?'Connected':feed.status==='unconfigured'?'Connection needed':'Unavailable'}</h3><p>{feed.message}</p>{feed.retrievedAt?<small>Retrieved {new Date(feed.retrievedAt).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'})}</small>:null}{feed.status==='connected'&&!feed.rows.length?<p>No campaign delivery recorded for this period.</p>:null}{feed.rows.length>200?<p>Showing the first 200 rows. Export includes the complete retrieved report.</p>:null}{feed.rows.length?<div style={{overflowX:'auto'}}><table className="marketing-table"><thead><tr>{['Date','Campaign','Currency','Spend','Impressions','Clicks','Provider conversions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{feed.rows.slice(0,200).map(r=><tr key={r.campaignId+r.date}><td>{r.date}</td><td>{r.name}</td><td>{r.currency}</td><td>{r.spend.toFixed(2)}</td><td>{r.impressions.toLocaleString()}</td><td>{r.clicks.toLocaleString()}</td><td>{r.conversions??'—'}</td></tr>)}</tbody></table></div>:null}</div>)}</section>;
}
