"use client";
import { useEffect, useState } from "react";
import { ArrowDownRight, Compass, MousePointer2, Target } from "lucide-react";
import type { ABCFilters, ABCFunnel, ABCReport, MarketingABC } from "@/lib/marketing-abc";
const n = (value: number | undefined) => value === undefined ? "—" : value.toLocaleString("en-ZA", { maximumFractionDigits: 0 });
const percent = (value: number | undefined) => value === undefined ? "—" : `${(value * 100).toFixed(1)}%`;
const time = (value: number | undefined) => value === undefined ? "—" : `${Math.round(value)}s`;
const eventLabels: Record<string, string> = { page_view: "Public page views", public_link_click: "Public navigation clicks", public_button_click: "Public button clicks", contact_click: "Phone / email / WhatsApp clicks", booking_cta_click: "Booking link clicks", booking_started: "Unit finder opened", price_viewed: "Units & prices viewed", select_unit: "Unit selections", booking_details_started: "Customer details opened", reservation_requested: "Saved reservations", booking_error: "Reservation errors", enquiry_form_started: "Enquiry form started", enquiry_submit: "Enquiry submit attempts", enquiry_error: "Enquiry errors", enquiry_delivery_pending: "Quote acknowledged; CRM delivery unconfirmed", generate_lead: "Saved enquiries", scroll_depth: "Scroll milestones", engaged_30_seconds: "30 seconds active on page", feedback_price: "Better price", feedback_availability: "Different availability", feedback_timing: "More time to decide", feedback_help: "Help choosing a unit", feedback_research: "Just researching" };
function ReportNotes({ report }: { report: ABCReport }) { return <>{report.status === "unavailable" && <p className="abc-gap" role="status">This report is unavailable. Check the reporting connection or refresh.</p>}{report.status === "connected" && !report.rows.length && <p className="abc-gap">No measured activity in this period and filter.</p>}{report.limited && <p className="abc-gap">Top 100 rows only; totals are retrieved separately.</p>}{report.caveats.map(note => <p className="abc-note" key={note}>{note}</p>)}</>; }
export function MarketingFunnel({ title, funnel }: { title: string; funnel: ABCFunnel }) {
  const first = funnel.steps[0]?.users ?? 0;
  const largest = funnel.steps.slice(0, -1).reduce<ABCFunnel["steps"][number] | null>((max, s) => !max || s.abandoned > max.abandoned ? s : max, null);
  return <article className="abc-funnel"><header><div><p className="eyebrow">ORDERED USER JOURNEY</p><h3>{title}</h3></div><Target size={20} /></header>
    {funnel.status === "unavailable" ? <p className="abc-gap">Funnel report unavailable. Event totals are not substituted for an ordered journey.</p> : <>
      {!first && <p className="abc-gap">No measured starts. These new stages collect forward from the tracking release; historical activity cannot be reconstructed.</p>}
      <ol>{funnel.steps.map((s, i) => <li key={s.name}><div className="abc-step-heading"><span><b>{i + 1}</b>{s.name}</span><strong>{n(s.users)} <small>users</small></strong></div><div className="abc-bar"><span style={{ width: `${first ? s.users / first * 100 : 0}%` }} /></div>{i < funnel.steps.length - 1 && <p><ArrowDownRight size={14} />{n(s.abandoned)} did not reach the next stage · {s.users ? percent(s.abandonmentRate) : "No denominator"}</p>}</li>)}</ol>
      {largest && largest.abandoned > 0 && <div className="abc-insight"><strong>Largest measured drop-off: {largest.name}</strong><p>{n(largest.abandoned)} users stopped progressing here. Review the page and error / feedback signals; the exit alone does not establish a reason.</p></div>}
    </>}
    <p className="abc-note">Closed funnel: users must start at step 1 and complete each next stage within 30 minutes. Other actions may occur between stages. This is a Google user journey, not a count of paid customers or a session-only funnel.</p>{funnel.caveats.map(note => <p className="abc-note" key={note}>{note}</p>)}
  </article>;
}
export function MarketingABCPanel({ from, to }: { from: string; to: string }) {
  const [data, setData] = useState<MarketingABC | null>(null), [error, setError] = useState("");
  const [filters, setFilters] = useState<ABCFilters>({}), [options, setOptions] = useState<ABCReport["rows"]>([]);
  useEffect(() => {
    const controller = new AbortController();
    const query = new URLSearchParams({ from, to, ...filters });
    fetch(`/api/v1/marketing/abc?${query}`, { signal: controller.signal, cache: "no-store" }).then(async res => {
      if (!res.ok) throw Error(res.status === 403 ? "ABC website reporting requires all-store reporting access." : "ABC reports could not load. Choose up to 90 days and refresh.");
      const result: MarketingABC = (await res.json()).data; setData(result);
      if (!Object.values(filters).some(Boolean) && result.acquisition.status === "connected") setOptions(result.acquisition.rows);
    }).catch(e => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort();
  }, [from, to, filters]);
  const applyFilters = (next: ABCFilters) => { setData(null); setError(""); setFilters(next); };
  const totals = data?.totals.status === "connected" ? data.totals.rows[0]?.metrics ?? [0, 0, 0, 0, 0, 0, 0] : [];
  const previous = data?.previous.status === "connected" ? data.previous.rows[0]?.metrics ?? [0,0,0,0,0,0,0] : [];
  const events = data?.events.status === "connected" ? data.events.rows : [];
  const feedback = events.filter(row => row.dimensions[0].startsWith("feedback_"));
  const selected = Object.values(filters).some(Boolean);
  return <section className="marketing-card marketing-abc" aria-labelledby="abc-title">
    <header className="abc-header"><div><p className="eyebrow">MARKETING INTELLIGENCE</p><h2 id="abc-title">Acquisition → Behaviour → Conversion</h2><p>Follow the journey from discovery to action. Find the leaks, then test what improves them.</p></div><span className="marketing-provider-status" data-status={data?.status}>{error ? "Unavailable" : data?.status === "connected" ? "Google Analytics connected" : data?.status === "unconfigured" ? "Connection needed" : data?.status === "unavailable" ? "Unavailable" : "Loading ABC reports…"}</span></header>
    <div className="abc-scope"><span>Public STOR24 website · selected date period · consented traffic only</span><span>Store filters apply to CRM results below. ABC filters apply to every website panel and funnel here.</span></div>
    <div className="abc-filters">{([ ["channel", "Channel", 0], ["source", "Source / medium", 1], ["campaign", "Campaign", 2] ] as const).map(([key, label, index]) => <label key={key}>{label}<select aria-label={label} value={filters[key] ?? ""} onChange={e => applyFilters({ ...filters, [key]: e.target.value })}><option value="">All {label.toLowerCase()}s</option>{Array.from(new Set([...options.map(row => row.dimensions[index]), ...(filters[key] ? [filters[key]!] : [])])).sort().map(value => <option key={value}>{value}</option>)}</select></label>)}<label>Device<select aria-label="Device" value={filters.device ?? ""} onChange={e => applyFilters({ ...filters, device: e.target.value })}><option value="">All devices</option>{["desktop", "mobile", "tablet", "smart tv"].map(value => <option key={value}>{value}</option>)}</select></label><button className="button button-secondary" onClick={() => applyFilters({})} disabled={!selected}>Clear ABC filters</button></div>
    {error && <p role="alert" className="abc-gap">{error}</p>}
    {data?.status === "unconfigured" && <p className="abc-gap">Configure an organisation-bound, read-only Google Analytics connection.</p>}
    <div className="abc-kpis">{[["Sessions", n(totals[0]),n(previous[0])], ["Visitors", n(totals[1]),n(previous[1])], ["Page views", n(totals[2]),n(previous[2])], ["Engagement rate", percent(totals[4]),percent(previous[4])], ["Average session", time(totals[5]),time(previous[5])], ["Active time", time(totals[6]),time(previous[6])]].map(([label, value, prior]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>Previous: {prior}</small></div>)}</div>
    {data && <>
      {data.comparisonPeriod && <p className="abc-note">Compared with equal-length prior period {data.comparisonPeriod.from}–{data.comparisonPeriod.to}, using the same ABC filters.</p>}
      <ReportNotes report={data.totals}/>
      <div className="abc-trend"><h4>Traffic & engagement over time</h4><ReportNotes report={data.daily}/>{data.daily.rows.length>0 && <><svg viewBox="0 0 800 140" role="img" aria-label="Daily sessions and engaged sessions; values available in the table"><polyline points={data.daily.rows.map((r,i)=>`${i*800/Math.max(1,data.daily.rows.length-1)},${130-r.metrics[0]/Math.max(1,...data.daily.rows.map(row=>row.metrics[0]))*115}`).join(" ")} fill="none" stroke="#123541" strokeWidth="3"/><polyline points={data.daily.rows.map((r,i)=>`${i*800/Math.max(1,data.daily.rows.length-1)},${130-r.metrics[1]/Math.max(1,...data.daily.rows.map(row=>row.metrics[0]))*115}`).join(" ")} fill="none" stroke="#168972" strokeWidth="3"/></svg><p className="abc-note">Navy: sessions · Green: engaged sessions</p><details><summary>Daily values</summary><div className="marketing-table-scroll"><table className="marketing-table"><thead><tr><th>Date</th><th>Sessions</th><th>Engaged sessions</th></tr></thead><tbody>{data.daily.rows.map(r=><tr key={r.dimensions[0]}><td>{r.dimensions[0]}</td><td>{n(r.metrics[0])}</td><td>{n(r.metrics[1])}</td></tr>)}</tbody></table></div></details></>}</div>
      <article className="abc-section"><header><span className="abc-letter">A</span><div><h3><Compass size={18} /> Acquisition</h3><p>Which channels, sources and campaigns bring engaged traffic?</p></div></header>{data.acquisition.rows.some(r=>/netcash|paypal|stripe/i.test(r.dimensions[1])) && <p className="abc-gap">Payment-provider referrals appear in acquisition. These may be returning customers, rather than new marketing traffic; review unwanted-referral settings before attributing campaign impact.</p>}<ReportNotes report={data.acquisition}/><div className="marketing-table-scroll"><table className="marketing-table"><thead><tr>{["Channel", "Source / medium", "Campaign", "Sessions", "Engaged", "Engagement", "GA key events"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{data.acquisition.rows.map((row, i) => <tr key={i}>{row.dimensions.map((v, j) => <td key={j}>{v}</td>)}<td>{n(row.metrics[0])}</td><td>{n(row.metrics[1])}</td><td>{percent(row.metrics[2])}</td><td>{n(row.metrics[3])}</td></tr>)}</tbody></table></div><p className="abc-note">Session attribution from Google. Key events depend on the property configuration; they are not reconciled CRM enquiries, revenue or paid move-ins. Campaign identifiers from registered links can be matched in Tracked links.</p></article>
      <article className="abc-section"><header><span className="abc-letter">B</span><div><h3><MousePointer2 size={18}/> Behaviour</h3><p>What did visitors view and do? Where did they spend active time?</p></div></header><div className="abc-two-columns"><div><h4>Content engagement</h4><ReportNotes report={data.pages}/><div className="marketing-table-scroll"><table className="marketing-table"><thead><tr><th>Public page</th><th>Views</th><th>Users</th><th>Active time</th></tr></thead><tbody>{data.pages.rows.filter(r => /^\/(?:[a-z0-9-]+\/)*[a-z0-9-]*$/.test(r.dimensions[0]) && !/^\/(?:pay|account|admin|api|access|my-stor24)(?:\/|$)|^\/book\//.test(r.dimensions[0])).map((r, i) => <tr key={i}><td>{r.dimensions[0]}</td><td>{n(r.metrics[0])}</td><td>{n(r.metrics[1])}</td><td>{time(r.metrics[2])}</td></tr>)}</tbody></table></div><p className="abc-note">Active time is total foreground engagement, not elapsed wall time. Users can appear on multiple pages.</p></div><div><h4>Actions & friction</h4><ReportNotes report={data.events}/><div className="abc-actions">{events.filter(r => eventLabels[r.dimensions[0]] || r.dimensions[0].startsWith("storage_")).map(r => <div key={r.dimensions[0]}><span>{eventLabels[r.dimensions[0]] ?? r.dimensions[0].replaceAll("_", " ")}</span><strong>{n(r.metrics[0])}<small>{n(r.metrics[1])} users</small></strong></div>)}</div><h4>What visitors clicked</h4><ReportNotes report={data.clicks}/><div className="marketing-table-scroll"><table className="marketing-table"><thead><tr><th>Page</th><th>Action / destination</th><th>Clicks</th></tr></thead><tbody>{data.clicks.rows.map((r,i)=><tr key={i}><td>{r.dimensions[0]}</td><td>{r.dimensions[2] === "(not set)" ? eventLabels[r.dimensions[1]] : r.dimensions[2]}{r.dimensions[3].startsWith("https://stor24.co.za/") && <small className="marketing-cell-note">{r.dimensions[3].slice(20)}</small>}</td><td>{n(r.metrics[0])}</td></tr>)}</tbody></table></div><h4>Device performance</h4><ReportNotes report={data.devices}/>{data.devices.rows.map(r => <div className="abc-device" key={r.dimensions[0]}><strong>{r.dimensions[0]}</strong><span>{n(r.metrics[0])} sessions · {percent(r.metrics[1])} engaged · {time(r.metrics[2])} avg.</span></div>)}</div></div></article>
      <article className="abc-section"><header><span className="abc-letter">C</span><div><h3><Target size={18}/> Conversion</h3><p>See ordered progress, drop-offs and the reasons visitors actually report.</p></div></header><div className="abc-two-columns"><MarketingFunnel title="Choose a unit → saved reservation" funnel={data.funnels.booking}/><MarketingFunnel title="Enquiry → saved lead" funnel={data.funnels.enquiry}/></div><h4>Where actions completed or failed</h4><ReportNotes report={data.conversionPages}/><div className="marketing-table-scroll"><table className="marketing-table"><thead><tr><th>Public page</th><th>Outcome / signal</th><th>Events</th><th>Users</th></tr></thead><tbody>{data.conversionPages.rows.map((r,i)=><tr key={i}><td>{r.dimensions[0]}</td><td>{eventLabels[r.dimensions[1]] ?? r.dimensions[1]}</td><td>{n(r.metrics[0])}</td><td>{n(r.metrics[1])}</td></tr>)}</tbody></table></div><div className="abc-insight"><h4>What would help visitors decide?</h4>{feedback.length ? feedback.map(r => <div className="abc-device" key={r.dimensions[0]}><span>{eventLabels[r.dimensions[0]] ?? r.dimensions[0]}</span><strong>{n(r.metrics[0])} responses</strong></div>) : <p>No visitor feedback recorded in this filter and period. Pricing influence and reasons for not converting remain unknown. A price view followed by an exit does not prove a price objection.</p>}<p className="abc-note">Optional, consented feedback from the unit finder. Respondents are self-selected; counts are answers, not representative percentages or causal proof.</p></div></article>
      <details className="abc-coverage"><summary>Tracking coverage & measurement limits</summary><ul><li>Public page views, safe navigation and button clicks, scroll milestones and active-page time are measured after consent.</li><li>Unit finder stages, pricing exposure, selection, form attempts, generic errors and successful enquiry / reservation acknowledgements are separate events.</li><li>No form contents, contact details, booking references, identity, signing or payment pages are sent to analytics. Private customer workflows are excluded.</li><li>Rejected consent, blocked tags, network loss and historical untracked actions remain gaps. This is not every visitor or every click.</li><li>Signed leases, actual settlement and move-ins use the scoped CRM outcomes below. Browser acknowledgement is not payment proof.</li><li>Google / Meta ads conversion matching and CRM-to-GA reconciliation retain their separate provider and real-customer validation gates.</li></ul><a href="https://developers.google.com/analytics/devguides/reporting/data/v1/funnels" target="_blank" rel="noopener noreferrer">Google funnel definitions</a></details>
      {data.retrievedAt && <p className="abc-note">Retrieved {new Date(data.retrievedAt).toLocaleString("en-ZA", { timeZone: "Africa/Johannesburg" })}. Google processing delays and privacy thresholds apply. New event coverage collects forward from release.</p>}
    </>}
  </section>;
}
