"use client";
/* eslint-disable @next/next/no-img-element -- Same-origin authenticated synthetic sample must bypass image optimisation. */
import { useEffect, useState } from "react";
import { Warehouse, FileCheck2, Wallet, ShieldCheck, Camera, KeyRound, FlaskConical } from "lucide-react";
import { MoveInProgressNav } from "@/components/move-in-progress-nav";
import { trainingUnits, trainingRequired, trainingReady } from "@/lib/move-in-training-contract";
import type { TrainingSnapshot } from "@/lib/move-in-training";
const endpoint = "/api/v1/move-in-training";
async function readResponse(response: Response): Promise<TrainingSnapshot> {
  const result = await response.json();
  if (!response.ok) throw new Error(result.error?.message ?? "Training could not be loaded.");
  return result.data;
}
export function TrainingEntry() {
  const [data,setData] = useState<TrainingSnapshot | null>(null), [error,setError] = useState(""), [busy,setBusy] = useState(false);
  useEffect(()=>{ const refresh=()=>fetch(endpoint,{cache:"no-store"}).then(response=>response.ok ? readResponse(response) : null).then(setData).catch(()=>{}); void refresh(); const timer=setInterval(refresh,15000); return()=>clearInterval(timer); },[]);
  if (!data || (!data.canToggle && !data.enabled)) return null;
  return <aside className="training-entry"><div><strong><FlaskConical size={18} aria-hidden="true" /> Manager training</strong><p>{data.enabled ? "Training is available in a separate demo run. This booking is still live." : "Let yourself and facility managers practise payment, photo review and key handover."}</p></div><div className="training-entry__actions">{data.canToggle && <label><input type="checkbox" role="switch" aria-label="Enable manager training" checked={data.enabled} disabled={busy} onChange={async e=>{ const enabled=e.target.checked;setBusy(true);setError("");try{setData(await readResponse(await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"toggle",enabled,version:data.controlVersion})})));}catch(e){setError(e instanceof Error ? e.message : "Try again.");}finally{setBusy(false);}}} /> Training {data.enabled ? "on" : "off"}</label>}{data.canToggle && <small>Only you control this switch. Turning it off ends all current demo runs.</small>}{data.enabled && <a href="/operations/move-in/training" className="button button-primary">Start training</a>}</div>{error && <p role="alert">{error}</p>}</aside>;
}
export function MoveInTraining() {
  const [data,setData] = useState<TrainingSnapshot | null>(null), [error,setError] = useState(""), [busy,setBusy] = useState(false), [step,setStep] = useState(0), [preview,setPreview] = useState(false);
  useEffect(()=>{let active=true;const refresh=()=>fetch(`${endpoint}${data?.facilityId ? `?facility=${encodeURIComponent(data.facilityId)}` : ""}`,{cache:"no-store"}).then(readResponse).then(next=>{if(active)setData(next);}).catch(e=>{if(active){setData(null);setError(e.message);}});void refresh();const timer=setInterval(()=>{if(document.visibilityState === "visible")void refresh();},15000);return()=>{active=false;clearInterval(timer);};},[data?.facilityId]);
  async function command(action:string,value?:string,form?:FormData) {
    if(!data)return;setBusy(true);setError("");
    try {
      const response = await fetch(endpoint,{method:"POST",...(form ? {body:form} : {headers:{"Content-Type":"application/json"},body:JSON.stringify({action,facilityId:data.facilityId,version:data.run?.version,value})})});
      const next=await readResponse(response);setData(next);
      if(action === "preview")setPreview(true);
      else {setPreview(false);if(action === "unit")setStep(1);if(action === "agreement")setStep(2);if(action === "payment" && next.run && next.run.state.paid >= trainingRequired(next.run.state))setStep(3);if(action === "identity")setStep(4);if(action === "approve")setStep(5);if(action === "reset" || action === "start")setStep(0);}
    } catch(e){setError(e instanceof Error ? e.message : "Try again.");try{setData(await readResponse(await fetch(`${endpoint}?facility=${encodeURIComponent(data.facilityId)}`,{cache:"no-store"})));}catch{setData(null);}}finally{setBusy(false);}
  }
  async function upload(image:File) {if(!data?.run)return;const form=new FormData();form.set("facilityId",data.facilityId);form.set("version",String(data.run.version));form.set("image",image);await command("photo",undefined,form);}
  const state=data?.run?.state, required=state ? trainingRequired(state) : 0;
  const complete=state ? [!!state.unit,state.agreement,state.paid>=required && required>0,state.identity,state.photo==="APPROVED",!!state.handedOverAt] : [];
  const labels=["Select unit","Agreement","Payment","Check ID","Access photo","Hand over keys"];
  const icons=[Warehouse,FileCheck2,Wallet,ShieldCheck,Camera,KeyRound];
  return <div className="page-stack training-workspace"><header className="training-banner"><FlaskConical aria-hidden="true"/><div><strong>TRAINING MODE · Demo records only</strong><p>No real money, customers, units, messages or precinct access are changed. Use the supplied sample image only.</p></div></header><div className="page-header"><div><h1>Practise a move-in</h1><p>Demo customer · Training booking · Start date today</p></div><a className="button button-secondary" href="/operations/move-in">Return to live move-in</a></div>{error && <p className="form-error" role="alert">{error}</p>}
  {!data ? <p>{error ? "Training is unavailable. Return to live Move in or refresh." : "Loading training access…"}</p> : !data.enabled ? <section className="panel panel-spacious"><h2>Training is switched off</h2><p>Only the owner can enable it from Move in.</p><a href="/operations/move-in" className="button button-primary">Back to Move in</a></section> : <>
    <label>Training facility <select aria-label="Training facility" value={data.facilityId} disabled={busy} onChange={async e=>{setBusy(true);setError("");try{setData(await readResponse(await fetch(`${endpoint}?facility=${encodeURIComponent(e.target.value)}`,{cache:"no-store"})));setStep(0);setPreview(false);}catch(e){setError(e instanceof Error ? e.message : "Try again.");}finally{setBusy(false);}}}>{data.facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
    {!state ? <section className="panel panel-spacious"><h2>Your saved training run</h2><p>Work through all six stages. You can leave and resume while training remains enabled.</p><button className="button button-primary" disabled={busy || !data.facilityId} onClick={()=>command("start")}>Create my demo booking</button></section> : <>
    <MoveInProgressNav steps={labels.map((label,index)=>({label,icon:icons[index],complete:complete[index],status:complete[index] ? "Completed" : index===4 ? state.photo.replaceAll("_"," ").toLowerCase() : "To do",onClick:()=>{setStep(index);setPreview(false);}}))}/>
    <section className="panel panel-spacious training-step"><h2>{labels[step]}</h2>
    {step===0 && <><p>Choose a demo unit. These are not part of the live inventory.</p>{trainingUnits.map(unit=><button key={unit.id} className={`button ${state.unit===unit.id ? "button-primary" : "button-secondary"}`} disabled={busy || state.agreement} onClick={()=>command("unit",unit.id)}>{unit.name} · R{unit.rent.toFixed(2)}</button>)}</>}
    {step===1 && <><div className="training-document"><h3>TRAINING AGREEMENT · No legal effect</h3><p>Demo customer rents {state.unit ?? "a demo unit"} from today for R{required.toFixed(2)}. This practice document creates no real lease or tenancy.</p></div><button className="button button-primary" disabled={busy || !state.unit || state.agreement} onClick={()=>command("agreement","confirmed")}>{state.agreement ? "Demo agreement signed" : "Confirm demo agreement signed"}</button></>}
    {step===2 && <><p>Required R{required.toFixed(2)} · Test receipts R{state.paid.toFixed(2)} · Demo balance R{(required-state.paid).toFixed(2)}</p><form onSubmit={e=>{e.preventDefault();void command("payment",String(new FormData(e.currentTarget).get("amount")));}}><label>Test payment amount<input name="amount" type="number" min="0.01" max="10000" step="0.01" defaultValue={Math.max(0,required-state.paid)} required disabled={busy || !state.agreement || complete[2]}/></label><p>This records a training receipt only. No payment is taken.</p><button className="button button-primary" disabled={busy || !state.agreement || complete[2]}>Record test payment</button></form></>}
    {step===3 && <><div className="training-document"><h3>Sample identity · DEMO CUSTOMER</h3><p>Training reference DEMO-ID-001. No actual identity document is collected.</p></div><p>Practise matching the document to the customer and booking.</p><button className="button button-primary" disabled={busy || !complete[2] || state.identity} onClick={()=>command("identity","confirmed")}>{state.identity ? "Demo ID accepted" : "Confirm demo ID checked"}</button></>}
    {step===4 && <><p>Practise upload, private preview and staff approval. Real customer images are rejected; use this supplied non-person sample.</p><a href={`${endpoint}?sample=true`} download="stor24-training.png" className="button button-secondary">Download sample image</a><label>Upload supplied sample<input type="file" accept="image/png" disabled={busy || !state.identity || !!state.handedOverAt} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></label><p>Photo status: <strong>{state.photo.replaceAll("_"," ")}</strong></p>{state.photo==="WAITING_REVIEW" && <><button className="button button-primary" disabled={busy} onClick={()=>command("preview")}>Open sample for review</button>{preview && <div className="training-photo"><img src={`${endpoint}?sample=true`} alt="Synthetic training silhouette, not a person" width="120" height="160"/><div><button className="button button-primary" disabled={busy} onClick={()=>command("approve")}>Approve training photo</button><button className="button button-secondary" disabled={busy} onClick={()=>command("reject")}>Request replacement</button></div></div>}</>}</>}
    {step===5 && <>{state.handedOverAt ? <><h3>Training handover complete</h3><p>Demo tenancy active · Demo unit occupied · Training audit saved.</p><p>Precinct access: <strong>not provisioned</strong>. This confirms the training flow only.</p></> : <><p>{trainingReady(state) ? "All demo checks are complete. Practise confirming the customer and handing over keys." : "Complete the agreement, full test payment, ID check and approved sample photo first."}</p><form onSubmit={e=>{e.preventDefault();void command("handover","confirmed");}}><label><input type="checkbox" required disabled={!trainingReady(state) || busy}/> I am confirming a training key handover only.</label><button className="button button-primary" disabled={busy || !trainingReady(state)}>Record training handover</button></form></>}</>}
    <div className="training-footer">{step>0 && <button className="button button-secondary" onClick={()=>setStep(step-1)}>Previous step</button>}{step<5 && <button className="button button-secondary" onClick={()=>setStep(step+1)}>Next step</button>}{data.canToggle && <button className="button button-secondary" disabled={busy} onClick={()=>command("reset")}>Reset my demo run</button>}</div>
    </section></>}
  </>}
  </div>;
}
