"use client";

import { useState } from "react";
import { Plus, Settings2, Trash2 } from "lucide-react";

type Value = string | number | boolean;
type Settings = Record<string, Value>;
type Defaults = Record<string, Settings>;
type PaymentType = { name: string; description: string; allowed: boolean; onlineAllowed: boolean; reversals: boolean };
type StoreRef = { id: string; name: string };
type ResponseLists = { creditReasons: string[]; callNotePhrases: string[]; complimentaryReasons: string[]; unitNotes: string[] };
const tabs = ["General", "Proration", "Move In", "Move Out", "Invoice", "Payment Types", "Payments", "Credits", "Refunds", "Daily Close", "Late Fees", "Printing & Reports", "SMS", "South Africa", "Inter-store transfers", "Response lists", "Activity reasons", "Reservations"] as const;
type Tab = (typeof tabs)[number];
const securityLevels = ["Administrator", "Auditor", "Area Manager", "Site Manager", "User", "Part Timer", "Special", "Driver"];

export function ProgramDefaults({ initial, busy, stores, currentStoreId, onSave }: { initial?: Record<string, unknown>; busy: boolean; stores: StoreRef[]; currentStoreId: string; onSave: (config: Record<string, unknown>) => void }) {
  const [active, setActive] = useState<Tab>(tabs.includes(initial?.activeGroup as Tab) ? initial?.activeGroup as Tab : "General");
  const [defaults, setDefaults] = useState<Defaults>((initial?.defaults as Defaults) ?? {});
  const [paymentTypes, setPaymentTypes] = useState<PaymentType[]>(Array.isArray(initial?.paymentTypes) ? initial.paymentTypes as PaymentType[] : []);
  const [smsMessages, setSmsMessages] = useState<string[]>(Array.isArray(initial?.smsMessages) ? initial.smsMessages as string[] : []);
  const [responseLists, setResponseLists] = useState<ResponseLists>((initial?.responseLists as ResponseLists) ?? { creditReasons: [], callNotePhrases: [], complimentaryReasons: [], unitNotes: [] });
  const settings = defaults[active] ?? {};
  const set = (key: string, value: Value) => setDefaults((current) => ({ ...current, [active]: { ...(current[active] ?? {}), [key]: value } }));

  return <div className="company-form program-defaults-workspace">
    <div className="panel-heading"><div><p className="eyebrow">General setup</p><h2>Program defaults</h2><p className="panel-subtitle">Store-specific operational rules reproduced from the first SiteLink Program Defaults row.</p></div><Settings2 className="positive-icon"/></div>
    <div className="program-tabs" role="tablist">{tabs.map((tab) => <button type="button" role="tab" aria-selected={active === tab} className={active === tab ? "active" : ""} onClick={() => setActive(tab)} key={tab}>{tab}</button>)}</div>
    <p className="defaults-scope-note">Website attributes remain in their dedicated setup section. IP enforcement belongs in platform security, and unattended billing batches will only be exposed when live payment and invoicing workers are available.</p>
    <div className="program-default-panel"><ProgramPanel tab={active} values={settings} set={set} paymentTypes={paymentTypes} setPaymentTypes={setPaymentTypes} smsMessages={smsMessages} setSmsMessages={setSmsMessages} responseLists={responseLists} setResponseLists={setResponseLists} stores={stores} currentStoreId={currentStoreId}/></div>
    <div className="form-footer"><button type="button" className="button button-primary" disabled={busy} onClick={() => onSave({ activeGroup: active, defaults, paymentTypes, smsMessages, responseLists })}>{busy ? "Saving…" : "Save program defaults"}</button></div>
  </div>;
}

function ProgramPanel(props: { tab: Tab; values: Settings; set: (key: string, value: Value) => void; paymentTypes: PaymentType[]; setPaymentTypes: (rows: PaymentType[]) => void; smsMessages: string[]; setSmsMessages: (rows: string[]) => void; responseLists: ResponseLists; setResponseLists: (lists: ResponseLists) => void; stores: StoreRef[]; currentStoreId: string }) {
  const { tab, values: v, set } = props;
  if (tab === "General") return <div className="defaults-grid"><Group title="Gate defaults"><Select setting="gateTimeZone" label="Time zone" value={v.gateTimeZone} options={["Business Hours", "Gate Hours", "24 Hours"]} set={set}/><Select setting="keypadZone" label="Keypad zone" value={v.keypadZone} options={["All Keypads", "Entry Keypads", "Exit Keypads"]} set={set}/><Number setting="minimumGateBalance" label="Minimum balance before gate lockout" value={v.minimumGateBalance} set={set}/></Group><Group title="Tax defaults"><Number setting="taxRate1" label="Tax rate #1 (%)" value={v.taxRate1} step="0.001" set={set}/><Number setting="taxRate2" label="Tax rate #2 (%)" value={v.taxRate2} step="0.001" set={set}/></Group><Group title="Charge rounding"><Number setting="chargeRounding" label="Round calculated charges to nearest amount" value={v.chargeRounding} step="0.01" set={set}/></Group><Group title="Security log on" wide><Check setting="requireActionLogin" label="Require users to log on for sensitive actions" value={v.requireActionLogin} set={set}/><Check setting="enforcePci" label="Enforce PCI DSS credit-card security standards" value={v.enforcePci} set={set}/></Group><Group title="Auto-refresh local data" wide><Number setting="inactivityMinutes" label="Minutes of inactivity before refresh" value={v.inactivityMinutes ?? 20} min="1" set={set}/></Group><Group title="StorageForum" wide><Select setting="storageForumLevel" label="Minimum security level" value={v.storageForumLevel} options={securityLevels} set={set}/></Group></div>;
  if (tab === "Proration") return <div className="defaults-grid"><Group title="Billing default"><Radio setting="billingDefault" value={v.billingDefault} options={[["firstMonth","First-of-Month"],["28Day","28 Day Anniversary"],["anniversary","Anniversary"]]} set={set}/></Group><Group title="First-of-month proration"><Radio setting="firstMonthProration" value={v.firstMonthProration} options={[["schedule","Prorate first month according to schedule"],["secondMonth","Require full first month and prorate second month"]]} set={set}/><div className="range-grid"><Number setting="fullRentFrom" label="Charge full rent from day" value={v.fullRentFrom ?? 1} min="1" max="31" set={set}/><Number setting="fullRentTo" label="to" value={v.fullRentTo ?? 5} min="1" max="31" set={set}/><Number setting="prorateFrom" label="Prorate from day" value={v.prorateFrom ?? 6} min="1" max="31" set={set}/><Number setting="prorateTo" label="to" value={v.prorateTo ?? 24} min="1" max="31" set={set}/></div></Group><Group title="Paid-through date"><Radio setting="paidThrough" value={v.paidThrough} options={[["full","Change only for full rent payments"],["partial","Change for partial rent payments"]]} set={set}/></Group><Group title="Move-out proration"><Radio setting="firstMonthMoveOut" label="First-of-month billing" value={v.firstMonthMoveOut} options={[["month","Prorate by month"],["30day","Prorate by 30-day periods"]]} set={set}/><Radio setting="day28MoveOut" label="28-day billing" value={v.day28MoveOut} options={[["28day","Prorate by 28-day periods"],["7day","Prorate by 7-day periods"]]} set={set}/></Group></div>;
  if (tab === "Move In") return <div className="defaults-stack"><Group title="Move-in date"><Radio setting="moveInDate" value={v.moveInDate} options={[["today","Require move-in on today's date"],["todayFuture","Allow today's or future dates"],["any","Allow any past or future date"]]} set={set}/></Group><Group title="Authorised e-signature" wide><Check setting="blendSignAutoCountersign" label="Automatically countersign completed leases using the authorised company signature stored in BlendSign" value={v.blendSignAutoCountersign} set={set}/><p className="defaults-help">Leave this off during manual UAT. BlendSign must also have an authorised representative, signature, initials and company permission enabled.</p></Group><Group title="Concessions"><Check setting="belowStandardRent" label="Allow rent below the standard rate" value={v.belowStandardRent} set={set}/><Check setting="belowStandardCharges" label="Allow recurring charges below standard rates" value={v.belowStandardCharges} set={set}/><Check setting="predefinedConcessionsOnly" label="Require predefined concession plans" value={v.predefinedConcessionsOnly} set={set}/></Group><Group title="Miscellaneous move in"><Check setting="sendInvoices" label="Default to sending invoices to new tenants" value={v.sendInvoices} set={set}/><Check setting="requireMarketing" label="Require marketing data" value={v.requireMarketing} set={set}/><Check setting="chargeAdminFee" label="Charge the default administrative fee" value={v.chargeAdminFee} set={set}/><Check setting="printLease" label="Prompt to print lease" value={v.printLease} set={set}/></Group><Group title="Document delivery"><Check setting="deliveryPrint" label="Print" value={v.deliveryPrint} set={set}/><Check setting="deliveryEmail" label="Email" value={v.deliveryEmail} set={set}/></Group></div>;
  if (tab === "Move Out") return <div className="defaults-grid"><Group title="Move-out date"><p className="defaults-help">Saved date restrictions are checked in South African time before a new move-out changes access or accounts. Existing completed move-out retries retain their original result.</p><Radio setting="moveOutDate" value={v.moveOutDate} options={[["today","Require today's date"],["todayFuture","Allow today's or future dates"],["todayPast","Allow today's or past dates"],["any","Allow any past or future date"]]} set={set}/><Number setting="maxBackdatingDays" label="Maximum backdating days (blank or 0 = unlimited)" value={v.maxBackdatingDays} min="0" set={set}/><Check setting="restrictCurrentMonth" label="Restrict backdating to current month" value={v.restrictCurrentMonth} set={set}/></Group><Group title="Insufficient notice fee"><Radio setting="noticeFeeMode" value={v.noticeFeeMode} options={[["none","Do not use"],["prorated","Charge prorated days"],["fixed","Charge a fixed amount"],["percent","Charge a percentage of rent"]]} set={set}/><Number setting="noticeFeeDays" label="Days of rental rate" value={v.noticeFeeDays ?? 14} min="0" set={set}/><Number setting="noticeFeeAmount" label="Fixed amount" value={v.noticeFeeAmount} min="0" step="0.01" set={set}/><Number setting="noticeFeePercent" label="Percentage of rental rate" value={v.noticeFeePercent} min="0" step="0.01" set={set}/><Check setting="alwaysNoticeFee" label="Always charge fee during move-out" value={v.alwaysNoticeFee} set={set}/></Group><Group title="Miscellaneous move out"><Check setting="disableProration" label="Disable move-out proration" value={v.disableProration} set={set}/><Number setting="disableProrationAfterDay" label="Days after billing-period start" value={v.disableProrationAfterDay ?? 14} min="1" max="31" set={set}/><Check setting="promptLedger" label="Prompt to print ledger history and notes" value={v.promptLedger} set={set}/><Check setting="allowBadDebtWriteoff" label="Allow bad-debt write-off at move-out" value={v.allowBadDebtWriteoff} set={set}/><Check setting="reuseAccessCode" label="Prompt to change and re-use access code" value={v.reuseAccessCode} set={set}/><Check setting="requireExitSurvey" label="Require exit survey data" value={v.requireExitSurvey} set={set}/><Check setting="preventPreviousReversal" label="Prevent reversals from previous months" value={v.preventPreviousReversal} set={set}/></Group><Group title="Unpaid future charges"><Radio setting="futureCharges" value={v.futureCharges} options={[["delete","Delete unpaid future charges"],["credit","Credit unpaid future charges"]]} set={set}/></Group><Group title="Transfer" wide><Check setting="chargeTransferFee" label="Charge the default transfer fee" value={v.chargeTransferFee} set={set}/></Group></div>;
  if (tab === "Invoice") return <div className="defaults-grid"><Group title="Invoice timing"><Number setting="invoiceDaysBefore" label="Print invoices this many days before rent due" value={v.invoiceDaysBefore ?? 60} set={set}/><Check setting="chargeInvoiceFee" label="Charge default invoice fee" value={v.chargeInvoiceFee} set={set}/><Text setting="locationCode" label="Location code shown on invoice" value={v.locationCode} set={set}/></Group><Group title="Unpaid charge selection"><Radio setting="unpaidSelection" value={v.unpaidSelection} options={[["all","All billing periods"],["pastCurrent","Past and current billing periods"]]} set={set}/></Group><Group title="Remittance address"><TextArea setting="remittanceAddress" label="Address" value={v.remittanceAddress} set={set}/><Check setting="useSiteAddress" label="Use site address" value={v.useSiteAddress} set={set}/></Group><Group title="Format"><Radio setting="invoiceFormat" value={v.invoiceFormat} options={[["onePage","One-page invoice"],["detailedNew","Detailed: charges not previously invoiced"],["detailedAll","Detailed: all unpaid charges"]]} set={set}/></Group></div>;
  if (tab === "Payment Types") return <PaymentTypes rows={props.paymentTypes} setRows={props.setPaymentTypes}/>;
  if (tab === "Payments") return <div className="defaults-grid"><Group title="Receipt printing"><Radio setting="receiptPrinting" value={v.receiptPrinting} options={[["prompt","Prompt before printing"],["always","Always print receipt"],["never","Never print receipt"]]} set={set}/></Group><Group title="Order of payments"><Radio setting="paymentOrder" value={v.paymentOrder} options={[["oldest","Oldest first"],["rent","Rent before fees"],["fees","Fees before rent"]]} set={set}/></Group><Group title="Receipt emailing"><Radio setting="receiptEmailing" value={v.receiptEmailing} options={[["prompt","Prompt before emailing"],["always","Always email receipt"],["never","Never email receipt"]]} set={set}/></Group><Group title="Ledger format"><Radio setting="ledgerFormat" value={v.ledgerFormat} options={[["standard","Standard ledger"],["simple","Simple ledger"]]} set={set}/></Group><Group title="Miscellaneous" wide><Check setting="showCardOnFile" label="Show card on file when taking a card payment" value={v.showCardOnFile} set={set}/><Check setting="partialReminder" label="Prompt to print a partial-payment reminder" value={v.partialReminder} set={set}/><Check setting="disablePastDue" label="Prompt to disable past-due handling" value={v.disablePastDue} set={set}/><Check setting="preventBackdatedCharges" label="Prevent backdated charges when manually adding one" value={v.preventBackdatedCharges} set={set}/><Check setting="saveAutoBill" label="Prompt to save auto-bill information" value={v.saveAutoBill} set={set}/><Number setting="disablePartialAfterDays" label="Disable partial payments after days past due" value={v.disablePartialAfterDays ?? 0} min="0" set={set}/><Number setting="resetPastDueWithinDays" label="Reset past-due events within days" value={v.resetPastDueWithinDays ?? 0} min="0" set={set}/></Group></div>;
  if (tab === "Credits") return <div className="defaults-stack"><Group title="Employee restrictions on issuing credits - global"><Number setting="maxCreditsPerPeriod" label="Maximum credits per period (0 = disabled)" value={v.maxCreditsPerPeriod ?? 0} min="0" step="0.01" set={set}/><Select setting="globalCreditLevel" label="Security level required above maximum" value={v.globalCreditLevel} options={securityLevels} set={set}/><Radio setting="creditResetPeriod" label="Reset period" value={v.creditResetPeriod} options={[["current","Current month"],["3months","Previous 3 months"],["6months","Previous 6 months"],["12months","Previous 12 months"],["never","Never reset"]]} set={set}/></Group><Group title="Employee restrictions - by tenant ledger"><Number setting="maxCreditsPerLedger" label="Maximum credits per ledger account" value={v.maxCreditsPerLedger ?? 0} min="0" step="0.01" set={set}/><Select setting="ledgerCreditLevel" label="Security level required above maximum" value={v.ledgerCreditLevel} options={securityLevels} set={set}/></Group><Group title="Discount restrictions"><Number setting="maxMerchandiseDiscount" label="Maximum merchandise discount (%)" value={v.maxMerchandiseDiscount ?? 0} min="0" max="100" step="0.01" set={set}/><Select setting="discountLevel" label="Security level required above maximum" value={v.discountLevel} options={securityLevels} set={set}/></Group></div>;
  if (tab === "Refunds") return <Group title="Refund restrictions"><Number setting="merchandiseReturnDays" label="Maximum days since original purchase" value={v.merchandiseReturnDays ?? 14} min="0" set={set}/><Number setting="minimumRefund" label="Minimum allowed refund (0 = disabled)" value={v.minimumRefund ?? 0} min="0" step="0.01" set={set}/><Number setting="maximumRefund" label="Maximum allowed refund (0 = disabled)" value={v.maximumRefund ?? 0} min="0" step="0.01" set={set}/><Select setting="refundLevel" label="Security level required above maximum" value={v.refundLevel} options={securityLevels} set={set}/></Group>;
  if (tab === "Daily Close") return <div className="defaults-stack"><Group title="Automatic daily close"><Radio setting="automaticDailyClose" value={v.automaticDailyClose} options={[["none","Do not use automatic daily close"],["midnight","Always close automatically at midnight"],["payments","Close automatically only when payments were made"]]} set={set}/></Group><Group title="Miscellaneous"><Check setting="requireLeadsBeforeClose" label="Require walk-ins and leads before making a daily close" value={v.requireLeadsBeforeClose} set={set}/></Group></div>;
  if (tab === "Late Fees") return <div className="defaults-stack"><Group title="Late fee defaults for tenants"><Radio setting="lateFeeSchedule" value={v.lateFeeSchedule} options={[["chargeSetup","Use settings under Charge Setup"],["california","Use California Late Fee Schedule"]]} set={set}/></Group><Group title="Late fee threshold"><Radio setting="lateFeeThresholdMode" value={v.lateFeeThresholdMode} options={[["fixed","Fixed amount"],["percent","Percentage of rent"]]} set={set}/><Number setting="lateFeeThreshold" label="Minimum past-due threshold" value={v.lateFeeThreshold} min="0" step="0.01" set={set}/></Group><Check setting="lateFeesByUnit" label="Set up late fees unit-by-unit" value={v.lateFeesByUnit} set={set}/></div>;
  if (tab === "Printing & Reports") return <div className="defaults-grid"><Group title="Reporting options" wide><Number setting="monthlyPeriodEndDay" label="Monthly period ending day" value={v.monthlyPeriodEndDay} min="1" max="31" set={set}/><Number setting="fiscalYearStartMonth" label="Fiscal year starts in month" value={v.fiscalYearStartMonth} min="1" max="12" set={set}/><Check setting="exportStoreColumns" label="Add store name and location code to Excel exports" value={v.exportStoreColumns} set={set}/></Group><Group title="Start-of-day printing"><Radio setting="startPrinting" value={v.startPrinting} options={[["none","Do not use printing automation"],["prompt","Prompt to print letters and reports"]]} set={set}/><Check setting="printLettersNoFee" label="Letters without an associated fee" value={v.printLettersNoFee} set={set}/><Check setting="printLettersAll" label="Letters with or without an associated fee" value={v.printLettersAll} set={set}/><Check setting="printInvoices" label="Invoices" value={v.printInvoices} set={set}/><Check setting="printStartReports" label="Start-of-day reports" value={v.printStartReports} set={set}/></Group><Group title="Printing options"><Select setting="defaultFont" label="Default font" value={v.defaultFont} options={["Arial", "Calibri", "Times New Roman", "Verdana"]} set={set}/><Check setting="collatePages" label="Collate pages" value={v.collatePages} set={set}/><Radio setting="paperSize" label="Paper size" value={v.paperSize} options={[["letter","US Letter"],["a4","A4"]]} set={set}/></Group></div>;
  if (tab === "SMS") return <SmsMessages rows={props.smsMessages} setRows={props.setSmsMessages}/>;
  if (tab === "South Africa") return <div className="defaults-grid"><Group title="South African defaults"><Text setting="country" label="Country" value={v.country ?? "South Africa"} set={set}/><Text setting="currency" label="Currency" value={v.currency ?? "ZAR"} set={set}/><Check setting="useAreaMeasurements" label="Show area measurements on unit lists" value={v.useAreaMeasurements ?? true} set={set}/><Select setting="measurementSystem" label="Measurement system" value={v.measurementSystem ?? "Metric (metres)"} options={["Metric (metres)"]} set={set}/><Number setting="currencyDecimals" label="Currency decimal places" value={v.currencyDecimals ?? 2} min="0" max="4" set={set}/><Number setting="taxDecimals" label="Tax decimal places" value={v.taxDecimals ?? 2} min="0" max="4" set={set}/></Group><Group title="VAT"><Number setting="vatRate" label="Standard VAT rate (%)" value={v.vatRate ?? 15} min="0" max="100" step="0.01" set={set}/><Radio setting="vatDisplay" label="Pricing treatment" value={v.vatDisplay ?? "inclusive"} options={[["inclusive","VAT-inclusive customer pricing"],["exclusive","VAT added to the displayed charge"]]} set={set}/><p className="defaults-help">Defaulted to the current South African standard VAT rate. Confirm vendor-specific tax treatment with finance before operational use.</p></Group></div>;
  if (tab === "Inter-store transfers") return <div className="defaults-stack"><Group title="Inter-store inventory transfers"><Check setting="enableTransfers" label="Enable transfers from this store" value={v.enableTransfers} set={set}/><Check setting="requireTransferApproval" label="Require manager approval before dispatch" value={v.requireTransferApproval ?? true} set={set}/><Check setting="requireReceiptConfirmation" label="Require receiving-store confirmation" value={v.requireReceiptConfirmation ?? true} set={set}/></Group><Group title="Allowed destination stores"><div className="check-grid">{props.stores.filter((store) => store.id !== props.currentStoreId).map((store) => <Check key={store.id} setting={`destination:${store.id}`} label={store.name} value={v[`destination:${store.id}`]} set={set}/>)}</div></Group></div>;
  if (tab === "Response lists") return <div className="defaults-grid response-list-grid"><ListEditor title="Predefined credit reasons" rows={props.responseLists.creditReasons} setRows={(rows) => props.setResponseLists({ ...props.responseLists, creditReasons: rows })}/><ListEditor title="Predefined call-note phrases" rows={props.responseLists.callNotePhrases} setRows={(rows) => props.setResponseLists({ ...props.responseLists, callNotePhrases: rows })}/><ListEditor title="Complimentary-unit reasons" rows={props.responseLists.complimentaryReasons} setRows={(rows) => props.setResponseLists({ ...props.responseLists, complimentaryReasons: rows })}/><ListEditor title="Predefined unit notes" rows={props.responseLists.unitNotes} setRows={(rows) => props.setResponseLists({ ...props.responseLists, unitNotes: rows })}/></div>;
  if (tab === "Activity reasons") return <Group title="Require a reason for selected activities"><div className="check-grid activity-reason-grid"><CheckList values={v} set={set} items={activityReasonItems}/></div></Group>;
  return <Group title="Reservation defaults"><Number setting="reservationExpiryDays" label="Days after placement before a reservation expires" value={v.reservationExpiryDays ?? 60} min="1" set={set}/><Number setting="newLeadFollowupDays" label="Days before first follow-up on a new lead" value={v.newLeadFollowupDays ?? 1} min="0" set={set}/><Number setting="subsequentFollowupDays" label="Days between subsequent follow-ups" value={v.subsequentFollowupDays ?? 1} min="0" set={set}/><Check setting="applyReservationFee" label="Apply reservation fee to converted move-in by default" value={v.applyReservationFee} set={set}/></Group>;
}

const activityReasonItems: [string, string][] = [["discountCharge","Manually discount a charge"],["issueCredit","Manually issue a credit"],["waiveLateFees","Waive late fees"],["complimentaryUnit","Set a unit as complimentary"],["editUnitName","Edit unit name"],["editUnitType","Edit unit type"],["editUnitSize","Edit unit size"],["editUnitRates","Edit standard rates"],["editSecurityDeposit","Edit standard security deposit"],["editUnitStatus","Edit rentable status"],["deleteUnit","Delete a unit"],["deleteUnitType","Delete a unit type"],["editMerchandise","Edit a charge or merchandise item"],["deleteMerchandise","Delete a charge or merchandise item"],["deleteDiscount","Delete a discount plan"],["deleteEmployee","Delete an employee"],["editTenantRent","Edit tenant rent"],["editMoveInDate","Edit tenant move-in date"],["editLeaseDate","Edit tenant lease date"],["editAnniversary","Edit tenant anniversary date"],["editTenantDefaults","Edit tenant fee or late-fee defaults"],["editBillingFrequency","Edit tenant billing frequency"],["editTaxExempt","Edit tenant tax-exempt status"],["disablePastDue","Disable tenant past-due events"],["refundFee","Refund a fee or returned merchandise"],["editRevenueSettings","Edit revenue-management settings"]];

function PaymentTypes({ rows, setRows }: { rows: PaymentType[]; setRows: (rows: PaymentType[]) => void }) { return <Group title="Payment types"><div className="editor-list">{rows.map((row, index) => <div className="payment-type-row" key={index}><input aria-label="Payment type" placeholder="Payment type" value={row.name} onChange={(e) => setRows(rows.map((item, i) => i === index ? { ...item, name: e.target.value } : item))}/><input aria-label="Description" placeholder="Description" value={row.description} onChange={(e) => setRows(rows.map((item, i) => i === index ? { ...item, description: e.target.value } : item))}/><InlineCheck label="Allowed" checked={row.allowed} onChange={(value) => setRows(rows.map((item, i) => i === index ? { ...item, allowed: value } : item))}/><InlineCheck label="Online" checked={row.onlineAllowed} onChange={(value) => setRows(rows.map((item, i) => i === index ? { ...item, onlineAllowed: value } : item))}/><InlineCheck label="Reversals" checked={row.reversals} onChange={(value) => setRows(rows.map((item, i) => i === index ? { ...item, reversals: value } : item))}/><button type="button" className="icon-button" aria-label="Delete payment type" onClick={() => setRows(rows.filter((_, i) => i !== index))}><Trash2 size={15}/></button></div>)}</div><button type="button" className="button button-secondary button-small editor-add" onClick={() => setRows([...rows, { name: "", description: "", allowed: true, onlineAllowed: false, reversals: false }])}><Plus size={14}/>Add payment type</button></Group>; }
function SmsMessages({ rows, setRows }: { rows: string[]; setRows: (rows: string[]) => void }) { return <Group title="Predefined SMS messages"><div className="editor-list">{rows.map((row, index) => <div className="sms-row" key={index}><textarea aria-label={`SMS message ${index + 1}`} rows={2} maxLength={320} value={row} onChange={(e) => setRows(rows.map((item, i) => i === index ? e.target.value : item))}/><button type="button" className="icon-button" aria-label="Delete SMS message" onClick={() => setRows(rows.filter((_, i) => i !== index))}><Trash2 size={15}/></button></div>)}</div><button type="button" className="button button-secondary button-small editor-add" onClick={() => setRows([...rows, ""])}><Plus size={14}/>Add SMS message</button></Group>; }
function ListEditor({ title, rows, setRows }: { title: string; rows: string[]; setRows: (rows: string[]) => void }) { return <Group title={title}><div className="editor-list">{rows.map((row, index) => <div className="list-editor-row" key={index}><input aria-label={`${title} ${index + 1}`} value={row} onChange={(e) => setRows(rows.map((item, i) => i === index ? e.target.value : item))}/><button type="button" className="icon-button" aria-label={`Delete ${title} item`} onClick={() => setRows(rows.filter((_, i) => i !== index))}><Trash2 size={15}/></button></div>)}</div><button type="button" className="button button-secondary button-small editor-add" onClick={() => setRows([...rows, ""])}><Plus size={14}/>Add item</button></Group>; }
function CheckList({ values, set, items }: { values: Settings; set: (key: string, value: Value) => void; items: [string, string][] }) { return <>{items.map(([setting, label]) => <Check key={setting} setting={setting} label={label} value={values[setting]} set={set}/>)}</>; }
function Group({ title, wide, children }: { title: string; wide?: boolean; children: React.ReactNode }) { return <section className={`defaults-group${wide ? " defaults-group-wide" : ""}`}><h3>{title}</h3><div className="defaults-fields">{children}</div></section>; }
function Check({ setting, label, value, set }: { setting: string; label: string; value: Value | undefined; set: (key: string, value: Value) => void }) { return <label className="check-label"><input type="checkbox" checked={Boolean(value)} onChange={(e) => set(setting, e.target.checked)}/><span>{label}</span></label>; }
function InlineCheck({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="check-label compact"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)}/><span>{label}</span></label>; }
function Radio({ setting, label, value, options, set }: { setting: string; label?: string; value: Value | undefined; options: string[][]; set: (key: string, value: Value) => void }) { return <fieldset className="radio-field"><legend>{label}</legend>{options.map(([optionValue, optionLabel]) => <label key={optionValue}><input type="radio" name={setting} checked={value === optionValue} onChange={() => set(setting, optionValue)}/><span>{optionLabel}</span></label>)}</fieldset>; }
function Number({ setting, label, value, set, ...props }: { setting: string; label: string; value: Value | undefined; set: (key: string, value: Value) => void } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "type" | "value">) { return <label>{label}<input type="number" value={value === undefined ? "" : String(value)} onChange={(e) => set(setting, e.target.value === "" ? "" : globalThis.Number(e.target.value))} {...props}/></label>; }
function Text({ setting, label, value, set }: { setting: string; label: string; value: Value | undefined; set: (key: string, value: Value) => void }) { return <label>{label}<input value={String(value ?? "")} onChange={(e) => set(setting, e.target.value)}/></label>; }
function TextArea({ setting, label, value, set }: { setting: string; label: string; value: Value | undefined; set: (key: string, value: Value) => void }) { return <label>{label}<textarea rows={5} value={String(value ?? "")} onChange={(e) => set(setting, e.target.value)}/></label>; }
function Select({ setting, label, value, options, set }: { setting: string; label: string; value: Value | undefined; options: string[]; set: (key: string, value: Value) => void }) { return <label>{label}<select value={String(value ?? "")} onChange={(e) => set(setting, e.target.value)}><option value="">Select…</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
