"use client";
import {useRef,useState} from "react";
import {reportCsvRows} from "@/lib/report-history-contract";
import type {ReportDataset} from "@/lib/visual-report-contract";
export function ReportHistoryImporter({datasets,facilities,onImported}:{datasets:ReportDataset[];facilities:{id:string;name:string}[];onImported:()=>Promise<void>}) {
  const [datasetKey,setDatasetKey]=useState(datasets[0]?.key??""),[facilityId,setFacilityId]=useState(facilities[0]?.id??""),[csv,setCsv]=useState(""),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({});
  const [name,setName]=useState(""),[extractedAt,setExtractedAt]=useState(""),[approvalReference,setApprovalReference]=useState(""),[validated,setValidated]=useState<{rowCount:number;unmappedFields:string[];sourceSha256:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[failed,setFailed]=useState(false);
  const lock=useRef(false),dataset=datasets.find(d=>d.key===datasetKey);
  const invalidate=()=>{setValidated(null);setMessage("");};
  const readFile=async(file:File|undefined)=>{invalidate();setCsv("");setHeaders([]);setMapping({});if(!file)return;setBusy(true);try{if(file.size>5*1024*1024)throw new Error("Choose a CSV smaller than 5 MB.");const source=await file.text(),rows=reportCsvRows(source);const columns=rows[0]?.map(h=>h.trim())??[];if(!columns.length)throw new Error("The CSV has no headers.");setCsv(source);setHeaders(columns);setName(file.name.replace(/\.csv$/i,""));setMapping(Object.fromEntries(["sourceRecordId",...(dataset?.fields.map(f=>f.key)??[])].filter(key=>columns.includes(key)).map(key=>[key,key])));setFailed(false);}catch(error){setFailed(true);setMessage(error instanceof Error?error.message:"Unable to read CSV.");}finally{setBusy(false);}};
  const submit=async(kind:"validate"|"import")=>{
    if(lock.current)return;lock.current=true;setBusy(true);setMessage("");setFailed(false);
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);
    try{
      // datetime-local is explicitly SAST, independent of the employee's device timezone.
      const body={kind,dataset:datasetKey,facilityId,csv,mapping:Object.fromEntries(Object.entries(mapping).filter(([,header])=>header)),name,extractedAt:extractedAt?`${extractedAt}:00+02:00`:"",approvalReference};
      const response=await fetch("/api/v1/reports/history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error?.message??"History import failed.");
      if(kind==="validate"){setValidated(result.data);setMessage(`Validated ${result.data.rowCount} records. Review the missing fields before importing.`);}else{setValidated(null);setCsv("");setHeaders([]);await onImported();setMessage(`Imported ${result.data.rowCount} reporting records. Current customer accounts and payments were not changed.`);}
    }catch(error){setFailed(true);setMessage(error instanceof Error?error.message:"Import failed. Retry with the same extract to recover the same import.");}finally{clearTimeout(timer);lock.current=false;setBusy(false);}
  };
  if(!dataset)return null;
  return <section className="panel panel-spacious"><h2>Import SiteLink reporting history</h2><p>Import one approved extract for one store and dataset. Map source columns to the fields below, validate, then import. Reporting history is kept separate from current customer and finance records.</p><fieldset disabled={busy} className="report-builder-fieldset"><div className="form-grid"><label>Dataset<select value={datasetKey} onChange={e=>{invalidate();setDatasetKey(e.target.value);setMapping({});}}>{datasets.map(d=><option value={d.key} key={d.key}>{d.name}</option>)}</select></label><label>Store<select value={facilityId} onChange={e=>{invalidate();setFacilityId(e.target.value);}}>{facilities.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Source CSV<input type="file" accept=".csv,text/csv" onChange={e=>void readFile(e.target.files?.[0])}/></label><label>Extract name<input value={name} maxLength={100} onChange={e=>{invalidate();setName(e.target.value);}}/></label><label>Extracted at (SAST)<input type="datetime-local" value={extractedAt} onChange={e=>{invalidate();setExtractedAt(e.target.value);}}/></label><label>Approval / reconciliation reference<input value={approvalReference} maxLength={150} onChange={e=>{invalidate();setApprovalReference(e.target.value);}}/></label></div>{headers.length>0&&<><h3>Column mapping</h3><p>Source record IDs must be unique. Blank mappings become “Not recorded”. Monetary history requires an explicit currency column. Use ISO dates and unformatted decimal amounts.</p><div className="form-grid">{[{key:"sourceRecordId",label:"Source record ID (required)"},...dataset.fields.filter(f=>f.key!=="facility")].map(field=><label key={field.key}>{field.label}<select value={mapping[field.key]??""} onChange={e=>{invalidate();setMapping(m=>({...m,[field.key]:e.target.value}));}}><option value="">Not recorded / unmapped</option>{headers.map(header=><option key={header}>{header}</option>)}</select></label>)}</div></>}{validated&&<div className="report-builder-basis"><p>{validated.rowCount} rows · Source fingerprint {validated.sourceSha256.slice(0,12)}…</p><p>Unmapped fields: {validated.unmappedFields.map(key=>dataset.fields.find(f=>f.key===key)?.label??key).join(", ")||"None"}.</p><p>Validation confirms format and mapping. Your approval reference records reconciliation responsibility; validation does not independently verify SiteLink or accounting totals.</p></div>}<div className="button-row"><button className="button button-secondary" disabled={!csv} onClick={()=>void submit("validate")}>Validate extract</button><button className="button button-primary" disabled={!validated} onClick={()=>void submit("import")}>Import validated history</button></div></fieldset>{busy&&<p role="status">Processing reporting history…</p>}{message&&<p role={failed?"alert":"status"}>{message}</p>}</section>;
}
