'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowUpRight, CheckCircle2, CircleHelp, RefreshCw, ShieldCheck, AlertTriangle, Download } from 'lucide-react';
import { PageHeader } from './page-header';
import type { OperationsDiagnostics } from '@/lib/operations-diagnostics';
import { formatSouthAfricaDateTime } from '@/lib/south-africa-time';

const queueKeys: ('incoming' | 'outgoing')[] = ['incoming', 'outgoing'];
const labels = { good: 'Verified', warning: 'Review', critical: 'Needs attention', unknown: 'Not verified' };
const time = (value: string | null | undefined) => value ? formatSouthAfricaDateTime(value) : 'No recorded check';
async function readDiagnostics(signal?: AbortSignal): Promise<OperationsDiagnostics> {
  const response = await fetch('/api/v1/operations/diagnostics', { cache: 'no-store', signal: signal ? AbortSignal.any([signal, AbortSignal.timeout(35_000)]) : AbortSignal.timeout(35_000) });
  if (!response.ok) throw Error();
  const body = await response.json();
  if (!Array.isArray(body.data?.cards) || !Array.isArray(body.data?.history) || !Array.isArray(body.data?.messagingConfigured) || !body.data?.queues || typeof body.data?.checkedAt !== 'string') throw Error();
  return body.data;
}
export function TroubleshootingDashboard() {
  const [data, setData] = useState<OperationsDiagnostics | null>(null);
  const [busy, setBusy] = useState(true); const [error, setError] = useState('');
  const resourceProblem = data?.hostFresh && data.host && (data.host.appHealth !== 'healthy' || data.host.oomKilled === true || (data.host.databaseConnections != null && data.host.databaseLimit != null && data.host.databaseLimit > 0 && data.host.databaseConnections / data.host.databaseLimit >= .8));
  function load(signal?: AbortSignal) {
    return readDiagnostics(signal).then(value => { if (!signal?.aborted) setData(value); })
      .catch(() => { if (!signal?.aborted) setError('The dashboard could not refresh. The figures below may be out of date. Check your alert messages or open the external monitor if the website is unavailable.'); })
      .finally(() => { if (!signal?.aborted) setBusy(false); });
  }
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, []);
  function refresh() { setBusy(true); setError(''); void load(); }
  function download() {
    if (!data) return;
    const file = new Blob([JSON.stringify({ ...data, exportedAt: new Date().toISOString(), note: 'Operational evidence only. Provider acceptance is not recipient delivery; local backups are not independent recovery.' }, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(file); const link = document.createElement('a'); link.href = url; link.download = 'stor24-troubleshooting.json'; link.click(); URL.revokeObjectURL(url);
  }
  return <div className="page-stack troubleshooting-workspace">
    <PageHeader eyebrow="Administration · System health" title="Troubleshooting" description="A clear view of what is working, what needs attention and where to investigate next." />
    <div className="diagnostic-toolbar"><div><span className="diagnostic-live"><Activity size={15} /> Read-only checks</span><p className="muted">{data ? `Dashboard refreshed ${time(data.checkedAt)} · SAST` : 'Loading operational evidence…'}</p></div><div className="diagnostic-buttons"><button className="button button-secondary" onClick={download} disabled={!data || busy}><Download size={16} /> Download diagnostics</button><button className="button button-primary" onClick={() => void refresh()} disabled={busy}><RefreshCw size={16} className={busy ? 'diagnostic-spin' : ''} />{busy ? 'Checking…' : 'Refresh checks'}</button></div></div>
    {error && <div className="diagnostic-notice" role="alert"><AlertTriangle size={20} /><div><strong>Refresh unavailable</strong><p>{error}</p></div><a href="https://github.com/blendproperty/stor24-portal/actions/workflows/monitor-production.yml" target="_blank" rel="noreferrer">Open external monitor <ArrowUpRight size={15} /></a></div>}
    {!data && !busy && <section className="panel"><p>No current dashboard evidence is available. Use Refresh checks to try again.</p></section>}
    {data && <>
      {resourceProblem && <div className="diagnostic-notice" role="alert"><AlertTriangle size={20} /><div><strong>Application or database resource check needs attention</strong><p>Review the application health, memory-limit termination and database connection figures below. Check the external monitor and Hostinger logs before changing a service.</p></div></div>}
      <section className="diagnostic-grid" aria-label="System health checks">{data.cards.map(card => {
        const Icon = card.state === 'good' ? CheckCircle2 : card.state === 'unknown' ? CircleHelp : AlertTriangle;
        return <article className={`diagnostic-card diagnostic-${card.state}`} key={card.id}><div className="diagnostic-card-top"><Icon size={20} /><span>{labels[card.state]}</span></div><h2>{card.title}</h2><strong className="diagnostic-value">{card.value}</strong><p>{card.detail}</p><small>{time(card.checkedAt)}</small><details><summary>What to do next</summary><p>{card.next}</p>{card.href && <a href={card.href} target={card.href.startsWith('https:') ? '_blank' : undefined} rel="noreferrer">Open investigation <ArrowUpRight size={14} /></a>}</details></article>;
      })}</section>
      <section className="panel diagnostic-resources"><div className="panel-heading"><div><h2>Application &amp; recovery</h2><p className="panel-subtitle">Host evidence refreshes every minute. Refresh this page to read the latest snapshot.</p></div><ShieldCheck size={22} /></div><div className="diagnostic-facts"><div><span>Application health</span><strong>{data.hostFresh ? (data.host?.appHealth ?? 'Unknown') : 'Not verified · snapshot stale or missing'}</strong></div><div><span>Memory-limit termination</span><strong>{!data.hostFresh || data.host?.oomKilled == null ? 'Not verified' : data.host.oomKilled ? 'Detected · investigate server logs' : 'Not detected in current container state'}</strong></div><div><span>Database connections</span><strong>{data.hostFresh && data.host?.databaseConnections != null && data.host.databaseLimit ? `${data.host.databaseConnections} / ${data.host.databaseLimit}` : 'Not verified'}</strong></div><div><span>Released image</span><strong>{data.host?.image ?? 'Not recorded'}</strong></div><div><span>Latest isolated restore proof</span><strong>{time(data.backup?.restoredAt)}</strong></div><div><span>Off-server recovery</span><strong>{data.backup?.offSite ? 'Off-server copy recorded · full recovery acceptance separate' : 'Not verified · independent copy and keys remain open'}</strong></div></div></section>
      <section className="panel diagnostic-integrations"><div className="panel-heading"><div><h2>Integrations &amp; delivery queues</h2><p className="panel-subtitle">Saved connection evidence, not a new provider test. Configuration alone does not prove end-to-end operation.</p></div><Link className="text-button" href="/integrations">Open integrations <ArrowUpRight size={15} /></Link></div><div className="diagnostic-facts"><div><span>Messaging configuration present</span><strong>{data.messagingConfigured.length ? data.messagingConfigured.join(', ') : 'None verified'}</strong></div>{queueKeys.map(key => <div key={key}><span>{key === 'incoming' ? 'Incoming events' : 'Outgoing events'}</span><strong>{data.queues[key] ? `${data.queues[key]?.pending} pending / processing · ${data.queues[key]?.failed} failed / dead-letter` : 'Read unavailable'}</strong></div>)}</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Integration</th><th>Recorded state</th><th>Last connection check</th></tr></thead><tbody>{data.connections?.length ? data.connections.map((row, index) => <tr key={index}><td>{row.provider}</td><td>{row.status}{row.stale ? ' · evidence stale or untested' : ''}</td><td>{time(row.checkedAt)}</td></tr>) : <tr><td colSpan={3}>{data.connections === null ? 'Connection evidence could not be read.' : 'No saved integration connection records. Configuration and provider tests are still required.'}</td></tr>}</tbody></table></div></section>
      <section className="panel diagnostic-history"><div className="panel-heading"><div><h2>Monitor &amp; alert history</h2><p className="panel-subtitle">Latest 20 external checks. Provider acceptance is shown here; handset/inbox delivery and your response are separate.</p></div><Link className="text-button" href="/settings/alerts">Manage recipients <ArrowUpRight size={15} /></Link></div><p className="muted">{data.activeRecipients == null ? 'Recipient list could not be read.' : `${data.activeRecipients} active recipient records.`} You remain the sole responder unless you deliberately change the list.</p><div className="table-wrap"><table className="data-table"><thead><tr><th>Time · SAST</th><th>Checks</th><th>Alert</th><th>Provider acceptance</th><th>Evidence</th></tr></thead><tbody>{data.history.length ? data.history.map(row => <tr key={row.runId}><td>{time(row.checkedAt)}</td><td>Website: {row.readiness}<br />Backup/resources: {row.backup}</td><td>{row.kind ?? (row.status === 'HEALTHY_NO_NOTIFICATION' ? 'Healthy · no notification' : row.status)}<span className="secondary-cell">{row.recipientSource?.replaceAll('_', ' ') ?? 'Recipient source unavailable'}</span></td><td>{row.channels.filter(c => c.accepted || c.failed).map(c => `${c.channel}: ${c.accepted} accepted${c.failed ? `, ${c.failed} failed` : ''}`).join(' · ') || 'No sends recorded'}</td><td><a className="text-button" href={`https://github.com/blendproperty/stor24-portal/actions/runs/${row.runId}`} target="_blank" rel="noreferrer">Open run <ArrowUpRight size={14} /></a></td></tr>) : <tr><td colSpan={5}>No external monitor evidence has reached this dashboard yet. Check the monitor run and evidence-transfer step.</td></tr>}</tbody></table></div></section>
      <section className="diagnostic-footer"><CircleHelp size={20} /><p>Refresh and download do not restart services, retry messages or change customer records. If this website is down, this dashboard may also be unavailable: use your email/SMS/WhatsApp alerts and the independent GitHub monitor. Provider/device testing, independent recovery, training and business approval remain separate readiness items.</p></section>
    </>}
  </div>;
}
