"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { defaultVisualQuery } from "@/lib/visual-report-engine";
import { reportFieldLabel, visualReportSchema, type FilterOperator, type ReportDataset, type VisualReportQuery, type VisualReportRow } from "@/lib/visual-report-contract";
import { queryFromTemplate, type VisualReportTemplate } from "@/lib/visual-report-templates";
import { ReportOnlineInsights } from "@/components/report-online-insights";
import { ReportHistoryImporter } from "@/components/report-history-importer";

type Saved={id:string;name:string;definition:VisualReportQuery;revision:number;visibility:"PRIVATE"|"ORGANISATION";editable:boolean};
type Schedule={id:string;name:string;active:boolean;nextRunAt:string|null;lastRunAt:string|null;cronExpression:string};
type Run={id:string;format:string;status:string;rowCount:number|null;createdAt:string;completedAt:string|null;failureCode:string|null;expiresAt:string|null;scheduleId:string|null};
type Catalogue={datasets:ReportDataset[];templates:VisualReportTemplate[];saved:Saved[];schedules:Schedule[];runs:Run[];savedMore?:boolean;historyMore?:boolean;history?:{id:string;dataset:string;facilityId:string;name:string;extractedAt:string;rowCount:number}[]};
type Preview={rows:VisualReportRow[];query:VisualReportQuery;generatedAt:string;matchedRows:number;basis:string;grain:string};
const operators:Record<FilterOperator,string>={eq:"is",ne:"is not",contains:"contains",gt:"is greater than",gte:"is at least",lt:"is less than",lte:"is at most",isEmpty:"is not recorded",isNotEmpty:"is recorded"};
function allowedOperators(type: string):FilterOperator[] {return type==="text"?["eq","ne","contains","isEmpty","isNotEmpty"]:type==="boolean"?["eq","ne","isEmpty","isNotEmpty"]:["eq","ne","gt","gte","lt","lte","isEmpty","isNotEmpty"];}
function initialValue(type:string){return type==="money"?"0.00":type==="number"?0:type==="boolean"?true:"";}
const at=(value:string)=>new Date(value).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg"});
async function requestJson(body?:unknown) {
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);
  try {
    const response=await fetch("/api/v1/reports/builder",{method:body?"POST":"GET",cache:"no-store",signal:controller.signal,...(body?{headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{})});
    const payload=await response.json();
    if(!response.ok)throw new Error(payload.error?.message??"Reporting is unavailable. Your selections are retained.");
    return payload;
  }catch(error){if(error instanceof DOMException&&error.name==="AbortError")throw new Error("The request timed out. Reload saved reports before retrying a save.");throw error;}finally{clearTimeout(timer);}
}
export function VisualReportBuilder({facilities,from,to,canExport,canSchedule,canShare}:{facilities:{id:string;name:string}[];from:string;to:string;canExport:boolean;canSchedule:boolean;canShare:boolean}) {
  const [catalogue,setCatalogue]=useState<Catalogue|null>(null),[query,setQuery]=useState<VisualReportQuery|null>(null),[selected,setSelected]=useState<Saved|null>(null);
  const [tab,setTab]=useState<"library"|"build"|"view"|"saved"|"inbox"|"history">("library"),[group,setGroup]=useState("All"),[search,setSearch]=useState("");
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[failure,setFailure]=useState(false);
  const [preview,setPreview]=useState<Preview|null>(null),[format,setFormat]=useState<"CSV"|"XLSX"|"PDF">("XLSX"),[visibility,setVisibility]=useState<"PRIVATE"|"ORGANISATION">("PRIVATE");
  const [cadence,setCadence]=useState<"daily"|"weekly"|"monthly">("daily"),[batch,setBatch]=useState<string[]>([]);
  const heading=useRef<HTMLHeadingElement>(null),mounted=useRef(false),busyRef=useRef(false),saveKey=useRef<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setFailure(false);setMessage("");try{const result=await requestJson();if(!["datasets","templates","saved","schedules","runs"].every(key=>Array.isArray(result.data?.[key])))throw new Error("The report library could not be read. Please reload reporting.");if(!mounted.current)return;setCatalogue({...result.data,...result.meta});setQuery(previous=>previous??(result.data.datasets.length?defaultVisualQuery(result.data.datasets.find((d:ReportDataset)=>d.key==="units")?.key??result.data.datasets[0].key,from,to):null));}catch(error){if(mounted.current){setFailure(true);setMessage(error instanceof Error?error.message:"Unable to load reporting.");}}finally{if(mounted.current)setLoading(false);}},[from,to]);
  useEffect(()=>{mounted.current=true;const timer=setTimeout(()=>void load(),0);return()=>{mounted.current=false;clearTimeout(timer);};},[load]);
  const change=(patch:Partial<VisualReportQuery>)=>{setQuery(q=>q?{...q,...patch}:q);setPreview(null);setMessage("");};
  const choose=(next:VisualReportQuery,saved:Saved|null=null)=>{saveKey.current=null;setQuery(next);setSelected(saved);setVisibility(saved?.visibility??"PRIVATE");setPreview(null);setMessage("");setTab("build");setTimeout(()=>heading.current?.focus(),0);};
  const execute=async(action:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setMessage("");setFailure(false);try{await action();}catch(error){setFailure(true);setMessage(error instanceof Error?error.message:"Reporting request failed. Your selections are retained.");}finally{busyRef.current=false;setBusy(false);}};
  const dataset=catalogue?.datasets.find(d=>d.key===query?.dataset);
  const validation=query?visualReportSchema.safeParse(query):null;
  const outputKeys=query?(query.metrics.length?[...query.groupBy,...query.metrics.map(m=>`${m.operation}_${m.field}`)]:query.columns):[];
  const addMetric=()=>{if(!query||!dataset)return;change({metrics:[...query.metrics,{field:"*",operation:"count"}],sort:undefined});};
  const previewReport=(selection=query)=>execute(async()=>{setPreview(null);const result=await requestJson({kind:"preview",query:selection});setPreview({rows:result.data,...result.meta});});
  const download=()=>execute(async()=>{
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);
    try{const response=await fetch("/api/v1/reports/builder",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"export",query,format}),signal:controller.signal});
      if(!response.ok){const result=await response.json();throw new Error(result.error?.message??"Download unavailable.");}
      const blob=await response.blob();if(!blob.size)throw new Error("The report file was empty.");
      const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`stor24-${query?.name.replace(/[^a-zA-Z0-9-]/g,"-")??"report"}.${format.toLowerCase()}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`Prepared ${format} download.`);
    }finally{clearTimeout(timer);}
  });
  const save=()=>execute(async()=>{saveKey.current??=crypto.randomUUID();const result=await requestJson({kind:"save",query,visibility,...(selected?.editable?{id:selected.id,revision:selected.revision}:{requestKey:saveKey.current})});setSelected({...result.data,editable:true});await load();setMessage("Report saved. It runs against your current store permissions.");});
  const archive=(saved:Saved)=>execute(async()=>{await requestJson({kind:"archive",id:saved.id,revision:saved.revision});if(selected?.id===saved.id)setSelected(null);setBatch(b=>b.filter(id=>id!==saved.id));await load();setMessage("Report archived and its schedules paused.");});
  const schedule=()=>execute(async()=>{if(!selected||!query||JSON.stringify(visualReportSchema.parse(selected.definition))!==JSON.stringify(visualReportSchema.parse(query)))throw new Error("Save your changes before scheduling.");await requestJson({kind:"schedule",id:selected.id,cadence});await load();setMessage("Scheduled for 08:00 SAST. Snapshots will appear in your private report inbox.");});
  const batchDownload=()=>execute(async()=>{
    const response=await fetch("/api/v1/reports/batch",{method:"POST",headers:{"content-type":"application/json"},signal:AbortSignal.timeout(45000),body:JSON.stringify({ids:batch,format})});
    if(!response.ok){const payload=await response.json();throw new Error(payload.error?.message??"Batch export failed.");}
    const url=URL.createObjectURL(await response.blob()),link=document.createElement("a");link.href=url;link.download="stor24-report-bundle.zip";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Prepared report bundle.");
  });
  const categoryOrder=["Tenants","Units","Finance","Marketing","Management","Insurance","Merchandise","Deposits"];
  const groups=["All",...[...new Set(catalogue?.templates.map(t=>t.group)??[])].sort((a,b)=>{const rank=(g:string)=>categoryOrder.includes(g)?categoryOrder.indexOf(g):categoryOrder.length;return rank(a)-rank(b)||a.localeCompare(b);})];
  const filteredTemplates = catalogue?.templates.filter(t=>(group==="All"||t.group===group)&&`${t.name} ${t.group}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <div className="visual-report-workspace">
    <nav className="report-builder-tabs" aria-label="Reporting sections">{([['library','Report library'],['view','Online report'],['build','Build a report'],['saved','Saved reports'],['inbox','Schedules & history'],['history','SiteLink history']] as const).map(([key,label])=><button key={key} className={`button ${tab===key?'button-primary':'button-secondary'}`} disabled={busy} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {message&&<div role={failure?"alert":"status"} className="panel report-builder-feedback"><p>{message}</p>{failure&&<button className="button button-secondary" disabled={busy||loading} onClick={()=>void load()}>Reload reporting</button>}</div>}
    {loading&&!catalogue?<p role="status">Loading the report library…</p>:null}
    {catalogue&&!catalogue.datasets.length?<p>You do not have access to these datasets. Contact your administrator for report access.</p>:null}
    {tab==="library"&&catalogue&&<section className="panel panel-spacious"><div className="report-directory-brand"><strong>STOR24</strong><p>REPORT CENTRE / ONLINE INSIGHTS AND DOWNLOADS</p></div><div className="panel-heading"><div><h2>Report library</h2><p>Start from a template, then adjust its fields and filters. Each report states what its data represents.</p></div><button className="button button-primary" disabled={!query} onClick={()=>query&&choose(defaultVisualQuery(query.dataset,from,to))}>Create custom report</button></div>
      <div className="form-grid"><label>Find a report<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by report name…"/></label><label>Category<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label></div>
      <div className="report-library-categories">{groups.filter(category=>category!=="All" && filteredTemplates.some(t=>t.group===category)).map(category=><details className="report-library-category" key={`${category}-${group}-${search}`} open role="region" aria-label={`${category} reports`}><summary className="report-category-heading"><div><p className="eyebrow">REPORT CATEGORY</p><h3>{category}</h3></div><span>{filteredTemplates.filter(t=>t.group===category).length} reports</span></summary><div className="report-builder-library">{filteredTemplates.filter(t=>t.group===category).map(t=><article className="report-template-card" key={t.key}><h3>{t.name}</h3>{t.reason?<><span className="report-readiness">Data or definition required</span><p>{t.reason}</p></>:t.legacyKey?<><p>Use the existing report with its approved date basis and reconciliation checks.</p><a className="button button-secondary" href={`/reports?reportKey=${encodeURIComponent(t.legacyKey)}`}>View online and download</a></>:<>{t.nativeGap?<><span className="report-readiness">Imported history required</span><details className="report-card-details"><summary>Source requirements</summary><p>{t.nativeGap}</p><p>{catalogue.datasets.find(d=>d.key===t.dataset)?.grain}</p></details></>:<p>{catalogue.datasets.find(d=>d.key===t.dataset)?.grain}</p>}<div className="button-row"><button className="button button-secondary" disabled={busy} onClick={()=>{const next=queryFromTemplate(t,from,to);choose(next);if(!t.nativeGap){setTab("view");void previewReport(next);}}}>View online</button><button className="report-directory-customise" disabled={busy} onClick={()=>choose(queryFromTemplate(t,from,to))}>Use template</button></div></>}</article>)}</div></details>)}{!filteredTemplates.length&&<p className="report-library-empty">No reports match this search and category.</p>}</div>
    </section>}
    {tab==="build"&&query&&dataset&&<>
      <section className="panel panel-spacious"><h2 ref={heading} tabIndex={-1}>Build a report</h2><p>Choose what to show. All filters must match; totals use the dataset’s record grain.</p>
      <fieldset disabled={busy} className="report-builder-fieldset"><div className="form-grid">
        <label>Report name<input value={query.name} maxLength={100} onChange={e=>change({name:e.target.value})}/></label>
        <label>Dataset<select value={query.dataset} onChange={e=>choose(defaultVisualQuery(e.target.value,query.from,query.to))}>{catalogue?.datasets.map(d=><option key={d.key} value={d.key}>{d.name}</option>)}</select></label>
        <label>Record source<select value={query.historyImportId??""} onChange={e=>{const imported=catalogue?.history?.find(h=>h.id===e.target.value);change({historyImportId:e.target.value||undefined,...(imported?{facilityId:imported.facilityId}:{})});}}><option value="">{dataset.importOnly?"Select an imported extract…":"STOR24 recorded data"}</option>{catalogue?.history?.filter(h=>h.dataset===query.dataset).map(h=><option key={h.id} value={h.id}>{h.name} · Extracted {at(h.extractedAt)} SAST</option>)}</select></label>
        <label>Store<select value={query.facilityId??""} onChange={e=>change({facilityId:e.target.value||undefined})}><option value="">All permitted stores</option>{facilities.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label>
        <label>Date basis<select value={query.intervalMode?`interval:${query.intervalMode}`:query.dateField??""} onChange={e=>change(e.target.value.startsWith("interval:")?{dateField:undefined,intervalMode:e.target.value.slice(9) as "overlap"|"whole-period"}:{dateField:e.target.value||undefined,intervalMode:undefined})}><option value="">Current / all recorded data</option>{dataset.fields.filter(f=>f.type==="date").map(f=><option key={f.key} value={f.key}>{f.label}</option>)}{query.dataset==="occupancies"&&<><option value="interval:overlap">Occupied during any part of period</option><option value="interval:whole-period">Occupied for entire period</option></>}</select></label>
        <label>From (SAST)<input type="date" disabled={!query.dateField&&!query.intervalMode} value={query.from} onChange={e=>change({from:e.target.value})}/></label><label>To (SAST)<input type="date" disabled={!query.dateField&&!query.intervalMode} value={query.to} onChange={e=>change({to:e.target.value})}/></label>
      </div><div className="report-builder-basis"><strong>Data basis</strong><p>{query.historyImportId?`Imported SiteLink history, separate from current STOR24 records. Extracted ${catalogue?.history?.find(h=>h.id===query.historyImportId)?.extractedAt?at(catalogue.history.find(h=>h.id===query.historyImportId)!.extractedAt):"unavailable"} SAST. Unmapped fields remain unrecorded.`:dataset.basis}</p><p>{dataset.grain}</p></div>
      {dataset.importOnly&&!query.historyImportId&&<p role="status">This report requires a dated source extract. Import and validate its CSV in SiteLink history, then select it above. You can prepare and save the report layout now.</p>}<h3>Columns</h3><div className="report-field-picker">{dataset.fields.map(f=><label key={f.key}><input type="checkbox" checked={query.columns.includes(f.key)} onChange={e=>change({columns:e.target.checked?[...query.columns,f.key]:query.columns.filter(k=>k!==f.key),sort:undefined})}/><span>{f.label}{f.personal?<small>Personal data</small>:null}</span></label>)}</div>
      <details><summary>Column order ({query.columns.length})</summary><ol className="report-column-order">{query.columns.map((key,index)=><li key={key}><span>{reportFieldLabel(dataset,key)}</span><button type="button" aria-label={`Move ${reportFieldLabel(dataset,key)} up`} disabled={!index} onClick={()=>{const cols=[...query.columns];[cols[index-1],cols[index]]=[cols[index],cols[index-1]];change({columns:cols});}}>↑</button><button type="button" aria-label={`Move ${reportFieldLabel(dataset,key)} down`} disabled={index===query.columns.length-1} onClick={()=>{const cols=[...query.columns];[cols[index+1],cols[index]]=[cols[index],cols[index+1]];change({columns:cols});}}>↓</button></li>)}</ol></details>
      <div className="panel-heading"><h3>Filters</h3><button className="button button-secondary" disabled={query.filters.length>=20} onClick={()=>change({filters:[...query.filters,{field:dataset.fields[0].key,operator:"eq",value:""}]})}>Add filter</button></div>{!query.filters.length&&<p>No extra filters. Store permissions always apply.</p>}
      {query.filters.map((filter,index)=>{const field=dataset.fields.find(f=>f.key===filter.field)!;const update=(patch:Partial<typeof filter>)=>change({filters:query.filters.map((f,i)=>i===index?{...f,...patch}:f)});return <div className="report-builder-rule" key={index}><label>Filter {index+1} field<select value={filter.field} onChange={e=>{const chosen=dataset.fields.find(f=>f.key===e.target.value)!;update({field:chosen.key,operator:"eq",value:initialValue(chosen.type)});}}>{dataset.fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>Condition<select value={filter.operator} onChange={e=>update({operator:e.target.value as FilterOperator})}>{allowedOperators(field.type).map(op=><option key={op} value={op}>{operators[op]}</option>)}</select></label>{!["isEmpty","isNotEmpty"].includes(filter.operator)&&<label>Value{field.type==="boolean"?<select value={String(filter.value)} onChange={e=>update({value:e.target.value==="true"})}><option value="true">Yes</option><option value="false">No</option></select>:<input type={field.type==="date"?"date":["money","number"].includes(field.type)?"number":"text"} step="any" value={String(filter.value??"")} onChange={e=>update({value:field.type==="number"?(e.target.value===""?"":Number(e.target.value)):e.target.value})}/>}</label>}<button className="button button-secondary" aria-label={`Remove filter ${index+1}`} onClick={()=>change({filters:query.filters.filter((_,i)=>i!==index)})}>Remove</button></div>;})}
      <div className="panel-heading"><h3>Grouping and totals</h3><button className="button button-secondary" disabled={query.metrics.length>=8} onClick={addMetric}>Add total</button></div><p>For a detailed list, leave totals empty. To combine records, add a total and choose up to three grouping fields. Money totals require currency grouping where currencies are recorded.</p>
      <div className="report-group-picker">{dataset.fields.filter(f=>["text","boolean"].includes(f.type)).map(f=><label key={f.key}><input type="checkbox" disabled={!query.groupBy.includes(f.key)&&query.groupBy.length>=3} checked={query.groupBy.includes(f.key)} onChange={e=>change({groupBy:e.target.checked?[...query.groupBy,f.key]:query.groupBy.filter(k=>k!==f.key),sort:undefined})}/>{f.label}</label>)}</div>
      {query.metrics.map((metric,index)=>{const update=(patch:Partial<typeof metric>)=>change({metrics:query.metrics.map((m,i)=>i===index?{...m,...patch}:m),sort:undefined});return <div className="report-builder-rule" key={index}><label>Total {index+1}<select value={metric.operation} onChange={e=>{const operation=e.target.value as typeof metric.operation;update({operation,field:operation==="count"?"*":dataset.fields.find(f=>["money","number"].includes(f.type))?.key??"*"});}}>{['count','sum','average','min','max'].map(op=><option key={op} value={op}>{({count:"Count records",sum:"Sum",average:"Average",min:"Minimum",max:"Maximum"} as Record<string,string>)[op]}</option>)}</select></label>{metric.operation!=="count"&&<label>Amount / number<select value={metric.field} onChange={e=>update({field:e.target.value})}>{dataset.fields.filter(f=>["money","number"].includes(f.type)).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>}<button className="button button-secondary" aria-label={`Remove total ${index+1}`} onClick={()=>change({metrics:query.metrics.filter((_,i)=>i!==index),sort:undefined})}>Remove</button></div>;})}
      <div className="form-grid"><label>Sort by<select value={query.sort?.field??""} onChange={e=>change({sort:e.target.value?{field:e.target.value,direction:query.sort?.direction??"asc"}:undefined})}><option value="">Default order</option>{outputKeys.map(key=><option key={key} value={key}>{reportFieldLabel(dataset,key)}</option>)}</select></label>{query.sort&&<label>Sort direction<select value={query.sort.direction} onChange={e=>change({sort:{field:query.sort!.field,direction:e.target.value as "asc"|"desc"}})}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label>}<label>Download format<select aria-label="Download format" value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="XLSX">Excel (.xlsx)</option><option value="PDF">PDF</option><option value="CSV">CSV</option></select></label>{canShare&&<label>Saved definition visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as typeof visibility)}><option value="PRIVATE">Only me</option><option value="ORGANISATION">Organisation template</option></select></label>}</div>
      {validation&&!validation.success&&<p className="report-validation" role="status">{validation.error.issues[0].message}</p>}
      <div className="button-row"><button className="button button-primary" disabled={!validation?.success||(dataset.importOnly&&!query.historyImportId)} onClick={()=>void previewReport()}>Preview report</button><button className="button button-secondary" disabled={!validation?.success||!canExport||(dataset.importOnly&&!query.historyImportId)} onClick={()=>void download()}>Download {format}</button><button className="button button-secondary" disabled={!validation?.success} onClick={()=>void save()}>{selected?.editable?"Save changes":"Save report"}</button>{selected&&<button className="button button-secondary" onClick={()=>choose({...query,name:`${query.name.slice(0,85)} (copy)`})}>Duplicate</button>}</div>
      {canSchedule&&selected?.editable&&<div className="report-schedule-actions"><label>Schedule<select value={cadence} onChange={e=>setCadence(e.target.value as typeof cadence)}><option value="daily">Daily, previous day</option><option value="weekly">Mondays, previous 7 days</option><option value="monthly">First of month, previous month</option></select></label><button className="button button-secondary" onClick={()=>void schedule()}>Schedule saved report</button><p>Runs at 08:00 SAST into your private report inbox. The saved definition is pinned when scheduled; changing it requires a new schedule.</p></div>}
      </fieldset>{busy&&<p role="status">Preparing your request…</p>}</section>
    </>}
    {(tab==="view"||tab==="build")&&preview&&dataset&&<section className="panel panel-spacious report-builder-preview" aria-label="Report results"><h2>{preview.query.name}</h2><p>{preview.rows.length} result rows · {preview.matchedRows} matching records · Generated {at(preview.generatedAt)} SAST</p><p>{preview.basis}</p><ReportOnlineInsights key={preview.generatedAt} rows={preview.rows} query={preview.query} dataset={dataset} matchedRows={preview.matchedRows}/></section>}
    {tab==="view"&&query&&dataset&&<section className="panel panel-spacious"><div className="button-row"><button className="button button-secondary" disabled={busy} onClick={()=>setTab("build")}>Adjust fields and filters</button><button className="button button-secondary" disabled={busy||!canExport} onClick={()=>void download()}>Download {format}</button><button className="button button-secondary" disabled={busy} onClick={()=>void previewReport()}>Refresh report</button></div><label>Online download format<select value={format} disabled={busy} onChange={e=>setFormat(e.target.value as typeof format)}><option value="PDF">PDF</option><option value="XLSX">Excel (.xlsx)</option><option value="CSV">CSV</option></select></label><p>Downloads use the full selected report.</p>{busy&&<p role="status">Preparing online report…</p>}</section>}
    {tab==="saved"&&catalogue&&<section className="panel panel-spacious"><h2>Saved reports</h2><p>Definitions are saved; every run uses your current permissions and current database records.</p>{catalogue.savedMore&&<p role="status">Showing the first 200 accessible definitions. Narrow the catalogue with an administrator before adding more shared templates.</p>}{!catalogue.saved.length&&<p>You have no saved reports yet.</p>}<div className="report-builder-library">{catalogue.saved.map(s=><article className="report-template-card" key={s.id}><h3>{s.name}</h3><p>{s.visibility==="PRIVATE"?"Private":"Organisation template"} · Revision {s.revision}</p><div className="button-row"><button className="button button-secondary" disabled={busy} onClick={()=>choose(s.definition,s)}>Open report</button>{s.editable&&<button className="button button-secondary" disabled={busy} onClick={()=>void archive(s)}>Archive</button>}</div>{canExport&&<label><input type="checkbox" checked={batch.includes(s.id)} disabled={busy||(!batch.includes(s.id)&&batch.length>=5)} onChange={e=>setBatch(b=>e.target.checked?[...b,s.id]:b.filter(id=>id!==s.id))}/>Include in bundle</label>}</article>)}</div>{canExport&&<div className="button-row"><label>Bundle format<select value={format} disabled={busy} onChange={e=>setFormat(e.target.value as typeof format)}><option value="XLSX">Excel</option><option value="PDF">PDF</option><option value="CSV">CSV</option></select></label><button className="button button-primary" disabled={busy||!batch.length} onClick={()=>void batchDownload()}>Download selected reports ({batch.length}/5)</button></div>}</section>}
    {tab==="history"&&catalogue&&<><section className="panel panel-spacious"><h2>Imported SiteLink history</h2><p>Each extract retains its source fingerprint, extraction date and approval reference. It remains separate from current STOR24 records.</p>{catalogue.historyMore&&<p role="status">Showing the most recent 200 accessible extracts.</p>}{!catalogue.history?.length?<p>No reporting history extracts are available for your stores and datasets.</p>:catalogue.history.map(h=><article className="report-schedule-card" key={h.id}><div><strong>{h.name}</strong><p>{h.rowCount} records · {at(h.extractedAt)} SAST</p></div><button className="button button-secondary" onClick={()=>choose({...defaultVisualQuery(h.dataset,from,to),historyImportId:h.id,facilityId:h.facilityId})}>Build from history</button></article>)}</section>{canShare&&<ReportHistoryImporter datasets={catalogue.datasets} facilities={facilities} onImported={load}/>}</>}
    {tab==="inbox"&&catalogue&&<section className="panel panel-spacious"><div className="panel-heading"><h2>Schedules and run history</h2><button className="button button-secondary" disabled={busy||loading} onClick={()=>void load()}>Refresh history</button></div><p>Scheduled snapshots are private, encrypted and expire according to the configured retention period. Downloads recheck your current access. Failed runs do not produce a file.</p><h3>Schedules</h3>{!catalogue.schedules.length&&<p>No schedules yet. Open a saved report to schedule it.</p>}{catalogue.schedules.map(s=><article className="report-schedule-card" key={s.id}><div><strong>{s.name}</strong><p>{s.active?`Active · Next ${s.nextRunAt?at(s.nextRunAt):"pending"} SAST`:"Paused"}</p></div>{s.active&&<button className="button button-secondary" disabled={busy} onClick={()=>void execute(async()=>{await requestJson({kind:"pause",id:s.id});await load();setMessage("Schedule paused.");})}>Pause schedule</button>}</article>)}<h3>Recent runs</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Requested (SAST)</th><th>Format</th><th>Status</th><th>Rows</th><th>Result</th></tr></thead><tbody>{catalogue.runs.map(r=><tr key={r.id}><td>{at(r.createdAt)}</td><td>{r.format}</td><td>{r.status}{r.failureCode?` · ${r.failureCode}`:""}</td><td>{r.rowCount??"—"}</td><td>{r.scheduleId&&r.status==="SUCCEEDED"&&r.expiresAt&&new Date(r.expiresAt)>new Date()?<a className="button button-secondary" href={`/api/v1/reports/runs/${encodeURIComponent(r.id)}?format=XLSX`}>Download snapshot</a>:r.expiresAt?"Expired / unavailable":r.format==="PREVIEW"?"Viewed":"Run metadata"}</td></tr>)}</tbody></table></div>{!catalogue.runs.length&&<p>No recorded runs yet.</p>}</section>}
  </div>;
}
