import { addLeadAction, reserveAction } from "@/app/actions/leasing";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { listLeasing } from "@/lib/leasing-service";
import { requireScope } from "@/lib/scope";
import { unitTypeLabel } from "@/lib/unit-type-label";
export const metadata = { title: "Lead to lease" };
export default async function LeadsPage(){const data=await listLeasing(await requireScope());const units=data.facilities.flatMap(f=>f.units.filter(u=>u.status==="AVAILABLE"));return <div className="page-stack"><PageHeader eyebrow="Sales pipeline" title="Lead to lease" description="Capture, qualify and reserve real inventory for real customer records."/>
<section className="panel panel-spacious"><h2>Add lead</h2><form action={addLeadAction} className="leasing-form"><select name="facilityId" required>{data.facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select name="customerId" required><option value="">Customer</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.companyName||`${c.firstName} ${c.lastName}`}</option>)}</select><input name="source" placeholder="Source" required/><input name="expectedMoveIn" type="date"/><button className="button button-primary">Add lead</button></form><h2>Reserve available unit</h2><form action={reserveAction} className="leasing-form"><select name="facilityId" required>{data.facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select name="customerId" required>{data.customers.map(c=><option key={c.id} value={c.id}>{c.companyName||`${c.firstName} ${c.lastName}`}</option>)}</select><select name="unitId" required>{units.map(u=><option key={u.id} value={u.id}>{u.number} — R {Number(u.monthlyRate)}</option>)}</select><input name="quotedRate" type="number" step=".01" placeholder="Quoted rate" required/><input name="intendedMoveIn" type="date"/><button className="button button-secondary">Reserve</button></form></section>
<section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Prospect</th><th>Facility</th><th>Source</th><th>Requirement</th><th>Stage</th></tr></thead><tbody>{data.leads.map(l=><tr key={l.id}><td className="primary-cell">{l.customer?.companyName||`${l.customer?.firstName??""} ${l.customer?.lastName??""}`}</td><td>{l.facility.name}</td><td>{l.source}</td><td>{l.desiredUnitType ? unitTypeLabel(l.desiredUnitType) : "Open"}</td><td><StatusPill>{l.stage}</StatusPill></td></tr>)}</tbody></table></div></section></div>}
